### ISSUE TITLE
Elevate Item Sorting

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#775] opened 2016-08-10 18:36 UTC
As users approach max light, the usefulness of sorting by light drops.  Making item sort more accessible without going into settings would make the feature more likely to be used.

We can have options to sort by:

1. Light
2. Rarity
3. Name
4. Elemental

**Comment by bhollis** [comment] 2016-08-11 05:37
Potentially related to / duplicate of #647?

**Closed** 2016-08-18 15:00 UTC
