### ISSUE TITLE
Editing an existing Loadout using Optimize Armor loads a generic loadout

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7869] opened 2022-02-15 19:29 UTC
### DIM Version

Version 7.5.1.1001295 (beta), built on 2/14/2022, 4:10:38 PM

### Browser Details

Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)

### OS Details

MacOS 12.3 beta (21E5206e)

### Describe the bug

From the main "Inventory" I clicked on my Warlock, scrolled to an existing loadout with armor mods, clicked on the ✎ (Edit) icon, clicked on "Optimize Armor" and I expected the loadout to open in "Loadout Optimizer" with the mods populated and the armor from the loadout pinned but instead loadouts with no mods and no pinned items was loaded sorted in descending Tier order.

**Comment by zacgoodwin** [comment] 2022-02-15 19:53
FYI; if you need a workaround I found one here: 

https://github.com/DestinyItemManager/DIM/issues/7867#issue-1139124276

**Comment by bhollis** [comment] 2022-02-15 20:27
Closing as a duplicate of #7867

**Closed** 2022-02-15 20:27 UTC
Labels: Bug
