### ISSUE TITLE
Crash after switching characters (iPhone)

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#5321] opened 2020-06-15 16:01 UTC
**What version of DIM are you using?**
Version 6.15.0 (release), built on 6/14/2020, 2:46:57 PM
Orange icon 

**What Browser and OS are you using?**
Safari, iOS 13.5 on an iPhone 8 Plus. 

**Describe the bug and how to make it happen**
After switching characters *in destiny* DIM crashes as I swipe to the new character. This didn’t happen a few weeks ago.

**Comment by bhollis** [comment] 2020-06-15 17:58
Possibly related to https://github.com/DestinyItemManager/DIM/issues/5100

**Comment by mannyrye** [comment] 2020-06-15 20:54
BTW the error I get is #185

**Comment by bhollis** [comment] 2020-06-17 04:00
Sentry issue: [DIM-GYX](https://sentry.io/organizations/destiny-item-manager/issues/1615745749/?referrer=github_plugin)

**Comment by bhollis** [comment] 2020-09-19 04:43
Closing as dupe of #5109

**Closed by bhollis** 2020-09-19 04:43 UTC
Labels: Bug
