### ISSUE TITLE
armor2.0 element should need to match to be considered dupe

### ISSUE THREAD

**Issue by Ragnarok96** [DestinyItemManager/DIM#4481] opened 2019-10-16 05:28 UTC
With solar, arc and void on armour pieces now I think is:dupe should not highlight pieces if they is only 1 with the same name and element

**Comment by bhollis** [comment] 2019-10-19 05:18
Duplicate of #4435, I think?

**Comment by sundevour** [comment] 2019-10-19 05:21
my understanding is
"armor2.0 element should need to match to be considered dupe"

**Comment by bhollis** [comment] 2019-10-19 21:05
Right, isn't that also what #4435 was saying?

**Comment by sundevour** [comment] 2019-10-20 00:50
i thought #4435 requested element+capacity to be shown in the comparison popup, but i can see now it could be interpreted differently, we'll fold this in either way.

**Closed by sundevour** 2019-10-20 00:50 UTC
Labels: Feature: Search
