### ISSUE TITLE
iPadOS sheet positioning is wrong

### ISSUE THREAD

**Issue by wdesmet** [DestinyItemManager/DIM#9317] opened 2023-03-28 20:17 UTC
### DIM Version

DIM (Destiny Item Manager) Version 7.62.0 (release), built on 27-3-2023 04:08:01 DIM AppStore 7 - Mac OS 10.15.7

### Browser Details

App store version (ios safari)

### OS Details

ios, ipad air last gen

### Describe the bug

On the loadouts screem, press loadouts optimizer. Select subclass. Then customize subclass. On my device this materializes halfway up the screen, then either needs to be dragged down or tapped when dragging doesnt work. Attached a static view of the broken state. 
![E0B3FD21-CC90-4B16-95A8-3D5F27252551](https://user-images.githubusercontent.com/181424/228356650-883a7c97-7b64-4e47-b3b4-10e0285c89b1.jpeg)

**Comment by robojumper** [comment] 2023-03-28 23:21
Probably a duplicate of #9240.

**Comment by bhollis** [comment] 2023-03-29 00:53
There's a couple of different things going on that I haven't tracked down - basically we try to figure out the keyboard height in order to show the sheet over the keyboard, but Safari is very quirky.

**Comment by ferazambuja** [comment] 2023-06-07 16:36
A minor gripe when using on the iPad is the keyboard automatically shows when selecting mods or artifacts. Probably because the search field is automatically active on those windows instead of the user clicking on it. 
This behavior makes more sense for the desktop, but the keyboard takes too much space on mobile and tablet. 

![IMG_1651](https://github.com/DestinyItemManager/DIM/assets/12782082/880342e3-dcc0-4193-a20b-68d2bc46387c)

**Comment by bhollis** [comment] 2023-06-07 17:13
It's not supposed to, assuming we can detect that you're on iOS/iPadOS. If you're forcing the desktop version it won't be able to.

**Comment by ferazambuja** [comment] 2023-06-07 17:34
Thanks, I’ve checked, and on Safari, it only does if you request the desktop version.

 However, on the native iOS app, it does that. Sorry for the crappy gif, but I believe it can demonstrate. 

![RPReplay_Final1686158457](https://github.com/DestinyItemManager/DIM/assets/12782082/c81fc24b-703f-4667-83b5-b601e599a52a)

**Closed** 2023-06-08 20:09 UTC
Labels: Bug, Mobile Interface
