### ISSUE TITLE
LoadoutBuilder.Nothing cannot be selected

### ISSUE THREAD

**Issue by rentalhost** [DestinyItemManager/DIM#6849] opened 2021-06-16 14:43 UTC
Open the Loadout Builder, modify the new option to something else and try to back to "nothing". It will not works and the previous option will keep actived.

https://github.com/DestinyItemManager/DIM/blob/0fabcc9aa4b40886f33d70ffb9a11e9bbe14044c/src/app/loadout-builder/filter/FilterBuilds.tsx#L61-L69

**Comment by bhollis** [comment] 2021-06-16 15:56
Duplicate of #6848

**Closed by bhollis** 2021-06-16 15:56 UTC
