### ISSUE TITLE
Suggestion: Transfer to character / vault from item compare popup

### ISSUE THREAD

**Issue by jkewley** [DestinyItemManager/DIM#4709] opened 2019-11-14 15:52 UTC
With Armor 2.0 I find myself using the comparison tool quite a bit to decide if I should keep or trash an item. I'll swap keep/trash tags and unlock the one I want to get rid of, the click the name to find it in inventory and drag drop to the character to prepare it for deletion.

I'd love to instead have a 'to vault' and 'to character' button in the item description window of the popup so I don't have to leave the current context.

I've done the hard work of producing a pixel-perfect mock up for you with my top-tier design skills, so the rest should be fairly easy.

![image](https://user-images.githubusercontent.com/1148930/68872825-46d5e100-06c4-11ea-85fd-2061ebdcf621.png)

**Comment by Wh1rledPeas** [comment] 2019-11-14 19:45
Actually, I'd like to see the icons turned into active buttons, so tapping on them would pull up the default move/equip buttons.

**Comment by bhollis** [comment] 2019-11-15 16:24
Duplicate of #3833

**Closed by bhollis** 2019-11-15 16:24 UTC
Labels: Feature: Item Comparison
