### ISSUE TITLE
Implement saved searches

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#2954] opened 2018-08-08 06:51 UTC
I have a bunch of standard searches I do, but there is no way to save them and have them available from a drop menu.  So each time I need to enter them over again.  This is a pain on an iPad.

It would be very useful to be able to create searches similar to the way you can create loadouts.

**Comment by bhollis** [comment] 2018-09-06 07:36
Duplicate of #1874.

**Closed by bhollis** 2018-09-06 07:36 UTC
Labels: Feature: Search
