### ISSUE TITLE
More Inventory Display Options for Vault

### ISSUE THREAD

**Issue by adammand** [DestinyItemManager/DIM#6050] opened 2020-10-21 14:12 UTC
Would like to be able to customize the layout of how items are displayed on the inventory screen. Despite being able to change sort options, the layout (particularly with three different character types and a large vault) can look pretty cluttered.

At a minimum, it would be nice to have an option for armor sorting in the vault to begin new classes with a new line and the character sign rather than just the sign. Spacer headings above vault areas (for kinetic, energy, heavy, and all armor types) would be nice as well. Sometimes when I'm looking for a kinetic depending on where I'm scrolled at I catch myself looking in the energy locations. Armor can run together somewhat too. The vault is spatially distant from the headings near the characters (which are limited to weapons/armor) so some labelling and whitespace within the vault sections themselves would probably help. Rather than having to look for the different pictures of different types, it'd be much easier to just read the "Arms" or "Energy" heading above the vault items.

**Comment by bhollis** [comment] 2020-10-21 17:57
Duplicate of https://github.com/DestinyItemManager/DIM/issues/3613

**Closed by bhollis** 2020-10-21 17:57 UTC
Labels: Enhancement
