### ISSUE TITLE
Cache data for offline use for when the API is down/no internet connection

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#3140] opened 2018-09-27 17:36 UTC
It would be cool if we could cache items so that when you do not have an internet connection, or the bungie API is down we could continue development.

It would also be useful for users as they could continue to do item management... just maybe not moving items, unless we  batched the moves... which is probably more work than it's worth.

Another (possibly simpler) option is to have a mock server that we (developers) could point to returns static data.

**Comment by bhollis** [comment] 2018-09-27 21:36
I think of this every time the API is down and then forget it once the API is back...

**Comment by bhollis** [comment] 2018-09-28 04:12
Duplicate of #2164.

**Closed by bhollis** 2018-09-28 04:12 UTC
Labels: Enhancement

**Comment by Revadike** [comment] 2024-11-20 17:14
This is not working for me
![image](https://github.com/user-attachments/assets/3a07d9e0-8d65-4cc2-9cd1-e139b9d7e95b)
