### ISSUE TITLE
Improve Platform Selection

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#684] opened 2016-07-09 19:14 UTC
Users are getting Destiny Account errors and they are confused.  The issue is they are using the wrong platform.  If you associate Xbox and Playstation accounts with Bungie, we get both in the resultset, even if you haven't played.  If the default is the platform the player hasn't  played, they get this error.

If we get this error when querying the endpoint, then we should swap to another platform if the user has one.

If we still get the error (unusual), then we should have a better error message in this case.

**Comment by bhollis** [comment] 2016-08-08 07:36
Duplicate of #329.

**Closed by bhollis** 2016-08-08 07:36 UTC
Labels: enhancement
