### ISSUE TITLE
Sync item lock state with tag doesn't work with shaped weapons

### ISSUE THREAD

**Issue by crazycrank** [DestinyItemManager/DIM#9604] opened 2023-07-09 04:37 UTC
### DIM Version

Version 7.75.0 (release), built on 03/07/2023, 10:36:15 am

### Browser Details

Edge 114.0.1823.67

### OS Details

Windows 10

### Describe the bug

I just almost deleted a shaped weapon I have tagged as "Keep", while absently deleting half my vault.

I tried a couple of different things, like different tags, clearing everything and reapplying it, legendary and exotic shaped weapons, but the gist is, shaped weapons don't get their lock state synced to the applied tags.

Interestingly, manually locking them displays both the lock state and the tag which it doesn't do for other weapons types. So this makes me think it's a deliberate decision? I haven't tried this, but probably locked weapons can't be reshaped?

If this is the case, I think this is a design issue. As a user, I expect tagged weapons to be locked accordingly. To me, this is the indicator if I can dismantle or infuse a weapon, or if I want to keep it for now. Not locking them in-game will absolutely lead to accidental dismantles, because there's a misalignment in expectations and outcome of lockstate.

Please fix this

**Comment by bhollis** [comment] 2023-07-09 05:35
Yes, this is intentional. Crafted weapons are clearly wanted, and are marked in the UI. At the same time, auto-locking them makes it difficult to reshape them because the game will not allow reshaping locked weapons. So DIM does not automatically lock them.

**Comment by robojumper** [comment] 2023-07-09 05:55
This behavior is also called out on the Settings page:

> Crafted items will remain unlocked to allow reshaping.

**Comment by crazycrank** [comment] 2023-07-09 06:06
> This behavior is also called out on the Settings page:
> 
> > Crafted items will remain unlocked to allow reshaping.

I missed that tbh.
But the risk management of accidentally dismantling them is still considerable. Sometime we dismantle hundreds of weapons at once to clear out the vault, which, let's be honest, we're mostly not doing with full attention.
In the other hand, reshaping a locked weapon requires one additional click to unlock it first, which isn't too annoying.

I feel the trade-off here isn't that bad and should be reconsidered?

**Comment by robojumper** [comment] 2023-07-09 06:34
The problem is that otherwise, DIM will automatically re-lock the item as you are reshaping it, preventing you from completing the reshape, so you have to quit out of the screen and discard your changes.

Before a dismantling session, you can always [lock these items in bulk](https://github.com/DestinyItemManager/DIM/wiki/Item-Search#bulk-actions) - search for `is:crafted`, hit the three dots, Lock Items.

**Comment by andrewpong** [comment] 2023-07-14 00:38
> I feel the trade-off here isn't that bad and should be reconsidered?

When the auto-lock tag sync feature was first rolled out it'd be a fun minigame to reshape weapons before DIM auto-locked my weapons, hah. I actually didn't notice until reading your post that DIM had modified the behavior to exclude crafted weapons to address this.

**Comment by bhollis** [comment] 2023-07-14 18:29
Closing as this is intended, documented behavior.

**Closed by bhollis** 2023-07-14 18:29 UTC
Labels: Bug
