### ISSUE TITLE
Auto Tagged Searches

### ISSUE THREAD

**Issue by graytonio** [DestinyItemManager/DIM#9545] opened 2023-06-05 14:58 UTC
### Proposed change

When I have a saved search for finding specific items I want to be able to set that search to have a specific tag so when items are added to my inventory that match the search they will be automatically be tagged.  This could happen as part of the auto refresh so when items are updated into the system they are already tagged. 

### How does this fit into your workflow?

Instead of having to have an item feed up and leaving the game to tag items I can instead setup a set of searches that I want to always be marked with a certain tag. This means I don't have to constantly switch between the game and DIM when I want to just relax and play the game. This could be even more powerful when paired with the farming mode so after a session items are automatically marked.

**Comment by graytonio** [comment] 2023-06-05 15:15
I think it could be achieved by adding an observer to the allItemsSelector or newItemsSelector and doing the search filter with the configured tag.

**Comment by bhollis** [comment] 2023-06-05 20:10
Duplicate of https://github.com/DestinyItemManager/DIM/issues/7219

**Closed** 2023-06-05 20:10 UTC
Labels: Enhancement
