### ISSUE TITLE
Add the ability to load a shared DIM loadout to the iOS App Store DIM app

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8569] opened 2022-07-14 10:38 UTC
### Proposed change

Add the ability to load a shared DIM loadout to the iOS App Store DIM app.
Right now the workaround is to use Safari.

### How does this fit into your workflow?

Would be able to import loadouts directly to the app.

**Comment by bhollis** [comment] 2022-07-15 00:39
Duplicate of https://github.com/DestinyItemManager/iOS/issues/16

**Closed by bhollis** 2022-07-15 00:39 UTC
Labels: Enhancement
