### ISSUE TITLE
Ghost/Vehicles/Ships stuck on 'review'-tab when switching from a weapon in review-tab

### ISSUE THREAD

**Issue by darkelement1987** [DestinyItemManager/DIM#3550] opened 2019-01-13 11:18 UTC
Steps to reproduce:

1. Click on any weapon
2. Click the review tab and leave it
3. Click on a vehicle/ship/ghost

Stuck on review-tab and unable to switch back to 'overview'

System:

Win 10
Chrome 71.0.3578.98
Using DIM Beta.

![image](https://user-images.githubusercontent.com/21128187/51084613-2d26de80-172d-11e9-938f-c0f36a2ac58e.png)

![image](https://user-images.githubusercontent.com/21128187/51084618-3d3ebe00-172d-11e9-8f02-8f8af86a4866.png)

![image](https://user-images.githubusercontent.com/21128187/51084620-4760bc80-172d-11e9-9a2a-440dfa6d6746.png)

**Comment by delphiactual** [comment] 2019-01-13 16:07
Steps to reproduce:

1. Click on any weapon
2. Click the review tab ~and leave it~
3. Click on a vehicle/ship/ghost

Stuck on review-tab and unable to switch back to 'overview'

**Comment by inexorableAce** [comment] 2019-01-13 16:46
Someone had mentioned that when entering notes on one item, then clicking another item the Same notes text persisted. This could be the same issue, I assume some issue with the item pop up not refreshing or some components of it not refreshing.

**Comment by delphiactual** [comment] 2019-01-13 17:20
It appears to be more of a remember my selection bug, that is not taking into account for !reviewable

**Comment by bhollis** [comment] 2019-01-13 17:34
Yeah a lot of the old Angular components didn’t properly implement `$onChange` and thus don’t handle switching items without closing the popup inbetween. We can add a `key` property to force the component to be remounted until it can be rewritten.

**Comment by bhollis** [comment] 2019-01-13 17:35
#3549 is probably different and is related to the perk rating data not getting loaded into redux properly.

**Comment by delphiactual** [comment] 2019-01-13 20:53
I more meant related due to the port to react of item popup

**Closed** 2019-01-13 22:20 UTC
