### ISSUE TITLE
Auto lock items that are in a wish list

### ISSUE THREAD

**Issue by jgkawell** [DestinyItemManager/DIM#7356] opened 2021-12-05 01:22 UTC
### Proposed change

Whenever a player collects a new item that matches something in a wish list, automatically lock that item.

### How does this fit into your workflow?

Very often I collect a drop of an item and I'm not immediately sure in game if it's the exact roll I was looking for. If DIM would automatically apply a lock to the item, I would know not to dismantle it and then could check DIM to see which wish list item it matches. This would keep me from having to quickly bounce back and forth between the game and DIM whenever I get a dop that looks like it might be a god roll.

**Comment by delphiactual** [comment] 2021-12-05 01:23
#7219

**Comment by bhollis** [comment] 2021-12-05 02:06
Closing as a duplicate of #7219

**Closed** 2021-12-05 02:08 UTC
Labels: Enhancement
