### ISSUE TITLE
Chrome: all filters hang DIM

### ISSUE THREAD

**Issue by abbotn** [DestinyItemManager/DIM#2055] opened 2017-08-01 11:35 UTC
If I type any filter like "is:arc" and hit Enter...I have to kill the browser tab and reload DIM.

**Comment by gmcbay** [comment] 2017-08-02 05:26
Pretty sure this is a duplicate of issue #2054 

The problem isn't browser specific.  It could be something to do with specific Bungie data which might be why the devs reportedly can't reproduce, but this is happening to me on all browsers.

**Comment by bhollis** [comment] 2017-08-02 05:55
It's a bug in the text complete library. I'll have a fix tomorrow or Thursday 

-Ben

**Comment by bhollis** [comment] 2017-08-02 06:26
Duplicate of #2054.

**Closed by bhollis** 2017-08-02 06:26 UTC
