### ISSUE TITLE
DIM not loading

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1555] opened 2017-03-25 22:31 UTC
https://www.reddit.com/r/DestinyItemManager/comments/61hukr/dim_not_loading_properly_blank_inventory_screen/

```
Failed to load resource: net::ERR_CONNECTION_CLOSED
2main-8ac02d.js:1 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest": [null],"transformResponse": [null],"jsonpCallbackParam":"callback","url":"https://beta.destinyitemmanager.com/data/classified.json","headers":{"Accept":"application/json, text/plain, /"}},"statusText":""}
```

**Comment by delphiactual** [comment] 2017-03-26 00:29
https://www.reddit.com/r/DestinyItemManager/comments/60p0c9/error_loading_destiny_info_bungienet_may_be/

DIM v3.17.0 (release) - Please report any errors to https://www.reddit.com/r/destinyitemmanager www.bungie.net/common/destiny_content/sqlite/en/world_sql_content_64ba059d78e743476271c13d9ff5feff.content?host=apghicjnekejhfancbkahkhdckhdagna Failed to load resource: net::ERRFAILED dimDefinitions.factory.js:64 Objectconfig: Objectdata: nullheaders: function (n)status: -1statusText: ""proto: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()defineGetter: function __defineGetter()defineSetter: function __defineSetter()lookupGetter: function __lookupGetter()lookupSetter: function __lookupSetter()get __proto: function __proto()set __proto: function __proto_() (anonymous) @ dimDefinitions.factory.js:64
3angular.js:14516 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","responseType":"blob","url":"https://www.bungie.net/common/destiny_content/sqlite/en/world_sql_content_6…059d78e743476271c13d9ff5feff.content?host=apghicjnekejhfancbkahkhdckhdagna","headers":{"Accept":"application/json, text/plain, /"}},"statusText":""} (anonymous) @ angular.js:14516 2angular.js:14516 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","responseType":"blob","url":"https://www.bungie.net/common/destiny_content/sqlite/en/world_sql_content_6…059d78e743476271c13d9ff5feff.content?host=apghicjnekejhfancbkahkhdckhdagna","headers":{"Accept":"application/json, text/plain, /"}},"statusText":""} (anonymous) @ angular.js:14516 (anonymous) @ angular.js:11004 l @ angular.js:16871 $digest @ angular.js:17982 (anonymous) @ angular.js:18211 i @ angular.js:6274 (anonymous) @ angular.js:6554 angular.js:14516 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","responseType":"blob","url":"https://www.bungie.net/common/destiny_content/sqlite/en/world_sql_content_6…059d78e743476271c13d9ff5feff.content?host=apghicjnekejhfancbkahkhdckhdagna","headers":{"Accept":"application/json, text/plain, /"}},"statusText":""} (anonymous) @ angular.js:14516 (anonymous) @ angular.js:11004 l @ angular.js:16871 $digest @ angular.js:17982 $apply @ angular.js:18280 (anonymous) @ angular.js:13193

**Comment by bhollis** [comment] 2017-03-26 02:07
Things load fine for me. How can I reproduce this?

I was seeing errors a bunch last night, but it appeared to be a Bungie.net problem, and it didn't prevent me from loading DIM.

**Comment by bhollis** [comment] 2017-03-26 02:18
#1557 may help

**Comment by bhollis** [comment] 2017-03-30 06:22
Closing since I don't know how to repro.

**Closed by bhollis** 2017-03-30 06:22 UTC
