### ISSUE TITLE
Ergo sum compare should be groupable by intrinsic perk

### ISSUE THREAD

**Issue by thomaskchan** [DestinyItemManager/DIM#10650] opened 2024-07-20 07:30 UTC
### Proposed change

When comparing all our Ergo Sums, it would be useful to to have a way to have the items with the same intrinsic perk grouped together.  I do see that if your initial choice was a particular intrinsic, then there is s way to show only swords with that intrinsic, but I do think it would be useful to see them grouped together if you are looking at all swords.

### How does this fit into your workflow?

I would do a compare when clicking on any Ergo Sum, and then be able to quickly see how many of each type of intrinsic perk I had, and also quickly compare each type of sword.

**Comment by bhollis** [comment] 2024-07-20 20:03
Yep that's the plan. In the meantime use the Organizer which has many more sorting and filtering options.

**Comment by bhollis** [comment] 2024-09-06 06:07
Duplicate of #10638

**Closed by bhollis** 2024-09-06 06:07 UTC
Labels: Enhancement, Feature: Compare
