### ISSUE TITLE
Loadout Optimiser: Typing minimum power does not work

### ISSUE THREAD

**Issue by joshhunt** [DestinyItemManager/DIM#5554] opened 2020-08-05 23:09 UTC
**What version of DIM are you using?**
beta, Version 6.23.0.7734 (beta), built on 05/08/2020, 06:32:06

**What Browser and OS are you using?**
Chrome, Windows

**Describe the bug and how to make it happen**
In the loadout optimiser, if you use the text box to type in a power level, you get "no loadouts found". If you drag the slider to the same power value, you get loadouts.

https://gyazo.com/9c43ae75d96628ddf6cd0f7d12141bce

**Include devtools console logs**
 nothing interesting 
![image](https://user-images.githubusercontent.com/46142/89472778-17e32c00-d779-11ea-9108-aea1127253d5.png)

**Comment by ryan-rushton** [comment] 2020-08-06 00:16
Dupe of #5066

**Closed** 2020-08-07 05:00 UTC
Labels: Bug
