### ISSUE TITLE
Update Loadouts When Items are Removed

### ISSUE THREAD

**Issue by Wh1rledPeas** [DestinyItemManager/DIM#3589] opened 2019-02-02 21:07 UTC
When DIM updates its internal data from Bungie, I'm assuming it evaluates what has been added/removed, since we can see visual effects on new items.

As it's doing this, could you also identify items that have been removed, check to see if they are in Loadouts, and replace them with any duplicate item found? 

Every time I get a drop, I'm comparing it to the one I have. I keep the one with the perks I like the best and either infuse to maintain power level or discard. This results in out of date items in loadouts, in a very short amount of time.

**Comment by bhollis** [comment] 2019-02-02 21:34
Duplicate of https://github.com/DestinyItemManager/DIM/issues/2729

**Closed by bhollis** 2019-02-02 21:34 UTC
