### ISSUE TITLE
Add "Add roll to wish list" option to "gun perk options screen"

### ISSUE THREAD

**Issue by johyphenel** [DestinyItemManager/DIM#9445] opened 2023-05-06 19:13 UTC
### Proposed change

I'm not sure the proper name for the screen where you see all the perk options that can roll for a gun, but that's the screen I mean with "gun perk options screen". 

From that screen, today to can select a set of perks and see how they would affect the gun stats, you can also select "copy selected perks as wish list roll".

I wish there was an option to simply "Add selected perks to wish list" to simplify the workflow of adding new combos to my personal wishlist. 

### How does this fit into your workflow?

The current process to curate your own wishlist is tedious, having to keep your own text file and reupload it every time you make changes. It would be nice if DIM had a personal wishlist for you saved on the server, and you could add new rolls to the list right from the UI.

**Comment by robojumper** [comment] 2023-05-06 19:19
> proper name for the screen where you see all the perk options that can roll for a gun

We call it Armory but the name doesn't show a lot in DIM. Yes, we do want this, but this is a dupe of #8629, so closing in favor of that.

**Closed by robojumper** 2023-05-06 19:19 UTC
Labels: Enhancement, Feature: Wish List, Feature: Armory
