### ISSUE TITLE
Progress: Bright Dust

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8946] opened 2023-01-08 01:33 UTC
### Proposed change

We have sections for power level progress, showing what you can still do to gain more power level. However, brust dust may also be a goal for you (as is with me), so have a section dedicated to bright dust would be very helpful to organize what's left to do to gain bright dust, i.e. the weekly challenges + event bounties + extra vendor bounties (may be omitted). 

### How does this fit into your workflow?

One of my end goals is to gather bright dust and keeping track of what's left to do for all characters can be confusing at times, so having a tracker on DIM would be nice.

**Comment by bhollis** [comment] 2023-01-09 04:43
This is generally a duplicate of https://github.com/DestinyItemManager/DIM/issues/7103

**Closed** 2023-01-09 04:43 UTC
Labels: Enhancement, Feature: Progress
