### ISSUE TITLE
Include vendor armor in Loadout Optimizer

### ISSUE THREAD

**Issue by Stregone1** [DestinyItemManager/DIM#9576] opened 2023-06-16 21:37 UTC
### Proposed change

Probably not too useful for really established players, but newer or more casual players could probably benefit from the Loadout Optimizer also searching through the inventories of the various vendors, including Xur for potential armor pieces to include in the loadout.

### How does this fit into your workflow?

At reset or when Xur arrives, I could check my loadouts in the Optimizer to see if any vendors have upgrades for me.

**Comment by bhollis** [comment] 2023-06-16 21:45
Duplicate of #6878

**Closed** 2023-06-16 21:45 UTC
Labels: Enhancement
