### ISSUE TITLE
Deepsight borders appear on unlocked weapons

### ISSUE THREAD

**Issue by UndarkAido** [DestinyItemManager/DIM#9171] opened 2023-03-03 06:21 UTC
### DIM Version

Version 7.58.1.1002336 (beta), built on 3/2/2023, 3:34:10 PM

### Browser Details

Firefox, 110.0 (64-bit), PWAsForFirefox 2.4.1 

### OS Details

Windows 11 (DIM says Windows 10)

### Describe the bug

Deepsight borders appear on weapons with unlocked crafting patterns meaning you can never remove them

![image](https://user-images.githubusercontent.com/7421794/222645506-dca3376c-feab-40da-8ca8-9e7f64ec4c4a.png)
![20230303001525_1](https://user-images.githubusercontent.com/7421794/222645639-40350035-2d4c-402f-8079-a88d0f758196.jpg)

### Logs

[console-export-2023-3-3_0-19-0.txt](https://github.com/DestinyItemManager/DIM/files/10878777/console-export-2023-3-3_0-19-0.txt)

**Comment by bhollis** [comment] 2023-03-03 06:42
Interesting. Could you go to the bottom of the Settings page and click "Export API profile response" and attach it here?
<img width="510" alt="image" src="https://user-images.githubusercontent.com/313208/222649855-0727cda2-5642-4b8c-8d81-28f0a6f89a9d.png">

**Comment by fishfacemcgee** [comment] 2023-03-03 23:03
@bhollis I'm running into this too, but I'm not actually seeing a way to export an api profile response on the settings page? Is that only available on DIM Beta or something?

**Comment by delphiactual** [comment] 2023-03-03 23:04
yes, but addressed in #9176

**Comment by fishfacemcgee** [comment] 2023-03-03 23:08
If that fix is already live in Beta, then I can confirm it works. If it's not, then something else is going on, because standard DIM has the red border and Beta does not.

**Comment by delphiactual** [comment] 2023-03-03 23:10
that fix is not yet merged

**Comment by fishfacemcgee** [comment] 2023-03-03 23:13
![image](https://user-images.githubusercontent.com/1767723/222852514-b624b286-b073-4bbe-8daf-ae8badfcdaf7.png)

Then something else is going on. In an additional wrinkle, Beta is showing the resonance when inspecting the item, but no border. Meanwhile Stable is showing the red border but no resonance.

**Comment by delphiactual** [comment] 2023-03-03 23:14
please send a copy of your profile response from beta

**Comment by fishfacemcgee** [comment] 2023-03-03 23:20
[fishfacemcgee-profile-data.zip](https://github.com/DestinyItemManager/DIM/files/10886877/fishfacemcgee-profile-data.zip)

**Comment by UndarkAido** [comment] 2023-03-04 08:10
Here's mine: [profile-data.json.txt](https://github.com/DestinyItemManager/DIM/files/10887811/profile-data.json.txt)

**Closed** 2023-03-07 00:52 UTC
Labels: Bug
