### ISSUE TITLE
Display selected ornaments and shaders for gear in Destiny loadouts

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9357] opened 2023-04-03 17:33 UTC
### Proposed change

Currently, DIM does not display selected fashion for Destiny loadouts. I would like to see it as it is displayed in DIM loadouts.

### How does this fit into your workflow?

Destiny loadouts memorizes selected fashion for gear. And it is not possible to view anywhere. For me this is especially annoying for weapons. I can replace weapon ornament/shader for a new one, but once I apply Destiny loadout, fashion change reverted. The same is true for armor too.

Ability to view selected ornaments and shaders will help to identify which Destiny loadouts must be updated.

**Comment by bhollis** [comment] 2023-04-05 05:17
Duplicate of #9103, fixed in #9312

**Closed** 2023-04-08 20:00 UTC
Labels: Enhancement, Feature: Loadouts

**Comment by Prometheus3375** [comment] 2023-04-17 22:25
I forgot one thing. In-game loadouts also memorize selected kill tracker for weapons. Can be useful to view this info in DIM too.

Btw, why DIM cannot change kill trackers?

**Comment by delphiactual** [comment] 2023-04-21 21:58
bc the api does not allow it
