### ISSUE TITLE
Items missing from the collections

### ISSUE THREAD

**Issue by tsaxkid** [DestinyItemManager/DIM#3776] opened 2019-04-23 22:13 UTC
My collections tab on the DIM beta is missing a number of items (ex. no hunter exotics are even shown, even though I own them all; also, there are only 8 exotic weapons according to the app, because the rest are missing. I believe there are other items missing too, but the exotic category stands out the most

![DIM collections bug](https://user-images.githubusercontent.com/49925559/56619365-ee85a780-65ea-11e9-90f1-6e00910780d4.png)

**Comment by bhollis** [comment] 2019-04-24 05:05
Duplicate of #3766

**Closed by bhollis** 2019-04-24 05:05 UTC
