### ISSUE TITLE
"Apply Mod" to weapon silently fails/no-ops

### ISSUE THREAD

**Issue by nev-r** [DestinyItemManager/DIM#7683] opened 2022-01-08 09:45 UTC
![image](https://user-images.githubusercontent.com/68782081/148639697-a3c544c7-14d1-4031-9f0f-c2fbc976a1ee.png)

**Comment by bhollis** [comment] 2022-01-08 22:40
Duplicate of #7564

**Comment by nev-r** [comment] 2022-01-08 22:42
i'm not sure it is? cursory inspection made it seem like it doesn't even try an api request, which makes this very different from that lack of error reporting

**Comment by bhollis** [comment] 2022-01-08 22:53
Cool - I'll address them both together

**Comment by nev-r** [comment] 2022-01-08 22:58
in this one's case, preferably it wouldn't be offered unless AWA is available

**Comment by bhollis** [comment] 2022-01-08 23:20
Ah, I see the confusion. This is related to https://github.com/DestinyItemManager/DIM/issues/7377, and it's kind of a holdover from before we could insert plugs. Right now, if we can't insert right away, we just slot it as a socket override so you can preview the stats. You can see that the mod is displayed in the socket and status update.

We could either switch all mods to this behavior (and you have to hit "apply mods/perks" after making all your selections), or switch the label to "Preview mod"

**Closed** 2022-01-09 15:41 UTC
Labels: Bug, Feature: Item Details Popup, Feature: Sockets
