### ISSUE TITLE
Editing a loadout requires save to be clicked twice

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#4701] opened 2019-11-12 00:42 UTC
Current beta on Chrome on Windows 10.

Pick any loadout and edit it.
Make changes.
Click save, then click away.

Nothing happens.  Nothing is saved.

Pick any loadout and edit it.
Make changes.
Click save.  Then click save again.

Loadout editor goes away and changes are saved.

**Comment by bhollis** [comment] 2019-12-30 05:32
I'm unable to reproduce this. Is there some specific edits that you need to do?

One thing that might be confusing is that the dialog doesn't go away until the save is completed - which may involve calling Google Drive. So there can be some delay between hitting save and the dialog closing. I'll be fixing that as part of the work on the new API.

**Comment by philkernick** [comment] 2019-12-30 06:16
I didn't know about the delay.  I've just tested it, and it takes a full 2 seconds between clicking the save box and the dialog going away.  That's probably it.  If we can async the save action, it will solve it.

**Comment by bhollis** [comment] 2019-12-30 06:30
It's async already, but the close action doesn't fire until it's complete. Probably better to just assume it worked and close immediately.

**Comment by philkernick** [comment] 2019-12-30 08:18
Agreed.

**Comment by bhollis** [comment] 2020-01-04 08:47
Ugh, looking at the code I realize that this was originally set up to optimistically closed, but at some point someone added the feature to identify loadouts with duplicate names and warn about them (preventing the loadout drawer from closing). I'll have to do a bunch more work to rearrange this to be able to still do that without having to wait.

**Closed** 2020-02-17 04:25 UTC
Labels: Bug, Feature: Loadouts
