### ISSUE TITLE
Add Folders to Character DropDown Menu

### ISSUE THREAD

**Issue by Zurnic** [DestinyItemManager/DIM#8694] opened 2022-09-07 17:57 UTC
### Proposed change

I know I'm not the only one who has more loadouts than they'd care to admit. It would be useful to have the ability to create folders so that I could group certain loadouts together ie all the arc loadouts, all the builds from a certain creator, etc.

### How does this fit into your workflow?

I currently have to scroll for a long time to find the specific loadout I'm looking for or use the search feature which can take a while.

**Comment by bhollis** [comment] 2022-09-07 21:40
Duplicate of #7663

**Closed by bhollis** 2022-09-07 21:40 UTC
Labels: Enhancement
