### ISSUE TITLE
Add Required Character Level to VIEWABLE Item stat popup

### ISSUE THREAD

**Issue by mcdonamw** [DestinyItemManager/DIM#3128] opened 2018-09-24 21:08 UTC
While leveling Alts and drowning in blue level items, it would be useful to see the item's required character level.  We can filter by the level but the items don't seem to show this information anywhere in their stat screen popup

**Comment by bhollis** [comment] 2018-09-25 06:14
Duplicate of #2493

**Closed by bhollis** 2018-09-25 06:14 UTC
