### ISSUE TITLE
Planet warlock armor not marked as reaquireable 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5558] opened 2020-08-07 12:19 UTC
**What version of DIM are you using?**
6.23.0 Orange

**What Browser and OS are you using?**
Chrome Android 

**Describe the bug and how to make it happen**
Using filter for reaquireable gear the Io warlock armor is greyed out but I can buy it from my collection with same max power as the one I got from giving Asher Io tokens. 
Same for armor from Titan tokens.

**Comment by bhollis** [comment] 2020-08-07 20:52
Likely dupe of https://github.com/DestinyItemManager/DIM/issues/5116

**Closed by bhollis** 2020-08-07 20:52 UTC
Labels: Bug
