### ISSUE TITLE
Moving inventory items (materials, etc) fails to work

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#9340] opened 2023-04-01 21:40 UTC
### DIM Version

Version 7.62.0.1002461 (beta), built on 4/1/2023, 12:10:51 PM

### Browser Details

Chrome 111.0.0.0 - Linux x86_64

### OS Details

openSUSE Tumbleweed 20230326

### Describe the bug

This is similar to #7602 - the query is:

`is:movable -is:armor -is:weapon -is:ships -is:vehicle -is:ghost -name:"sweaty confetti" -name:"paraversal haul" -is:transmat -name:projection -name:rainmaker -name:"herealways piece" -name:"phantasmal fragment"`

If I allow ghosts to be moved (for example), that part works, but the items in the "Inventory" classification of items (materials etc) don't move.

The item selection shows correctly, but no errors are logged in the browser console (output shown in the logs section)

Let me know what other information would be useful.

### Logs

```shell
[loadout] Apply loadout Filtered Items to Vault
log.ts:58 Loadout Application: 13.482177734375 ms
```

**Comment by bhollis** [comment] 2023-04-01 23:22
Probably similar to / duplicate of #8506?

**Comment by hendersj** [comment] 2023-04-02 00:05
Similar at least, forgot I opened that one previously (searched and didn't find it).

**Closed** 2023-04-05 06:42 UTC
Labels: Bug, Feature: Item Movement
