### ISSUE TITLE
Weird niche exotic equip fail

### ISSUE THREAD

**Issue by Gix3612** [DestinyItemManager/DIM#9120] opened 2023-02-26 19:19 UTC
### DIM Version

Version 7.57.0.1002302 (beta), built on 2/26/2023, 1:27:50 PM

### Browser Details

Chrome

### OS Details

Windows 10

### Describe the bug

When equipping an exotic (armor or weapon) directly from the vault, DIM transfers it to inventory but returns the Bungie "can only have one item of this type equipped" message without attempting to replace other exotics you already had equipped in other slots. When the exotic is already on a character (current or another) it will swap your other exotic with a legendary before equipping it as expected. Locations of the legendary item being equipped has no effect on results.

**Comment by bhollis** [comment] 2023-02-26 20:41
Duplicate of #9121

I couldn't reproduce this myself (it always worked) but my vault is too full to empty out a bucket.

**Closed by bhollis** 2023-02-26 20:41 UTC
Labels: Bug
