### ISSUE TITLE
On a touch device, cannot see what a perk actually is

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#1983] opened 2017-07-15 03:54 UTC
I have an android device and I can't see what a perk actually is once I touch on the item to see all the perks.  All the icons for the perks show up, but sometimes perks like rifled barrel or reinforced barrel have the same icons and you can't really tell what the perk is.  Would be good if there was  a way to see text descriptions of the perk on a touch device.

**Comment by bhollis** [comment] 2017-07-15 04:16
Duplicate of #575.

We're going to get to this very soon!

**Closed by bhollis** 2017-07-15 04:16 UTC
