### ISSUE TITLE
Vault weapon-type spacer similar to class spacer for armor

### ISSUE THREAD

**Issue by SahandJ** [DestinyItemManager/DIM#6560] opened 2021-03-04 13:15 UTC
**Proposed change**
This proposed change is similar to #3613, however instead of marking it as proposed in #3613 with striped lines I would use the various weapon type / category icons (as found in "Organizer"). For instance, Auto Rifles would be preceded with the AR-icon:
![image](https://user-images.githubusercontent.com/5606617/109968947-9b570280-7cf3-11eb-9ced-58d7dfd16105.png)

If possible I would love an option to have each category on a new line. 

**How does this fit into your workflow?**
It would make it much easier to find specific weapons with a quick glance, narrowing down to the specific type much faster instead of having to recognise the weapon models. I believe this would be a nice QoL change.

**Comment by bhollis** [comment] 2021-03-04 20:30
I'm going to file this as a duplicate of #3613 - using weapon icons was one of the options we explored and rejected for being too noisy.

**Closed by bhollis** 2021-03-04 20:30 UTC
Labels: Enhancement

**Comment by SahandJ** [comment] 2021-03-04 22:40
I think having each weapon on a new line would circumvent the noisiness. Currently, it's just a mess looking at all weapons, I think there definitely should be a separator in a way.

**Comment by bhollis** [comment] 2021-03-05 00:33
We've prototyped that and it makes the view too tall
