### ISSUE TITLE
Equip weapon ornaments and shaders in loadouts

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#9038] opened 2023-01-29 01:02 UTC
### Proposed change

Currently, loadouts allow you to set "fashion" for your armor, but not for weapons when setting up loadouts.

### How does this fit into your workflow?

I've got a few different loadouts that I'd like to swap oranments/shaders for on my weapons so they match what I have on my armor - would make it so I don't have to manually make those changes.

**Comment by bhollis** [comment] 2023-01-29 01:36
Duplicate of #8260

**Closed by bhollis** 2023-01-29 01:36 UTC
Labels: Enhancement
