### ISSUE TITLE
Tag incoming items based on filters

### ISSUE THREAD

**Issue by thelovedolphin** [DestinyItemManager/DIM#8684] opened 2022-09-01 07:52 UTC
### Proposed change

Would love the ability to tag new/incoming items as junk or archive (or a new tag perhaps) based on filters of what I'm looking for. 

### How does this fit into your workflow?

I could add filters like is:deepsight, is:craftable, pattern not yet unlocked, and incoming items that fit that criteria could be tagged for me automatically. Would also be helpful for junk items. Filters for -is:exotic, basestat:total<60, -is:deepsight could automatically tag incoming items as junk. Vault cleaning would be immensely shortened, especially if filters could be saved and toggled

**Comment by robojumper** [comment] 2022-09-01 07:59
Duplicate of #7219.

**Closed by robojumper** 2022-09-01 07:59 UTC
Labels: Enhancement
