### ISSUE TITLE
Cannot Transfer A Crux of Crota To The Vault If there is Already A Crux There.

### ISSUE THREAD

**Issue by brandonkboswell** [DestinyItemManager/DIM#79] opened 2015-05-02 06:33 UTC

**Comment by SunburnedGoose** [comment] 2015-05-03 05:51
Are you supposed to be able to transfer a crux?

**Comment by brandonkboswell** [comment] 2015-05-04 13:15
I can Transfer Crux's Normally, just not when I already have one in my Vault

**Comment by brandonkboswell** [comment] 2015-05-04 13:17
Not sure about the stackable, will double check when I have access to Destiny

**Comment by SunburnedGoose** [comment] 2015-05-04 14:16
I'm not clear on the problem then.  Can you describe the what should be happening, and what the problem is with the app?

**Comment by geck0s** [comment] 2015-05-07 11:08
I reproduced this in v3.0.0 beta 4.  I moved one crux to the vault which now reads 20/24 general items.  Moving a second crux to the vault shows a red warning "Crux of Crota
There are no item slots available to transfer this item."

DIM V2.11.7 says "Error

Error #1642
There are no item slots available to transfer this item.

You may need to refresh the tool. Eventual support for this event."

The same behavior occurs when trying to move the vaulted crux onto the hunter which already has a crux.

I think this traces back to an API thing as the Bungie app also tells me "There are no slots available to transfer this item." and does not move the crux.

In the game, at the tower with my hunter holding a crux, hovering over the crux in the vault shows a red banner "Not Enough Space" and there is no "press A to Take" listed.  Same with the crux in my hunter's inventory, it cannot be transferred into the vault until the other one is moved onto another character.  They appear to be even less than unstackable as there is no way I can see to get them in the same place even as separate stacks.  Are there other unstackable items I can test with to compare and contrast this behavior?  

I earned them on separate characters and never attempted to bring them together before today.  Perhaps this is so that you can't have a stack of two or more cruxes be consumed in creating one necrochasm.  I'm hesitant to try simultaneous moves in game and in an app as it's unlikely to work and could only cause problems.

Finally I've got a legitimate reason to not make a Nechrochasm :)

**Comment by SunburnedGoose** [comment] 2015-05-07 12:56
That's what I was expecting. Thanks for verifying. I'll add some logic to
the crux then to avoid transfers g it it it already exists.

**Comment by geck0s** [comment] 2015-06-08 12:17
By the way, Royal Amethyst are not stackable either.  There are two different Royal Amethyst items, one worth 2500 glimmer and another worth 5000.  You can have at most one of each type in the vault or on a character at one time.  If  you run PoE enough, you should eventually get some more from the small chests at the end and can observer this behavior for yourself once you get two at the same time.  It's the same behavior I described above with the crux of crota.

**Comment by geck0s** [comment] 2015-06-20 17:48
I noticed similar behavior with some legendary ships like "Bane of the Dark Gods".  In DIM they produce a different error though.  I deleted my duplicates before I got a copy of the message though.  

It's not all legendary ships as there was no problem moving two "Hildian Seeker" ships from Skolas to one character at the same time.  This may be part of some mechanism to keep you from getting the same thing every week but that may have been changed around from one DLC to the next.

**Comment by kyleshay** [comment] 2015-10-29 06:10
Is this sort of thing still happening ?

**Comment by SunburnedGoose** [comment] 2015-10-29 06:14
Yes.  This happens with Shaders too.  You can only have one of them in a store at a time.  Dunno if there is a flag for it.

**Comment by geck0s** [comment] 2015-10-30 01:48
Yes, just now I tested and got "Crux of Crota
There are no item slots available to transfer this item."

I would assume Royal Amethyst are still being treated the same way but I don't have any to test with right now.

With the addition of kiosks, this sort of thing now occurs with many more items which will state "Can only hold one at a time" in a red banner when you hover over one in the vault, at a kiosk or from a vendor when you already have on your character or in your inventory.  

Just now I tried to use DIM to move a duplicate sparrow and it said "Sparrow S-31V
You can only have one of the thing you're trying to do/activate/equip. Man, this error is way too general. Listen, whatever you did... you can only do it once, or have one item, okay? Whatever."

The new problems apply to ships, sparrows, shaders, emblems, and emotes.  Nothing in those slots ever stacked but now you can't have more than one on a character or in the vault.  When the Destiny 2.0 patch hit, all my duplicate sparrows were removed including some that were equipped leaving me with a default sparrow until I selected a raid one again.  

Somehow DIM is differentiating between a fully charged antiquated rune and one that is not charged or only partially charged.  The fully charged one is locked to a character in the game and DIM doesn't display any move options or allow drag and drop.  Does the API provide some info distinguishing the charged runes and could it do the same for other items?

**Comment by SunburnedGoose** [comment] 2015-10-30 02:10
Yes, there is a no transfer property.

**Comment by geck0s** [comment] 2015-10-30 03:21
Ok, if the no transfer property works the way I would expect then it wouldn't be helpful for this issue.

I guess we need some way of identifying items on this list:
Crux of crota
Royal Amethyst valued at 2.5k glimmer
Royal Amethyst valued at 5k glimmer
any sparrow
any ship
any shader
any emblem
any emote

It'd be nice to get this info by checking item properties if possible so it would be more likely to work with future changes, but it could also be based mainly on item slot with hardcoded additions for the first three items.

If the item is on that list we need to check that there is not an identical item in the potential destination (or along the path from one character to another through the vault) before enabling the move and equip buttons. 

Or if we want to get fancy, we could support transferring from one character to another when the vault has a duplicate by transferring the vault item to the destination character and then move the item from the source character to the vault.  All of these items are indistinguishable anyway.

How should the UI indicate that the crux of crota you drug out of the vault cannot be dropped on the hunter that already has one but can be dropped on the warlock who does not?

**Comment by kyleshay** [comment] 2016-05-04 14:35
This is a bungie issue, correct? We display this message (from bungie) if a user tries to do it:

![screen shot 2016-05-04 at 10 33 04 am](https://cloud.githubusercontent.com/assets/424158/15017454/acce3eaa-11e3-11e6-9071-bb5cd6657bf1.png)

Is that enough to call this PR good? Worst case is you get that error, and maybe your item ends up in your vault? I like that option more than hiding the move/equip buttons for just my hunter if he already has the point emote... users might be confused why they can move it to their titan but not their hunter? better to show the error?

dunno.

does that make sense?

**Comment by SunburnedGoose** [comment] 2016-05-04 14:37
Shaders and Crux suffer this the most.  If the hash is in the target or vault, then you shouldn't have the ability to move the item.  Users will wonder why they don't have the button though...

**Comment by bhollis** [comment] 2016-05-04 15:22
Yeah, it's a Bungie issue, and I don't know how to detect what items have
this restriction...

**Comment by kyleshay** [comment] 2016-05-04 16:06
I guess we have two options:

when we're creating the item, if the item is in this list give it a flag:
 * Crux of crota
 * Royal Amethyst valued at 2.5k glimmer
 * Royal Amethyst valued at 5k glimmer
 * any sparrow
 * any ship
 * any shader
 * any emblem
 * any emote
then loop over the flagged items and define a black list of move locations.
with that black list we could disable the dropzone/movebox items for specific characters.

Another option is to keep the error message, maybe instead capture it and give a better explanation.
> You tried to move the '`item.name`' `item.type` to your `desination.character`, but that character already has that `item.type` and is only allowed one.

example:

> You tried to move the 'Point' emote to your Human Hunter, but that character already has that emote and is only allowed one.

And if we capture that message, maybe we could move it back to the source? That way it's not ending up in the vault? Or maybe keep it in the vault? Sometimes (for crude example...) I'm trying to clear for engrams from the post master, and wildly just swiping items off to make room. If I set the target to a character that has that item hash and is only allowed one, I don't really care that the item ended in the vault, I just want the room. Some people might care though.

**Comment by bhollis** [comment] 2016-05-04 16:22
I like capturing/renaming the error better than a blacklist. You forgot
certain Ghosts also have this problem...

**Closed** 2016-06-04 05:46 UTC
