### ISSUE TITLE
UI layering bugged in certain situations

### ISSUE THREAD

**Issue by WindedHero** [DestinyItemManager/DIM#8393] opened 2022-05-22 04:04 UTC
If you tap a weapon, then tap its name to pull up the wishlist and dupes, then tap one of the dupes, then tap or hover over the masterwork for that dupe, the masterwork tooltip or window pops under the current layer instead of over it. This breaks the close buttons on mobile, essentially bricking the UI.

**Comment by inexorableAce** [comment] 2022-05-22 04:10
dupe of #7823

**Closed by inexorableAce** 2022-05-22 04:10 UTC
