### ISSUE TITLE
No Turning Back is not shown as curated

### ISSUE THREAD

**Issue by vfragosop** [DestinyItemManager/DIM#5458] opened 2020-07-15 21:00 UTC
The title is pretty self-explanatory.
Since this bow has a fixed roll, shouldn't it be considered a curated weapon?
https://www.light.gg/db/items/720351794/no-turning-back/

**Comment by bhollis** [comment] 2020-07-15 21:06
Duplicate of https://github.com/DestinyItemManager/DIM/issues/4011

**Closed by bhollis** 2020-07-15 21:06 UTC
Labels: Bug
