### ISSUE TITLE
[Enhancement] Enable backup from mobile to local (or remote) storage

### ISSUE THREAD

**Issue by CodyFitzpatrick** [DestinyItemManager/DIM#4538] opened 2019-10-21 04:01 UTC
I love using my iPad for DIM when playing D2. Unfortunately there seem to be sync problems (not sure if I’m supposed to force restore from GDrive before adding new notes) so wanted to back everything up in order to import my custom data into/onto my other devices.

Unfortunately, I was met with an error screen (see below) as I believe JS is triggering a file download that iOS (in my case) does not know how to handle.

I know a lot of work would have to go into this (and this is not the first recommendation I have made without actually contributing myself), but it’d be great to be able to upload this file to the synced Google Drive, iCloud Drive, Dropbox, etc.

 Perhaps just an additional file in the synced GDrive with a name derived from the device identifier and time stamp in a human visible format would suffice. 

Let me know your thoughts!

![C14BF4C8-D06D-427E-BCB5-15ED1DEA7B55](https://user-images.githubusercontent.com/5438023/67175904-daeaac00-f395-11e9-9636-a130ea4d0ff8.jpeg)

**Comment by bhollis** [comment] 2019-10-21 04:42
Dupe of #4412. We're not going to invest any more in the current storage/sync system, as we're replacing it: #4418.

**Closed by bhollis** 2019-10-21 04:42 UTC
Labels: Infrastructure: Sync

**Comment by CodyFitzpatrick** [comment] 2019-10-24 00:45
Sounds great; thanks for linking #4418 @bhollis!
