### ISSUE TITLE
New Search Bar: "Enter" no longer selects the first autocomplete option

### ISSUE THREAD

**Issue by Roland46Plays** [DestinyItemManager/DIM#5645] opened 2020-08-23 11:33 UTC
**What version of DIM are you using?**
Version 6.25.0.7947 (beta), built on 23/08/2020, 07:56:50

**What Browser and OS are you using?**
Windows 10, MS Edge

**Describe the bug and how to make it happen**
Start to type a filter command, in previous version the filter used to be selectable, this is no longer working and the text appears to be unformatted, it code behind it for section and presentation appears to be missing.

![DIM Issue](https://user-images.githubusercontent.com/70056362/90977361-c8ed1300-e53c-11ea-8297-385fca1eb291.JPG)
![Screenshot (1)](https://user-images.githubusercontent.com/70056362/90977363-cd193080-e53c-11ea-808f-386db0cf5dfa.png)

```

**Comment by Roland46Plays** [comment] 2020-08-23 19:05
Resend.

 

From: Roland Moore <rolandaemoore@googlemail.com> 
Sent: 23 August 2020 18:38
To: 'DestinyItemManager/DIM' <reply@reply.github.com>
Subject: RE: [DestinyItemManager/DIM] Filter selections are no longer working. (#5645)

 

Ben,

 

It is not working, hopefully the attached will show you what I am doing and the results I am getting.

 

Roland.

**Comment by bhollis** [comment] 2020-08-23 20:31
Attachments don't work over email. 

Also, rather than just sending screenshots and having me guess what your issue is, could you describe what you expected and how that's not working? The issue template has a good example of that.

**Comment by kyleshay** [comment] 2020-08-26 00:18
I think what they intend to say is: Previously, filters would automatically match a result, but now you can insert freeform filters.

In the beta, the first result shows `is:blue is:a`, which isn't as useful. Pressing "tab" works to select the right option and expand the result, but previously that wasn't required.

| prod | beta |
| --- | --- | 
| <img width="203" alt="Screen Shot 2020-08-25 at 5 14 19 PM" src="https://user-images.githubusercontent.com/424158/91240361-ae5e9980-e6f6-11ea-85fd-a077dabd18c7.png"> | <img width="298" alt="Screen Shot 2020-08-25 at 5 15 05 PM" src="https://user-images.githubusercontent.com/424158/91240370-b585a780-e6f6-11ea-99d3-20f34145e250.png"> |

**Comment by bhollis** [comment] 2020-08-26 02:04
The only difference between the two is that in the original both Tab and Enter selected the completion, while in the new one only Tab does.

**Comment by bhollis** [comment] 2020-08-26 05:16
Closing as by design

**Closed by bhollis** 2020-08-26 05:16 UTC
Labels: Bug, Feature: Search
