### ISSUE TITLE
Alert for new items

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#567] opened 2016-06-02 13:48 UTC
I got a PM on reddit about this:

> Hey There,
> Saw your post on the Infusion Calc thread regarding implementing it into DIM, so hoping I'm messaging the right guy. I use DIM all the time, thank you guys so much for making it and doing an absolutely outstanding job!
> As I've been working on the whole T12 nonsense I am constantly refreshing DIM to find whatever new piece dropped before I forget about it and see if it's a better replacement for whatever I had before (I'm not going for a whatever T12 build, I'd rather have the right perks, so not just keeping high percentage roll stuff). Something that dawned on me that would make life a ton easier, is if for 24 or 48 hours after receiving any new piece there was a small "new" symbol on it or something in Dim so that you could just check at the end of the day, see what dropped and decide from there.
> I'm not sure if this is even possible whatsoever, but dawned on me with the T12 grind so just thought I'd throw it out there in case there was a way.
> Thanks again for all you guys do!

What I like about this is tracking items over time and alerting the user to useful items.

**Comment by ericnelson0** [comment] 2016-06-10 22:57
I tried to duplicate the in-game overlay in a local branch. Looks something like this:

![example_new](https://cloud.githubusercontent.com/assets/4594931/15980848/3a408d84-2f34-11e6-8610-da7b4de8b32d.gif)

It works by using chrome's local storage to store the id's of items that weren't in the old items loaded. The new items are only shown until they are clicked then they are dropped from the local storage. 

New items are only shown per "session" i.e. on complete reload all items will no longer be new.

I'm looking to get some feedback about the overlay and the description of how it works.

Should the new items persist until they are clicked even if the extension is closed?

**Comment by kyleshay** [comment] 2016-06-11 14:13
oh wow! that looks really great @ericnelson0. I wonder how log we should persist the new state for. I'm partial to the item being new until you click it (even between reloads.)

When you say complete reload, does that mean hard page refresh, or hitting the refresh icon/auto refresh?

another handy thing might be to add a `is:new` filter for the search box.

**Comment by ericnelson0** [comment] 2016-06-11 14:54
I meant a hard page refresh new items will stay "new" if the refresh icon is click or when returning from the loadout builder.

That's a great idea for the filter

**Comment by kyleshay** [comment] 2016-06-11 16:02
Ah, yes. Then that sounds good. Having to manually click every item just to unmark it as new would be tedious. Hard refresh ✅

**Comment by ericnelson0** [comment] 2016-06-11 17:53
It's done using SVG and svg animations!

**Comment by bhollis** [comment] 2016-06-11 22:30
Looks awesome! I wonder if we need a "mark all as read" button somewhere, though I don't know where it'd be.

**Comment by joshmedeski** [comment] 2016-06-13 15:23
Maybe we could add a notification as an optional setting that displays what the new item(s) is?

I would love this feature, then I can just glance at my computer while playing and see what that new item is without having to scroll or dig around.

p.s. I love the animation, great work!

**Comment by ericnelson0** [comment] 2016-06-14 06:12
So one problem with adding a notification for every new item is that new items are generated when the stores are reloaded, so you might get too many messages at one time.

**Comment by kyleshay** [comment] 2016-06-14 16:18
What if they were all in one toaster?

```
4 new items found. use the `is:new` filter or _click here_ to locate the items
```

**Comment by ericnelson0** [comment] 2016-06-14 17:14
@kyleshay That could work. I'll see if I can flesh something out to get some opinions.

**Comment by kyleshay** [comment] 2016-06-14 17:16
FYI there is a [`dimInfoService`](https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/services/dimInfoService.factory.js
) that helps with setting those up.


Example usage: 
```
      dimInfoService.show('movebox', {
        title: 'Did you know?',
        body: ['<p>Items can be dragged and dropped between different characters/vault columns.</p>',
               '<p>Try it out next time!<p>'].join(''),
        hide: 'Don\'t show this tip again'
      });
```

**Comment by ericnelson0** [comment] 2016-06-14 22:54
What about something like this:

![image](https://cloud.githubusercontent.com/assets/4594931/16062349/278e1126-3258-11e6-8455-3fa6656e7f6e.png)

Also, maybe I should just use toaster.pop. Otherwise, we'd get multiple copies as shown in the screencap.

**Comment by bhollis** [comment] 2016-06-15 03:49
Personally, I'd prefer not to have a notification. The "shine" is plenty.

**Comment by ericnelson0** [comment] 2016-06-15 15:26
I tend to agree with @bhollis, the shine with the filter is enough for me. However, if there is a setting to turn this off then I don't see it being that big of a deal to have a toast message appear.

**Comment by kyleshay** [comment] 2016-06-15 16:00
Maybe just update the 'hide this popup' copy to instead say "Don't show me this new item list again"

**Comment by ericnelson0** [comment] 2016-06-16 05:16
How about this?

![image](https://cloud.githubusercontent.com/assets/4594931/16106146/8caf6f50-3357-11e6-9808-34000c710397.png)

**Comment by bhollis** [comment] 2016-06-16 06:51
Do people really want that at all, though? Every feature is code that needs to be maintained.

The info service also doesn't have any way of turning back on disabled notifications. So the first time somebody gets annoyed with this, it's gone forever, so I imagine the trend will be towards it never being shown except for new users.

**Comment by bhollis** [comment] 2016-06-16 06:52
Plus it's not like I can click on those notifications to do anything cool, or hover over them to see the details of the item. It doesn't even say what light the item is. IMO totally useless and distracting, while the shines are elegant and fancy.

**Comment by ericnelson0** [comment] 2016-06-16 07:24
Just to play the devil's advocate, it is somewhat annoying to have to look through all your items and try to find the "shiny" ones and, if necessary, an option can be added in the settings so that it can be re-enabled.

What if clicking on the items in the popup scrolled them into view? Would you find that more useful?

**Comment by delphiactual** [comment] 2016-06-16 08:31
What if you moved them to the end of the queue in their respective buckets (i.e. all new items are shiny and the last things in each bucket)

**Comment by ericnelson0** [comment] 2016-06-16 15:01
It'd definitely make them easier to find. However, the is:new filter already does that. I guess the problem is having to scroll the full page to find every new item after the filter is applied. As @joshmedeski said you might just want to glance over and see what items are new without having to do much more than that.

**Comment by kyleshay** [comment] 2016-06-16 19:00
@SunburnedGoose any thoughts on the popup? other than that i'd say the PR is about ready to go!

**Comment by delphiactual** [comment] 2016-06-16 19:31
You could always add a button that shows all the new gear in a separate modal...

**Comment by kyleshay** [comment] 2016-06-16 19:54
that could be a nice addition. modal could have the actual clickable items along w/ move popup dialog... etc. i'm fine pulling this in, and adding that in when we have capacity for it.

**Comment by ericnelson0** [comment] 2016-06-16 20:18
@kyleshay I have found a couple of bugs:

1. If an item is new and it is deleted it still is in the local storage
2. Items with an id of 0 are all considered new.

I was planning on looking at these tonight. If you want to wait until those are fixed to merge.

**Comment by ericnelson0** [comment] 2016-06-16 21:48
@kyleshay do the popups have the ability to time out? Part of the reason the notifications might get annoying is having to click the 'x' for each one of them.

**Comment by ericnelson0** [comment] 2016-06-17 20:51
Nevermind. Fixed both issues. I'm just going to ignore consumables and general items (id == '0') for now. Should be good to go.

**Comment by Mulchman** [comment] 2016-06-23 17:52
Saw this in action last night.  I liked the shimmer on actual items (weapons/gear) but I didn't like having the shimmer on engrams and having to click each engram to get it to go away.

**Comment by kyleshay** [comment] 2016-06-23 19:36
also to note -- in some weird cases i get the popup and all items are marked as new

**Closed** 2016-06-25 23:55 UTC
Labels: enhancement

**Comment by Mulchman** [comment] 2016-07-08 23:54
Haven't had a chance to report this earlier, but when moving an item that's shimmering it's move icon is larger (like 2 times) than the normal item icon.  I don't have an image or gif to show at this time.  Just play and get some shimmer-y items, then drag and drop them some place else; you should see the icon be way bigger on the drop target.

**Comment by ericnelson0** [comment] 2016-07-09 00:24
@Mulchman Thanks, just submitted a PR.
