### ISSUE TITLE
[Feature] Mod collation

### ISSUE THREAD

**Issue by JeffHowden** [DestinyItemManager/DIM#2295] opened 2017-10-03 02:52 UTC
I find myself constantly going through the menial task of moving all rare mods to the vault, looking for any group of rare mods in the vault that's a multiple of three, and moving those groups to my current character so I can convert them to legendary mods at the gunsmith. It'd be nice to have a single menu item on each character (where "farming mode" is) that'd do all these steps automatically for me. Even better would be the ability to automatically move rare mods to the vault and a menu item on the vault (where "create loadout" is) that'd move any groups of three in the vault to my current character (3 would move, 4 would move 3 leaving 1, 5 would move 3 leaving 2, 6 would move 6, etc.).

**Comment by bhollis** [comment] 2017-10-03 05:23
Duplicate of #2255.

**Closed by bhollis** 2017-10-03 05:23 UTC
