### ISSUE TITLE
Collect Postmaster Pulls Entire Vault

### ISSUE THREAD

**Issue by ConcernedD2Player** [DestinyItemManager/DIM#8897] opened 2022-12-27 03:02 UTC
### DIM Version

Version 7.49.0.1002128 (beta), built on 12/25/2022, 6:19:12 PM

### Browser Details

OperaGx  93.0.4585.78

### OS Details

Windows 10

### Describe the bug

When pressing the "Collect Postmaster" button, post master item are retrieved along with all vault items possible to fit into inventory. Pulling postmaster items individually works fine though tedious.

**Comment by bhollis** [comment] 2022-12-27 21:04
Likely duplicate of #8872, #7935, or #6895

**Closed** 2023-01-12 08:09 UTC
Labels: Bug, Feature: Item Movement
