### ISSUE TITLE
Additional tags

### ISSUE THREAD

**Issue by MrTact** [DestinyItemManager/DIM#6324] opened 2020-12-12 19:32 UTC
**Proposed change**
I would like suggest adding some additional labeling options:
* PvP: Keep, this weapon roll is best suited for PvP
* PvE: Keep, this weapon roll is best suited for PvE
* Quickplay: Keep, this weapon roll is best suited for PvP BUT its power limit precludes its use in power-applied activities (Iron Banner/Trials)

***Questions***
* Should these tags come up if you filter on "Keep" as they are basically a subset of that tag?
* Or perhaps they should replace "Keep"?
* Should "quickplay" tagged items be archived unless you explicitly filter for them?
* Maybe rather than just PvE/PvP, break it down by activity? (General PvE, Strikes, Raids, Gambit, Crucible)
  * The loadout feature may adequately cover this breakdown already

**How does this fit into your workflow?**
This would enable finer-grained filtering/organizing. Especially useful for at-a-glance equipping items for a specific activity.

**Comment by kyleshay** [comment] 2020-12-12 19:56
Thanks for the suggestion MrTact --

The preferred way to add your own custom tags is by using the notes functionality:

https://destinyitemmanager.fandom.com/wiki/Tags_and_Notes#Using_notes_as_tags

Here are some reasons we aren't planning on adding additional tags:

https://github.com/DestinyItemManager/DIM/wiki/Frequently-Requested-Features#add-more-tag-values

Thanks again!

duplicate of #5180

**Closed by kyleshay** 2020-12-12 19:56 UTC
Labels: Enhancement

**Comment by DHager** [comment] 2020-12-18 05:29
> We've chosen the tag values we support based on a workflow of organizing your gear and identifying what to keep and what to get rid of, not what each item is best at. 

Except the way people decide what to keep or get rid of is **based on whether it helps meet a particular need**. They compare it to what they already use *for the same purpose*.

 :shrug:  I continue to find this policy baffling.

**Comment by MrTact** [comment] 2020-12-18 16:02
> duplicate of #5180

Sorry, I did search for existing issues before I filed this, but apparently I failed!
