### ISSUE TITLE
"DIM can't store data" error message appearing when loading DIM in Firefox

### ISSUE THREAD

**Issue by wjlaboy** [DestinyItemManager/DIM#10779] opened 2024-11-03 02:24 UTC
### DIM Version

v8.44.0

### Browser Details

Firefox 132.0 

### OS Details

Windows 11

### Describe the bug

Whenever I load up DIM in Firefox, I am met with an error message in the top-right corner stating the following:

> DIM can't store data in your browser. This can be caused by browsing in private or incognito mode, or when you have low disk space, or a browser bug. Try restarting your computer! You won't be able to log in to or use DIM until you fix this.

When I use DIM in Microsoft Edge or Google Chrome, I do not have this issue.

### Logs

```shell
[manifest] Error saving manifest file DOMException: IDBObjectStore.put: The serialized value is too large (size=267506836 bytes, max=267386880 bytes).
    i idb-keyval.ts:95
    _withIDBStore idb-keyval.ts:52
    _withIDBStore idb-keyval.ts:45
    promise callback*_withIDBStore idb-keyval.ts:43
    i idb-keyval.ts:94
    s manifest-service-json.ts:260
    s manifest-service-json.ts:191
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    s manifest-service-json.ts:170
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:102
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:97
    r promises.ts:13
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    u d2-definitions.ts:162
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    i d2-stores.ts:288
    P trace.ts:67
    P handleCallbackErrors.ts:25
    P trace.ts:66
    P trace.ts:453
    P trace.ts:453
    withScope stackStrategy.ts:49
    u stackStrategy.ts:135
    l currentScopes.ts:59
console.ts:40:19
    mt console.ts:40
    a log.ts:47
    s manifest-service-json.ts:265
    s manifest-service-json.ts:191
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    s manifest-service-json.ts:170
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:102
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:97
    r promises.ts:13
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    u d2-definitions.ts:162
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    i d2-stores.ts:288
    P trace.ts:67
    P handleCallbackErrors.ts:25
    P trace.ts:66
    P trace.ts:453
    P trace.ts:453
    withScope stackStrategy.ts:49
    u stackStrategy.ts:135
    l currentScopes.ts:59
```

**Comment by bhollis** [comment] 2024-11-03 02:33
Duplicate of #10764

**Closed by bhollis** 2024-11-03 02:33 UTC
Labels: Bug
