### ISSUE TITLE
Armor mods sheet closes immediately after clicking a mod.

### ISSUE THREAD

**Issue by Anthropole** [DestinyItemManager/DIM#7579] opened 2021-12-28 16:15 UTC
### DIM Version

Version 6.97.1.1001086 (beta), built on 12/27/2021, 4:21:34 PM

### Browser Details

Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)

### OS Details

MacOS 12.2 beta 21D5025f

### Describe the bug

I clicked on a Titan helm, then clicked on the 2nd Armor Mod socket, then clicked on "Rocket Launcher Ammo Finder", and expected the "Armor Mods" sheet to stay open so I can click the "Insert Mod" button, but instead the "Armor Mods" sheet closes immediately.

**Comment by bhollis** [comment] 2021-12-28 16:34
Duplicate of #7578

**Closed by bhollis** 2021-12-28 16:34 UTC
Labels: Bug
