### ISSUE TITLE
Collect Postmaster is easily mis-clickable.

### ISSUE THREAD

**Issue by Kaleidoscoped** [DestinyItemManager/DIM#6480] opened 2021-02-03 20:18 UTC
**Proposed change**
Add a confirmation for this feature like "Are you sure you want to collect all Postmaster items?"  Or, give an option to hide this button or disable it.

**How does this fit into your workflow?**
The "Collect Postmaster" is in a place that causes it to be easily clicked on accident due to items shifting when being intentionally pulled out as single items.  Mis-clicking it jams everything into potentially already overcrowded inventory and vault spaces.

**Comment by bhollis** [comment] 2021-02-03 20:19
Duplicate of #6426

**Closed by bhollis** 2021-02-03 20:19 UTC
Labels: Enhancement
