### ISSUE TITLE
Search in pull-from sheet goes off screen on Android

### ISSUE THREAD

**Issue by kyleshay** [DestinyItemManager/DIM#5876] opened 2020-09-25 00:31 UTC
**What Browser and OS are you using?**
Android/Chromium 

**Describe the bug and how to make it happen**
Open "pull from" sheet and click search bar

![Screenshot_20200924-172948](https://user-images.githubusercontent.com/424158/94213491-c4917e00-fe8b-11ea-91d2-08ad2f410114.png)

**Comment by bhollis** [comment] 2020-09-25 00:57
Duplicate of #5730

**Closed by bhollis** 2020-09-25 00:57 UTC
Labels: Bug, Feature: Item Movement, Feature: Search

**Comment by kyleshay** [comment] 2020-09-25 01:00
thanks! wow, I even filed it haha
