### ISSUE TITLE
Solar class ability icons the wrong colour. 

### ISSUE THREAD

**Issue by chewie30** [DestinyItemManager/DIM#8627] opened 2022-08-09 02:10 UTC
### DIM Version

Version 7.29.1.1001924 (beta), built on 08/08/2022, 19:22:55

### Browser Details

Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit)

### OS Details

Windows 11

### Describe the bug

Solar subclass, class ability and movement ability icons should be solar colour but are stasis.
![image](https://user-images.githubusercontent.com/50272943/183548022-89161d9e-b619-45cd-abab-8b8c47d7f32f.png)

**Comment by robojumper** [comment] 2022-08-09 05:52
Duplicate of #8421.

**Closed by robojumper** 2022-08-09 05:52 UTC
Labels: Bug
