### ISSUE TITLE
Eidolon Ally tooltip is poorly styled

### ISSUE THREAD

**Issue by jbccollins** [DestinyItemManager/DIM#1467] opened 2017-02-10 01:26 UTC
I think this screenshot should be enough to explain the issue.
<img width="346" alt="screen shot 2017-02-09 at 8 24 55 pm" src="https://cloud.githubusercontent.com/assets/8915552/22810308/f2b04526-ef05-11e6-96ca-6a3b87d737a4.png">

**Comment by kyleshay** [comment] 2017-02-10 05:58
Thanks, looks like this is a duplicate of #1455

**Closed by kyleshay** 2017-02-10 05:58 UTC

**Comment by jbccollins** [comment] 2017-02-11 18:07
@kyleshay ok cool.
