### ISSUE TITLE
Loadout Builder Crashing Chrome

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#670] opened 2016-07-08 14:46 UTC
Any reports of the Loadout Builder crashing when selecting advanced options and changing from Fast to Full?
24m 23 minutes ago

Nope, but there is a first for everything.
 **Destiny Item Manager**
 Can you give us some context?
22m 21 minutes ago

 **Scott Costa**
 Not sure if this is what your asking for. But the builder gets to between 55 or 65% and gives the "Aw, Snap! Something went wrong while displaying this webpage" error. 

I'm also performing this switch from fast to full with a warlock character. 

Fast works perfectly fine.
10m 9 minutes ago

 **Destiny Item Manager**
 Let's see what we can come up with.

**Comment by Scottcosta** [comment] 2016-07-08 19:55
5 hours ago
Scott Costa

If it's any consolation I've replicated this issue on two different systems. One is Ubuntu 32 bit with chromium and the other is Windows 10 64 bit, where I installed chrome and dim for the first time - same thing 

Also thanks again for such a awesome application and such a quick reply earlier. Keep up the great work. 

I'll monitor the link you provided.

**Comment by ericnelson0** [comment] 2016-07-09 15:24
Could you try running an instance of chrome with debugging enabled and post the log when this error occurs? That'd be an emmense help. 

Just start chrome from cmd with <code>--enable-logging --v=1</code>

Heres a guide too:
http://superuser.com/a/1007777

**Comment by kyleshay** [comment] 2016-07-29 15:50
closing until we hear more

**Comment by SunburnedGoose** [comment] 2016-07-29 16:46
I have experienced this.  When I turn on the 'Full' option, I can't get past 65% w/o Chrome crashing hard.  It is not happening at the moment.

**Comment by SunburnedGoose** [comment] 2016-07-29 16:47
![screen shot 2016-07-29 at 11 47 06 am](https://cloud.githubusercontent.com/assets/984608/17256234/4a18a2e0-5582-11e6-9e35-fba16e54463f.png)
![screen shot 2016-07-29 at 11 46 55 am](https://cloud.githubusercontent.com/assets/984608/17256233/4a175426-5582-11e6-8d88-0937aa537690.png)
![screen shot 2016-07-29 at 11 46 08 am](https://cloud.githubusercontent.com/assets/984608/17256235/4a1a1422-5582-11e6-97ab-613793a30c46.png)

**Comment by SunburnedGoose** [comment] 2016-07-29 16:48
Welp, that happened.  94%.

**Comment by ericnelson0** [comment] 2016-07-29 16:55
Can you try this and reproduce?

> Could you try running an instance of chrome with debugging enabled and post the log when this error occurs? That'd be an immense help.
> 
> Just start chrome from cmd with --enable-logging --v=1
> 
> Heres a guide too:
> http://superuser.com/a/1007777

Must be a memory or starvation issue.

**Comment by kyleshay** [comment] 2016-07-29 16:57
ah, we could add an option (range slider) that lets people adjust that time out, with a tooltip next to that that says if DIM keep crashing, try increasing the timeout (full mode will take longer, but it won't crash)

https://github.com/DestinyItemManager/DIM/blob/dev/app/scripts/minmax/dimMinMax.controller.js#L266

we considered webworkers, but they are a bit expensive since we need to pass the data as a string (so we need to parse/stringify)

**Comment by SunburnedGoose** [comment] 2016-07-29 17:03
I will later.  Too man cool tabs open atm :/

**Comment by Scottcosta** [comment] 2016-08-01 21:21
Here is a copy of my log replicating the issue


[chrome_debug.zip](https://github.com/DestinyItemManager/DIM/files/394801/chrome_debug.zip)

**Comment by Scottcosta** [comment] 2016-08-10 15:31
Uploaded the debug log nine days ago and have not heard anything. Do you need anything additional from me?

**Comment by ericnelson0** [comment] 2016-08-11 02:23
@Scottcosta No, thanks for the log. I couldn't find anything that telling in there. What are the specs on your machine? How much memory do you have?

**Comment by kyleshay** [comment] 2016-08-11 14:33
@ericnelson0, what if we just added an option next to the full mode setting that increased the timeout between cycles.

something along the lines of: `full mode crashing? click this mode [ ] to run full mode at a slower speed`

`if (processedCount % 50000 === 0) `

to something like:

`if (processedCount % 5000 === 0) `

it will run SO much slower, but the chances of DIM crashing would be much lower.

**Comment by ericnelson0** [comment] 2016-08-11 18:55
If it truly is a starvation issue then I'd say that'd be the way to go. 

@SunburnedGoose what are the specs on your system that crashes?

**Comment by SunburnedGoose** [comment] 2016-08-11 19:00
2012 Mac Mini, Core i5, 8GB RAM.

**Comment by ericnelson0** [comment] 2016-08-11 19:10
If you go to <code>chrome://crashes</code> are there any reports in there?

**Comment by SunburnedGoose** [comment] 2016-08-11 19:11
I just turned it on.  I'll go generate a crash :)

**Comment by SunburnedGoose** [comment] 2016-08-11 19:19
Just generated one.

Chrome Version: 52.0.2743.116
Operating System: Mac OS X 10.11.6

**Comment by ericnelson0** [comment] 2016-08-11 19:32
This might be the same file as what @Scottcosta uploaded, but is there anything interesting from the crash in <code>C:\Users\{username}\AppData\Local\Google\CrashReports</code>?

**Comment by Scottcosta** [comment] 2016-08-12 02:56
I've replicated the issue on three systems 
Windows 10 Pro 64bit with a fresh install of Chrome 52.0.2743.116 m (64-bit) - never used Chrome on this system other than to try and replicate the issue. 
Intel I7 6700K 
64 Gigs of memory
1 TB SSD and 4 TB Sata

Also Replicated on a Ubuntu 14.04.5 LTS  
32 megs of memory
750 gig Sata

Also checked the CrashReports directory and there is nothing listed there. (Made sure that hidden files etc.. is turned off to view all files)

**Comment by ericnelson0** [comment] 2016-08-12 04:33
Hmm. 

Does it appear to be random? How often does it happen? Any discernible patterns for when it happens?

**Comment by Scottcosta** [comment] 2016-08-13 03:31
Nothing random about it at all - It only occurs with my Warlock class - Titan and Hunter are fine. 

Now I don't know if this helps any - But I've got a ton of items for the Warlock in the vault and sitting in the slots of other Classes. (Vault is practically at its storage limit) But as I've recently been cleaning up items with the IS:Dupe search, it is slowly getting further along in percentage than before. At least I'm making it to 97% before it aww snaps! Whereas before it was 65%

**Comment by ericnelson0** [comment] 2016-08-13 04:18
> Nothing random about it at all - It only occurs with my Warlock class - Titan and Hunter are fine.
> 
> Now I don't know if this helps any - But I've got a ton of items for the Warlock in the vault

That is some good info. Thanks. 

If you are able to work with the chrome dev tools could you try setting a breakpoint and changing line <code>333</code> in <code>dimMinMax.controller.js</code>

from 
<code>if (processedCount % 50000 === 0) { // do this so the page doesn't lock up</code>

to:
<code>if (processedCount % 5000 === 0) { // do this so the page doesn't lock up</code>

and see if you still get this issue. @SunburnedGoose can you give this a shot and see if you still can get the crash too?

**Comment by kyleshay** [comment] 2016-10-03 17:40
builder updated, could we reach out to them to see if it works in beta now?

**Closed by kyleshay** 2016-10-03 17:40 UTC
