### ISSUE TITLE
Cannot log into DIM anymore

### ISSUE THREAD

**Issue by tricksofthetrade** [DestinyItemManager/DIM#2469] opened 2017-12-12 05:38 UTC
DIM no longer prompts me to log in while using Firefox v57.0.2. Have tested with Chrome and Edge and both prompt me to login. 

This issue occurred after I logged out in order to try and figure out why weapons and armor wouldn't load after CoO update (presumably still not fixed).

The error in the red box is strange, as you can see in the bottom of the screen dump, I am connected to the internet.
![dimerror](https://user-images.githubusercontent.com/34468222/33869024-bbd3f476-df5a-11e7-97ba-5c8b93229515.JPG)

**Comment by duckmanBR** [comment] 2017-12-12 13:39
Try on incognito mode.  If it works is probably a bad timing on an extension update that blocked bungie or DIM scripts.

Weapons and Armor not loading was fixed on the same day CoO launched (although some filters and infuse finder is still broken and the devs are working on it)

**Comment by tricksofthetrade** [comment] 2017-12-12 22:13
Okay, so I opened up in incognito mode, and when I clicked the launch app link, this time it did prompt me to authorize bnet to login. However, it didn't successfully get through.

Most likely an addon that I am running. I'll scrape through my addons and test to see which one is breaking it.

![dim secondary error](https://user-images.githubusercontent.com/34468222/33911239-d7677060-dfe5-11e7-899a-c154e55f4959.JPG)

**Comment by xari228** [comment] 2017-12-13 12:44
I'm having ths same problem. DIM worked fine for me up through last week (Dec. 4, I think), but when I tried to use it yesterday and today, I keep getting an error message. 

My Bungie account shows that DIM has been granted permission, but DIM itself won't load for me and gives an error message about not finding my account.  :-/

**Comment by bhollis** [comment] 2017-12-26 22:52
Are you all still having this issue?

**Comment by tricksofthetrade** [comment] 2017-12-27 02:31
Yes. Just tried it again then with Firefox. Still the same issue as shown in the screenshot of my first post.

**Comment by bhollis** [comment] 2017-12-27 06:31
Are you sure you don't have any extensions causing problems? Have you force refreshed and made sure you're on the latest version (4.31)?

**Comment by tricksofthetrade** [comment] 2017-12-27 06:34
Oh I already know there are extensions causing the problem (pre-CoO it caused no problems). I just stopped using DIM web and used the phone app. I don't really want to run without the extensions.

**Comment by duckmanBR** [comment] 2017-12-27 12:03
@tricksofthetrade but did you identified which extension is causing the problem?
When we say "disable your extensions"/"run in incognito" is just to pinpoint who is culprit.  Unless it's a extension that have nothing to do with blocking cookies/access (and then we probably can't tune it to stop breaking DIM) we can try to whitelist bungie/dim sites to make it work again...
Unless you are happy with using on mobile (I use it that way 99% of the time)... :smile:

**Comment by tricksofthetrade** [comment] 2017-12-27 13:28
I'm about 97% sure that Privacy Badger is causing the issue.

**Comment by duckmanBR** [comment] 2017-12-27 14:17
So, try to whitelist *.bungie.net

**Comment by Bubbajames29** [comment] 2018-01-03 23:09
As of just last night I have the same issue. I am using Firefox v.57.0.3, have talked to the guys on the DIM Discord and gone through all the steps of Private window, clearing cache/cookies and trying different browsers and devices. DIM works when I am on my mobile data on my phone so I am fairly sure that the issue is related to my router.

**Closed** 2018-01-22 05:14 UTC
