### ISSUE TITLE
manual refresh and/or disable automatic transferring

### ISSUE THREAD

**Issue by mc711** [DestinyItemManager/DIM#4498] opened 2019-10-19 02:55 UTC
please allow manual refresh and/or disabling automatic transferring when slots are full

 i know DIM auto refreshes when you switch focus from destiny to DIM but most likely due to api refresh limit, when i am inventory managing (dismantling or transferring) i am unable to refresh my inventory. 
when i transfer an item to a slot,  DIM sees the slot as occupied (but empty in game) it will make space by transferring a item to vault. this can be very annoying because my vault is always full so i always have to look around my vault for the item that was transferred

please add an option, this will save time and undesired api calls, this shouldnt be a problem because if there is already no space it returns a "no slot available" anyways. so auto transferring is not really necessary.

i understand this is mostly for convenience for other player but also other managers allow this type of transferring so it is definitely possible...

**Comment by bhollis** [comment] 2019-10-19 03:54
Duplicate of https://github.com/DestinyItemManager/DIM/issues/3666 (I think)

**Closed by bhollis** 2019-10-19 03:54 UTC
