### ISSUE TITLE
View in-game tracked tasks in DIM

### ISSUE THREAD

**Issue by Prometheus3375** [DestinyItemManager/DIM#9452] opened 2023-05-10 22:20 UTC
### Proposed change

Before the Lightfall one can track one triumph in-game and it it will be shown in DIM 
Tracked Triumphs category. Since Lightfall, one can track up to 3 Guardian Rank tasks and up to 6 other tasks (triumphs or challenges). But they are not visible in DIM anymore. I would like to have it back with some tunes.

1. Rename "Tracked Triumphs" category to "Tracked Tasks" or "Tracked Objectives", because you can track not only triumphs (DIM is already capable to add challenges there with its own tracker).
2. Return displaying of tracked tasks in-game.
3. Probably add another category for Guardian Rank tasks. This one should be hidden if no GR tasks are tracked.

### How does this fit into your workflow?

I usually use in-game tracker for tasks that should be done till or within some time, because it is limited. In DIM I track some grindy tasks like catalysts or "clear X many times" so that each time I open Progress tab it will remind me about them. But I want to view all tracked tasks at once as before Lightfall. Of course I can track in DIM all in-game tracked tasks, but then there will be no synchronization leading to more manual work.

Speaking of Guardian Ranks, I am not sure if its own category is really useful; maybe Guardian Rank tasks should not be viewed at all, because for me their in-game tracker is enough.

**Comment by robojumper** [comment] 2023-05-11 07:22
The Bungie.net API currently doesn't expose this -- Bungie-net/api#1803.

**Comment by bhollis** [comment] 2023-05-11 18:01
Duplicate of https://github.com/DestinyItemManager/DIM/issues/9174

**Closed by bhollis** 2023-05-11 18:01 UTC
Labels: Enhancement, Bungie API Limitation
