### ISSUE TITLE
allow search of community info for unowned items

### ISSUE THREAD

**Issue by shaver** [DestinyItemManager/DIM#2539] opened 2018-01-12 17:13 UTC
Looking at stuff like Xur's offerings and faction purchases, it would be great to be able to see what the community thinks of different items before acquiring them.

**Comment by bhollis** [comment] 2018-01-15 04:25
Thanks! I'll file this as a duplicate of #2363. We'll also support vendor viewing (with ratings) once the API is released for that.

**Closed by bhollis** 2018-01-15 04:25 UTC
