### ISSUE TITLE
Avoid transferring items to characters that are level 1, power 100.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2113] opened 2017-09-10 03:15 UTC
These characters haven't played the opening mission and cannot move items from them.  DIM tries to balance the vault and will move items to these alts with no way to get them back.  Would be a good go-forward optimization for returning players.

**Comment by bhollis** [comment] 2017-09-10 05:31
I have two such characters, and I'm unable to reproduce any problem. I can transfer items to and from those characters, with DIM or the Companion.

You may be thinking of the starting weapons, which are marked as non-transferable?

**Comment by bhollis** [comment] 2017-09-10 05:55
More possible explanations, cross posted from Bungie-net/api#81:

They tried to transfer the Traveler's Chosen, which is weirdly not transferable (or lockable!) where the other starting gear is transferable.
They were confused by bugs DIM had in transferring items in general (we had their D1 characters in the menu of transfer targets instead of their D2 characters, and that obviously won't work) and it made them believe their item was stuck.
Issue Bungie-net/api#80 may have caused them to believe they couldn't transfer items, since it would make items look like they didn't move.

**Comment by bhollis** [comment] 2017-09-10 06:25
I confirmed with a friend who had the problem described originally that DIM v4.13.0 fixes the issue and they can transfer off of the uninitialized character. So it was one of the explanations listed above.

**Closed by bhollis** 2017-09-10 06:25 UTC
Labels: Feature: D2
