### ISSUE TITLE
Slow sheet close animation

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#7458] opened 2021-12-11 23:23 UTC
We've gotten reports that the sheet close animation is very slow, especially on complex sheets like Compare. This doesn't reproduce for everyone (including yours truly) and doesn't reproduce on all sheets.

**Comment by bhollis** [comment] 2021-12-15 04:14
Apparently this happens more when a search is active

**Comment by Dayde** [comment] 2022-01-17 18:14
I reproduce this 100% with my vault search: `-is:tagged` click any item and use the compare tool with a maximized window on a large resolution 2560×1440.
It takes about 8seconds to completely show up (or disappear).

I also confirm that without the search the animation happens as expected.
There are 46 frames on the animation taking 155 to 170 ms each.
If I do the same on my secondary display which is only 1680×1050 the animation happens as expected.

Filtering my vault to sort it out is my main use case of DIM and this is getting a bit annoying I confess :)

Using DIM Beta latest version as an "installed" browser app.

**Comment by bhollis** [comment] 2022-01-17 23:22
With DIM fullscreened on a 3456 × 2234 screen, the search `-is:tagged`, and using compare tool from any item, the compare sheet is smooth as butter. Frame graph shows 60-90fps during the animation. Of course, I'm on macOS using Chrome, and have never seen an issue with this animation. I don't own a Windows computer to test with.

I can confirm using Chrome's "Rendering" debugger that no repaint is happening during the show/hide animation - the sheet is rendered once and then that image is slid off the page, rather than being re-rendered per frame.

My suspicion is that this is a Windows problem, potentially involving graphics drivers and maybe even being low on video RAM. Are you on Windows? Are you using Chrome? What GPU do you have? Does reinstalling/upgrading your video drivers help?

**Comment by delphiactual** [comment] 2022-01-18 00:23
updating my AMD drivers did solve this for me.

**Comment by bhollis** [comment] 2022-01-18 01:18
Definitely sounds like a video memory issue then? Like maybe there's a texture leak in Chrome with those drivers?

**Comment by Dayde** [comment] 2022-01-18 11:28
Interesting point !
Windows 11 / nvidia 1080Ti latest driver 511.23

I’ve tried tweaking some nvidia control panel options without any result.
I can reproduce the issue on chrome and brave but it is smooth on firefox.

**Comment by bhollis** [comment] 2022-01-18 15:29
How much video memory do you have?

I wonder if Chrome is allocating new textures for the scaled-down images.

**Comment by Dayde** [comment] 2022-01-18 20:25
11GB of dedicated VRAM
around 300MB taken by the only chrome process using VRAM when I launch DIM, ~60MB more when I enter the search

**Comment by Dayde** [comment] 2022-01-18 22:27
I reproduce with a local DIM install but have not been able to pinpoint the problem.
Chrome dev tools is not very helpful, it shows the long runnig tasks but will only mark the long parts as System or Idle.
If you have other tools to try and debug this I’d be glad to help and learn :)

**Comment by Dayde** [comment] 2022-01-18 22:56
Also I reproduce on  Linux (debian-testing) / chrome-stable but running an Intel Graphics chipset with no dedicated VRAM and 30GB of shareable VRAM (32GB of memory system wise)
Although I can see it is no proof that the problem is not only on windows given the difference of setup, it behaves really similarly and chrome dev tools performance profiler output looks the same in my most humble opinion.

**Comment by bhollis** [comment] 2022-01-19 04:41
I merged a test change into beta that removes the scale from search-hidden items. My hypothesis is that this removes a texture write that could cause problems.

**Comment by Dayde** [comment] 2022-01-19 05:59
I can see an improvement but still is a bit laggy.
The previously ~160ms task are now ~90ms and there are fewer steps ~40 -> ~30. (so still about 3s)
Without the search, the same test results in 6 tasks of ~40ms.

For the record I don’t think it is specific to the sheet close animation, the slow seems to affect all animations (highlight on hover for example is far less responsive with my -is:tagged search on).

Writing this I tried something else, instead of searching on `-is:tagged` as before I searched on a specific item name and guess what it is far less laggy, not butter smooth though, the animation only got 4 frames but it runs in time (I’m guessing the animation time is 200ms here right ?)
My point being the issue probably has multiple roots.

**Comment by bhollis** [comment] 2022-01-19 06:30
Unfortunately at this point I think we're talking about a problem that's at least at the browser level, if not a driver issue. There's no reason why having a few elements with reduced opacity should affect the responsiveness of the page.

**Comment by MeatSim** [comment] 2022-01-30 02:38
My technical knowledge is limited, but this wasn't an issue for me before. My hardware hasn't changed, so it seems the change was in software, whether DIM, browser, or OS.

fwiw, I'm running Edge on an old Windows 10 laptop with AMD A6 (drivers are up to date) and 8GB RAM. Not surprisingly, Chrome is also slow.

Comparing items without search is snappy in Edge and Chrome (~1 second). Comparing items with search causes slow animation for both sheet open and sheet close in Edge and Chrome (~6-10 seconds).

Firefox is janky but more consistent (~2-3 seconds) with or without search.

**Comment by bhollis** [comment] 2022-01-30 02:50
> this wasn't an issue for me before

Before when, roughly?

Did anything improve when I changed to no longer scale hidden items? Are all animations slow, or just the sheet?

**Comment by bhollis** [comment] 2022-01-30 02:53
Is the loadout drawer slow to show and hide as well?

**Comment by MeatSim** [comment] 2022-01-30 03:05
> 

Unfortunately, I didn't record when I first noticed the problem. My impression is that it was "recent," but that could be as far back as a month or so ago 🤦‍♂️

**Comment by MeatSim** [comment] 2022-01-30 03:16
> 

You mean like "Select exotic" and "Select mods"? "Select exotic" opens and closes within 1 second. "Select mods" opens in ~2 seconds and closes in 1 second. This is in Edge- I can test in other browsers if you'd like.

**Comment by bhollis** [comment] 2022-01-30 03:42
No I mean if you input a search on the inventory screen that causes many items to be dimmed out, and then you click your character tile and choose "Create Loadout", does the drawer that appears animate open and closed slowly the way the Compare drawer does?

**Comment by MeatSim** [comment] 2022-01-30 04:10
> No I mean if you input a search on the inventory screen that causes many items to be dimmed out, and then you click your character tile and choose "Create Loadout", does the drawer that appears animate open and closed slowly the way the Compare drawer does?

"Create Loadout" takes ~3-4 seconds to open or close with search and under 1 second to open or close without search.

**Comment by bhollis** [comment] 2022-01-30 04:18
OK, so it doesn't have anything to do with what's in the sheet

**Comment by MeatSim** [comment] 2022-01-30 04:21
A few other notes, fwiw:
 - The annoying thing about this issue is that until the sheet is completely off screen, it can effectively block other actions, like clicking on an item that can't be compared with the currently compared items.
 - Clearing the search bar so that no items are dimmed out does not make closing the sheet noticeably faster.

**Comment by bhollis** [comment] 2022-01-30 05:51
I made another change which may help here. Can you try the very latest Beta version and let me know if it's any better?

**Comment by MeatSim** [comment] 2022-01-30 06:43
> I made another change which may help here. Can you try the very latest Beta version and let me know if it's any better?

No improvement. If anything, it feels somewhat slower (~8-12 seconds).

**Comment by MeatSim** [comment] 2022-01-30 06:46
This is the beta at https://beta.destinyitemmanager.com, right?

**Comment by bhollis** [comment] 2022-01-30 07:09
That's the one, yes. I've verified in the debugger that after my change the layer doesn't repaint at all during the animation, where it used to. 8-12 seconds is insane, it's a ~500ms animation.

**Comment by bhollis** [comment] 2022-01-30 07:21
What version of Chrome are you using?

**Comment by MeatSim** [comment] 2022-01-30 23:50
> What version of Chrome are you using?

Last night, I tested in Microsoft Edge Version 97.0.1072.76 (Official build) (64-bit). Chrome was Version 97.0.4692.99 (Official Build) (64-bit). Tested beta in Chrome just now: 6-12 seconds.

**Comment by bhollis** [comment] 2022-01-31 04:41
I'm afraid the only conclusion I can come to is that there's something seriously wrong with your computer. That said, I've ordered a terrible Windows laptop to hopefully continue testing on.

**Comment by MeatSim** [comment] 2022-01-31 06:11
> I'm afraid the only conclusion I can come to is that there's something seriously wrong with your computer. That said, I've ordered a terrible Windows laptop to hopefully continue testing on.

That's entirely possible, but it didn't exhibit this behavior a couple months ago 🤷‍♂️ 

Beta in Firefox just now is 2-3 seconds, still janky.

**Comment by bhollis** [comment] 2022-02-14 06:30
Here's the debugger on my machine showing a single task from the sheet show animation, while many items are hidden by search. Each task is ~5ms and the animation is maintaining 120fps. The longest part of the task is style recalculation which is taking around 0.9ms each time. Can someone who is suffering from this issue show their version of this?

<img width="1367" alt="Screen Shot 2022-02-13 at 10 28 09 PM" src="https://user-images.githubusercontent.com/313208/153811623-9696aff2-af52-4756-b01b-6cd9ef19eca3.png">

**Comment by bhollis** [comment] 2022-02-14 06:31
Also, do any of you who are having this problem have any extensions installed?

**Comment by MeatSim** [comment] 2022-02-15 04:57
Does this help? Took ~7 seconds between click and finish.

![image](https://user-images.githubusercontent.com/31776312/153995237-dca99616-f5f9-49b7-9d3f-5eec2d1a5877.png)


> Here's the performance trace on my machine showing a single task from the sheet show animation, while many items are hidden by search. Each task is ~5ms and the animation is maintaining 120fps. The longest part of the task is style recalculation which is taking around 0.9ms each time. Can someone who is suffering from this issue show their version of this?
> 
> <img alt="Screen Shot 2022-02-13 at 10 28 09 PM" width="1367" src="https://user-images.githubusercontent.com/313208/153811623-9696aff2-af52-4756-b01b-6cd9ef19eca3.png">

**Comment by MeatSim** [comment] 2022-02-15 05:02
> Also, do any of you who are having this problem have any extensions installed?

I don't have any extensions installed

**Comment by MeatSim** [comment] 2022-02-19 15:58
> We changed how the animations work, a bit. Any better?

Until a few minutes ago, beta animation was much faster 😀 but I noticed that I could click the sheet-close link without any response 😕 It took either two clicks or holding the mouse button down slightly longer. Seems the changes were reverted a few minutes ago.

**Comment by bhollis** [comment] 2022-02-19 18:18
Not sure I understand. Nothing was reverted and nothing was changed about the close button.

**Comment by MeatSim** [comment] 2022-02-20 03:07
> Not sure I understand. Nothing was reverted and nothing was changed about the close button.

Not sure what happened, but about fifteen minutes after my post, beta animation returned to being fast and sheet-close link takes either two clicks or holding mouseDown longer. 🤷‍♂️

**Comment by MeatSim** [comment] 2022-02-20 03:52
What's weird is that when I record with DevTools, clicking sheet-close works, but the sheet descends a few pixels, goes back up, then disappears. It dropped a couple frames, but I don't see how that would explain the sheet going back up.

**Comment by bhollis** [comment] 2022-04-03 01:01
Are folks still seeing this?

**Comment by MeatSim** [comment] 2022-04-03 20:29
> Are folks still seeing this?

I'm not.

**Closed** 2022-04-03 21:23 UTC
Labels: Help Wanted: Developer, Need More Details
