### ISSUE TITLE
Display the name of loadout(s) that an item is in when it is clicked on

### ISSUE THREAD

**Issue by TheRealIceCracker** [DestinyItemManager/DIM#8104] opened 2022-03-09 01:53 UTC
### Proposed change

Show the names of the loadout(s) that an item is in when it's clicked on, either below stats or possibly in another collapsible sidebar?

### How does this fit into your workflow?

Whenever I do a vault purge, I go through items per slot and purge mostly based on custom stat total but I don't want to delete an item that's in a loadout I'm currently using. I can filter by -is:inloadout but this only tells me that it's in a loadout, not necessarily a loadout I've maybe just stopped using or maybe it's in some WIP/blank loadout for some reason. Being able to click on the item and see which loadout(s) it's in would be really nice.

Granted I could get around this by clearing my blank/WIP/unused loadouts before doing a purge, but I think there would be other use cases for this as well, such as being able to see what other loadouts an item is in when creating a loadout, and exclude it for reasons like it needs to keep its current elemental affinity for the other loadout.

Also, in general there is no other way to tell what loadout an item is in other than looking at that specific loadout.

**Comment by bhollis** [comment] 2022-03-09 01:55
Duplicate of #7218

**Closed by bhollis** 2022-03-09 01:55 UTC
Labels: Enhancement
