### ISSUE TITLE
Ignore interchangeable perks and perks to stats in optimization

### ISSUE THREAD

**Issue by lainverse** [DestinyItemManager/DIM#4469] opened 2019-10-14 14:08 UTC
I've noticed that Loadout Optimizer prefers items with stat perks in them since they give 60+ points overall and naturally make builds with higher overall stats. However, it means potentially better builds end up looking worse. Instead of counting them toward actual build stats I propose to count first slot on all items (unless specific perk is locked) as free +1 tier and mark items with wrong perk with recommendation to swap perk.
Or just an option to not count these +1 tier perks at all.

**Comment by bhollis** [comment] 2019-10-14 15:00
Duplicate of https://github.com/DestinyItemManager/DIM/issues/4470, I think.

**Closed by bhollis** 2019-10-14 15:00 UTC
