### ISSUE TITLE
Loadout with Subclass will unequip Original Subclass from Character

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#703] opened 2016-07-19 05:26 UTC
When you create a loadout, you have to click on a subclass on a specific character to add a subclass to the loadout.

When you apply the loadout to a character that was not the original owner, the loadout logic will unequip the subclass from the original character.  The expectation would be to leave the subclass as is.

**Comment by bhollis** [comment] 2016-07-22 06:38
I believe this is fundamentally a duplicate of #702.

**Comment by SunburnedGoose** [comment] 2016-07-25 18:43
I expect it will resolve when #702 is fixed.

**Comment by bhollis** [comment] 2016-08-03 06:45
I think this was fixed by #702, but I can't test it (no 2 characters of the same class). Holler if you think it's still busted.

**Closed by bhollis** 2016-08-03 06:45 UTC
Labels: bug
