### ISSUE TITLE
Compare Vendor Items

### ISSUE THREAD

**Issue by bmstasa** [DestinyItemManager/DIM#7333] opened 2021-11-28 20:42 UTC
### Proposed change

Would like to be able to compare vendor item(s) to item(s) already in inventory to see if the vendor item(s) are worth acquiring.  For example, compare an exotic armor roll from Xur to armor in the vault.

### How does this fit into your workflow?

When clicking on the item from the vendor screen, would like to see the compare option that is available when clicking on an item in inventory.

**Comment by bhollis** [comment] 2021-11-28 21:37
Thanks for the suggestion! We're already working on this one. 

Duplicate of #6878

**Closed** 2021-11-28 21:38 UTC
Labels: Enhancement
