### ISSUE TITLE
Weapons with non-reacquirable elements should not match `is:reacquirable`

### ISSUE THREAD

**Issue by koinu** [DestinyItemManager/DIM#5384] opened 2020-06-28 21:18 UTC
For `season:<=3` weapons, DIM should exclude them from `is:reacquirable` if the element is different than what you would get from pulling the weapon from collections.

This situation exists due to the changes that happened to mods with the Forsaken launch.

![Inventory - Arc](https://user-images.githubusercontent.com/1015755/85958386-091f8300-b94a-11ea-96ea-15c5bdb4bc92.png)

![Collections - Void](https://user-images.githubusercontent.com/1015755/85958391-10df2780-b94a-11ea-969d-1d439a4e3bbc.jpg)

**Comment by bhollis** [comment] 2020-07-01 17:42
Duplicate of #4568

**Closed by bhollis** 2020-07-01 17:42 UTC
