### ISSUE TITLE
Power Friends Mod - still showing as stacking mobility. 

### ISSUE THREAD

**Issue by GrandpaDub** [DestinyItemManager/DIM#6336] opened 2020-12-14 20:05 UTC
**What version of DIM are you using?**
Version 6.43.2.1000077 (beta), built on 12/13/2020, 6:53:12 PM

**What Browser and OS are you using?**
Chrome

**Describe the bug and how to make it happen**
In the loadout optimizer when you add powerful friends to multiple items it still shows the mobility stat stacking which has been fixed.

**Comment by kyleshay** [comment] 2020-12-14 20:07
related (duplicate?):  #6307

**Comment by bhollis** [comment] 2020-12-14 20:17
Duplicate of https://github.com/DestinyItemManager/DIM/issues/6336

**Closed by bhollis** 2020-12-14 20:17 UTC
Labels: Bug
