### ISSUE TITLE
Add a compare items panel

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#991] opened 2016-09-30 19:18 UTC
Add the ability to see two items at the same time, to compare them.

For reference: 
https://www.reddit.com/r/DestinyItemManager/comments/558g4v/suggestion_show_the_max_light_possible_on/

**Comment by kyleshay** [comment] 2016-09-30 20:35
Duplicate of #494, thanks for adding that link here, good to have more input so we know what makes sense to build.

**Closed by kyleshay** 2016-09-30 20:35 UTC
