### ISSUE TITLE
Transfer search to vault doesn't transfer all items from search result

### ISSUE THREAD

**Issue by kohum** [DestinyItemManager/DIM#2933] opened 2018-07-12 03:44 UTC
This is happening on the latest Beta version - Version 4.60.0.2205 (beta), built on 7/11/2018, 2:30:26 PM

- Search for "is:modifications is:legendary"
- From vault emblem click Transfer search "is:modifications...
- Only some items are transferred to the vault

**Comment by duckmanBR** [comment] 2018-07-12 13:34
Question:  The items that aren't being transferred are the ones that you already have an stack on vault?

If yes, the root of the problem is probably the same as #2932.

**Closed** 2018-07-14 19:17 UTC
Labels: Bug, Feature: Loadouts
