### ISSUE TITLE
Fashion Loadouts Dropdown

### ISSUE THREAD

**Issue by FutureD00D3R** [DestinyItemManager/DIM#7705] opened 2022-01-09 10:31 UTC
### Proposed change

Very simply put: allow users to create fashion loadouts and separate them visually in the gui from mod loadouts. Theoretically an easy implementation, use the already existing gui for adding shaders and ornaments, but just allow us to store those loadouts in a drop down in the loadout menu separate from the 'big boy' complete loadouts that feature shaders + armor + armor mods. 

In my mind it would be best to just add a button below "loadout optimizer" called "fashion loadouts" that uses the already existing gui to add the fashion elements to a loadout, but stores only those elements in the aforementioned dropdown. 

For an even simpler implementation: a single checkbox when creating a loadout that stores it to a "cosmetics only" loadout list which, when applied, only changes ornaments and shaders. The biggest QoL change would be the cosmetic only loadout list. 

This system could be more accessible for new players, as going to a different 'armor mods' and 'shaders' menus would beless  confusing for them, allowing them to tackle different parts of their loadout independently. Rather than having to create a new loadout that has no 'armor' no 'mods' no 'class' but then has the 'ornaments and shaders' only if they desire to just simply switch their outfit. 

### How does this fit into your workflow?

Before:
I create a new loadout from equipped gear
Remove all mods
Remove all armor pieces
Remove all weapons
Save loadout (which is stored intermixed in the list of power affecting loadouts) 

Ideal:
Create new fashion loadout from equipped gear
Preserves only ornaments + shaders 
Save loadout (stored in separate drop down)

In use: 
I click "apply loadout" to a loadout that straps on what I need (mods/armor pieces) for the next activity.
I don't like the current outfit I have on, so I go shopping for a fashion loadout saved in the dropdown.
I click "apply fashion loadout" to a loadout under that dropdown while preserving all 'tangible' (power affecting) mods

**Comment by bhollis** [comment] 2022-01-09 15:40
Duplicate of #7663, linking to that issue

**Closed by bhollis** 2022-01-09 15:40 UTC
Labels: Enhancement
