### ISSUE TITLE
Transferring an equipped Stillpiercer to another character fails

### ISSUE THREAD

**Issue by koush** [DestinyItemManager/DIM#414] opened 2016-02-24 21:14 UTC
Steps to reproduce.

0) Have two hunters. This may work with a hunter and another class, but unsure.
1) Equip Stillpiercer on Hunter 1.
2) Attempt to transfer equipped Stillpiercer to Hunter 2 (or another class maybe?).
3) Transfer fails with error box "Stillpiercer"

I can work around this by equipping something other than a Stillpiercer, so it is in the inventory, then transferring it.

**Comment by SunburnedGoose** [comment] 2016-02-24 21:17
It could be failing because it is trying to equip something that the character cannot use.  There are a couple of situations like that.  If you can have a google hangout with me, I can see what's happening when moving an item with Bungie and give you an answer.

**Comment by kyleshay** [comment] 2016-02-24 21:19
hmm, interesting. tried it myself and can't even move it to the vault.

**Comment by SunburnedGoose** [comment] 2016-02-24 21:48
Is there one in the vault already?

**Comment by kyleshay** [comment] 2016-02-24 21:50
i only have one. that action was me just dragging the stillpiercer to the inventory spot on the same character. that fails. if i drag that shotgun to replace it, it works. once the stillpiercer is in the unequipped slot it can move anywhere freely.

**Comment by SunburnedGoose** [comment] 2016-02-24 21:51
What weapon was it trying to replace it with?  You'll have to watch the network traffic to see what itemHash it is moving.

**Comment by kyleshay** [comment] 2016-02-24 21:51
no network activity at all. there is activity if i drag the shotty to equip it.

**Comment by kyleshay** [comment] 2016-02-24 21:52
no console errors either.

**Comment by SunburnedGoose** [comment] 2016-02-24 21:53
Never had a hunter :/  Can't test.

**Comment by kyleshay** [comment] 2016-02-24 22:03
the issue is in `dimItemService.factory.js#141`

          .where({
            classType: item.classType
          })

since it's an item for just hunters, we're filtering by class type (so that armor equips work properly and we don't try to equip a titan helmet on a hunter) but this is messed up for weapons, because `classType` for a normal weapon = 1, but `classType` for a hunter = 3

**Comment by kyleshay** [comment] 2016-02-24 22:12
check out the PR for more details. i think we're good. tried it locally and i think things are good.

**Comment by kyleshay** [comment] 2016-02-25 19:12
fixed in #415

**Closed by kyleshay** 2016-02-25 19:12 UTC
