### ISSUE TITLE
Add way to replace one armor piece with another in all affected Loadouts

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [DestinyItemManager/DIM#10270] opened 2024-02-14 19:44 UTC
### Proposed change

The Feature Request: Allow the user to select armor piece A to replace it with armor piece B (same slot) in all Loadouts where piece A appears. (Possibly limited to legendary to legendary and exotic to same exotic.) All other aspects of the Loadout remain the same.

### How does this fit into your workflow?

The Scenario: you have a chest piece that is used in multiple Loadouts. You obtain a new chest piece that has a similar or better stat distribution and higher stats  (e.g. higher in your preferred stats). You want to substitute the new piece for the old piece in all Loadouts that use the old piece then delete the old piece (since it is redundant). Currently, to do this, you have to individually open, edit, replace the armor, and save each affected Loadout.  Adding this feature for easy global drop-in replacement of armor in affected Loadouts will make armor inventory management  easier. The user can quickly substitute then eliminate redundant armor without breaking multiple Loadouts where it is used.

Thanks for your consideration.

**Comment by bhollis** [comment] 2024-02-17 01:32
#9812 is the place this would get implemented, though I doubt we'll extend it as far as replacing one item for another globally. The intended workflow for armor in loadouts is that you create them with the Loadout Optimizer, and then also let Loadout Optimizer replace that piece when you want to. This allows for the possibility that different replacement pieces may give the best stats.

Anyway, closing/linking as a dupe of #9812 in spirit.

**Closed by bhollis** 2024-02-17 01:32 UTC
Labels: Enhancement
