### ISSUE TITLE
Organizer screen not rotating, therefore, not functioning

### ISSUE THREAD

**Issue by Ravynne** [DestinyItemManager/DIM#7740] opened 2022-01-13 05:24 UTC
### DIM Version

6.99.1

### Browser Details

Chrome 97.0.4692.87

### OS Details

Android 12 on Pixel 6 Pro

### Describe the bug

If auto rotate is off, opening the organizer page, and rotating the display used to display the rotate button link and then the organizer would function.

If auto rotate is on, even after force closing the app, going to the organizer page does not go into rotate mode.

The app used to do this screen fine until recently.

**Comment by bhollis** [comment] 2022-01-14 00:54
Duplicate of #7558

**Closed by bhollis** 2022-01-14 00:54 UTC
Labels: Bug
