### ISSUE TITLE
Mod Slot Management

### ISSUE THREAD

**Issue by hendersj** [DestinyItemManager/DIM#7412] opened 2021-12-08 17:45 UTC
### Proposed change

Currently the mod slots in a loadout are set up to remove anything not included in the loadout (I think that's if any mods are included in the loadout).

It would be useful to be able to slot certain types of mods based on a loadout without removing existing mods.

For example, a loadout that includes a specific armor set with specific mods for charged with light/warmind cell/etc. along with mods for stat boosts shouldn't change when a separate loadout with specific weapons (which might include the addition of mods specific for the weapons) is equipped.  For example, having an armor loadout that includes res/rec/int mods should stay put when switching a weapon loadout that includes loader/scavenger/champion/reserves mods (or other weapon-specific mods).

### How does this fit into your workflow?

I have a few loadouts that are armor-only, and a few that are weapons-only.  For example, I have loadouts for Stormcaller, Voidwalker, Dawnblade/Well of Radiance, and Stasis classes, and I mix them with loadouts for different weapon sets.

Mods in loadouts would be much more convenient if they were additive/replaced existing similar mods, or "leave it alone" if the mod cost is incompatible (ie, don't remove an int mod if the weapon mods would make the total mod cost 12/higher than the max for the armor).

**Comment by bhollis** [comment] 2021-12-08 18:08
Thanks for the thought put into this! Closing as a duplicate of #7371.

**Closed by bhollis** 2021-12-08 18:08 UTC
Labels: Enhancement

**Comment by hendersj** [comment] 2021-12-08 18:14
Thanks!  Sorry, I should have looked to see if this had already been suggested.  Glad to hear that you're thinking about this already. :)
