### ISSUE TITLE
Allow to assume 1 to 5 masterworked stats in loadout optimizer

### ISSUE THREAD

**Issue by quetschke** [DestinyItemManager/DIM#6291] opened 2020-12-07 18:18 UTC
**Proposed change**
Currently the loadout optimizer allows to assume all armor pieces to be masterworked. That is extremely expensive and sometimes one or two masterworked pieces would be enough to get into a new tier.
Please add a 0 to 5 dropdown menu to indicate the assumed number of masterworked armor pieces. If a tier includes already masterworked armor that should be counted toward the assumed number.

**How does this fit into your workflow?**
This would allow to find the best armor when only a few ascendant shards are available.

**Comment by bhollis** [comment] 2020-12-07 18:30
Sort of a duplicate of https://github.com/DestinyItemManager/DIM/issues/5543.

We've talked about instead having a slider of "how many shards are you willing to spend".

**Closed by bhollis** 2020-12-07 18:30 UTC
Labels: Enhancement

**Comment by quetschke** [comment] 2020-12-07 19:46
That would be cool!
