### ISSUE TITLE
Scrolling by swiping in the comparison pane rarely works. 

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#5323] opened 2020-06-15 16:15 UTC
**What version of DIM are you using?**
Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?

Version 6.15.0 (release), built on 6/14/2020, 2:46:57 PM
Orange icon

**What Browser and OS are you using?**
It helps to know what type of browser and what version you're using. Have you installed DIM as an app through Chrome or Safari?

Safari, iOS 13.5 on an iPhone 8 Plus.

**Describe the bug and how to make it happen**
Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.

In the comparison window on an iPhone it is nearly impossible to scroll (by swiping). Both in portrait and landscape mode. It works sporadically. This is a long standing bug in DIM. 

**Include devtools console logs**
If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up:

```
Paste console logs here
```

**Comment by bhollis** [comment] 2020-06-15 17:38
Duplicate of https://github.com/DestinyItemManager/DIM/issues/3424

This is part of why the Organizer is really the replacement for Compare.

**Closed by bhollis** 2020-06-15 17:38 UTC
Labels: Bug
