### ISSUE TITLE
Collections Blue Check missing from vendor armor

### ISSUE THREAD

**Issue by StardustD2** [DestinyItemManager/DIM#9930] opened 2023-09-28 20:38 UTC
### DIM Version

Version 7.87.0.1002969 (beta), built on 9/28/2023, 6:37:56 PM

### Browser Details

Opera 102.0.0.0 (and all other browsers)

### OS Details

Windows 10

### Describe the bug

The missing checkmark has been throwing me off for a while considering it's present on essentially every other vendor item. At the very least, it would be nice to have the "This item is unlocked in collections." text on the popup after clicking on the armor like how it works in the Records tab. 

### Vendor inventory:
![image](https://github.com/DestinyItemManager/DIM/assets/117818418/03817472-0479-46c2-b003-3e49181719c6)
### In-game screenshot showing it's unlocked:
![image](https://github.com/DestinyItemManager/DIM/assets/117818418/1e405e14-bc82-4c79-8bc9-0d1676a8731c)

### Records tab item popup:
![image](https://github.com/DestinyItemManager/DIM/assets/117818418/c70f0312-eaa6-421e-854e-bbf39a39dd9f)
### Vendor item popup:
![image](https://github.com/DestinyItemManager/DIM/assets/117818418/b1354579-4d1b-402e-b8ea-0c1d645bb05a)

**Comment by bhollis** [comment] 2023-09-28 21:02
Probably yet another duplicate of #7023

**Comment by bhollis** [comment] 2023-09-28 21:03
Also #8226

**Comment by StardustD2** [comment] 2023-09-28 21:09
So I guess it's a Bungie issue then? bummer

**Comment by robojumper** [comment] 2023-09-28 22:38
One observation: The "only show uncollected items" toggle filters these out, but this is also a bug in that function

https://github.com/DestinyItemManager/DIM/blob/6d53158ec0de71fe293260bde4e666d4ec6ea021/src/app/vendors/d2-vendors.ts#L226-L234

where items without a collectible that aren't mods are automatically considered collected. Sigh...

As for fixing the general issue - #9776 had to solve a very similar problem where some (ornament) armor item hashes didn't have a collections entry. We might be able to generalize that code to find related collectibles for vendor armor too.

**Closed** 2023-10-02 22:32 UTC
Labels: Bug, Feature: Vendors, Feature: Records
