### ISSUE TITLE
Be able to designate a favorite shader or a few ones

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8573] opened 2022-07-14 11:19 UTC
### Proposed change

Be able to designate a favorite shader or a few ones

### How does this fit into your workflow?

Right now, one has to know part of the name or scroll until one finds it. This is tedious, specially if one uses a limited number of shaders for say guns.

**Comment by bhollis** [comment] 2022-07-15 00:34
Duplicate of #7493

**Closed by bhollis** 2022-07-15 00:34 UTC
Labels: Enhancement
