### ISSUE TITLE
Error message pops up whenever a sync with the API occurs.

### ISSUE THREAD

**Issue by wilwayco** [DestinyItemManager/DIM#10778] opened 2024-11-01 21:25 UTC
### DIM Version

Version 8.44.0 (release), built on 10/27/2024, 9:23:40 PM

### Browser Details

Firefox Developer 133.0b3 (aarch64)

### OS Details

MacOS Sonoma 14.7

### Describe the bug

After the Bungie authentication, upon Inventory view load, a popup appears:

<img width="381" alt="image" src="https://github.com/user-attachments/assets/07f0f6e8-df7f-422e-abaf-3c35258a044c">

Let me know what other Firefox settings I can try and submit.  Here's my setting for History:
<img width="707" alt="image" src="https://github.com/user-attachments/assets/bbb21fd8-00e7-4c3a-8fc3-09dc28e1305e">

There are no wishlists other than the default voltron.txt.

Workaround:

Use Google Chrome (Version 130.0.6723.92 (Official Build) (arm64)) seems to work OK.

### Logs

```shell
[manifest] Error saving manifest file DOMException: IDBObjectStore.put: The serialized value is too large (size=267506836 bytes, max=267386880 bytes).
    i idb-keyval.ts:95
    _withIDBStore idb-keyval.ts:52
    _withIDBStore idb-keyval.ts:45
console.ts:40:19

Sometimes:


[manifest] Error saving manifest file DOMException: IDBObjectStore.put: The serialized value is too large (size=267506836 bytes, max=267386880 bytes).
    i idb-keyval.ts:95
    _withIDBStore idb-keyval.ts:52
    _withIDBStore idb-keyval.ts:45
    promise callback*_withIDBStore idb-keyval.ts:43
    i idb-keyval.ts:94
    s manifest-service-json.ts:260
    s manifest-service-json.ts:191
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    s manifest-service-json.ts:170
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:102
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:97
    r promises.ts:13
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    u d2-definitions.ts:162
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    i d2-stores.ts:288
    P trace.ts:67
    P handleCallbackErrors.ts:25
    P trace.ts:66
    P trace.ts:453
    P trace.ts:453
    withScope stackStrategy.ts:49
    u stackStrategy.ts:135
    l currentScopes.ts:59
console.ts:40:19
    mt console.ts:40
    a log.ts:47
    s manifest-service-json.ts:265
    s manifest-service-json.ts:191
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    s manifest-service-json.ts:170
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:102
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    S manifest-service-json.ts:97
    r promises.ts:13
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    u d2-definitions.ts:162
    r Redux
    c observerMiddleware.ts:62
    dispatch Redux
    i d2-stores.ts:288
    P trace.ts:67
    P handleCallbackErrors.ts:25
    P trace.ts:66
    P trace.ts:453
    P trace.ts:453
    withScope stackStrategy.ts:49
    u stackStrategy.ts:135
    l currentScopes.ts:59

​
```

**Comment by bhollis** [comment] 2024-11-02 01:08
Duplicate of #10764

**Closed by bhollis** 2024-11-02 01:08 UTC
Labels: Bug
