### ISSUE TITLE
Feature Request: Wishlist Creation Tool

### ISSUE THREAD

**Issue by joshmadewell** [DestinyItemManager/DIM#6231] opened 2020-11-26 19:04 UTC
**Proposed change**
Add Wishlist Creation Tool

**How does this fit into your workflow?**
I would like to add a "Wishlist Creator" tool to DIM which would allow you to select a gun, its perks and add it to a list which you could then download and use as your wishlist. At first I thought of building _yet another tool_ that would do this but figured it might make most sense within DIM itself. Curious to hear if this is something y'all would accept before beginning to work on it here.

**Comment by bhollis** [comment] 2020-11-26 19:24
Yeah that'd be pretty cool! We've talked about it a lot but haven't had anyone willing to work on it.

**Comment by 48klocs** [comment] 2020-12-02 00:09
There's 3rd party tools out there (like https://d2gunsmith.com/ ) that let you configure and export as you want. I've got my own little tool to generate permutations based on recommendations, but it's not super fit for human consumption.

It would be pretty neat.

**Comment by mkossoris** [comment] 2024-04-07 06:32
I might be interested in taking a stab in my free time as I was just thinking about wanting a wishlist. I know it's been several years since this issue was opened, so I'm curious if @bhollis is still wanting this feature, and if so, do you have specifics on what it might look like? For example, what the user flow might be, navigation, placement of the UI, etc.

Also thoughts on spinning up a simple service to store wishlists to make it more user friendly for non-developers (who likely don't have GitHub accounts)? It could be as simple as like AWS CloudFront + S3. This might also enable other creators to easily create and modify wishlists which could be awesome for the community (imagine Datto talking about a loadout in a video and having a link to it in the description as a wishlist).

**Comment by mkossoris** [comment] 2024-04-07 07:17
I did a bit of thinking about the short and long-term flows for this. We could start with an MVP version that is a simple list creation tool to create lists that can be exported along with instructions to host it on GitHub. However, I think there may be potential for a full feature set for wish list management, and it would be awesome to have it tie into Light.gg's "Source" tag to make it easier for users to take action on their wish lists to actually acquire the gear.

### MVP
**Create Wish List**
1. User navigates to Settings > Wish List
2. User clicks "Create Wish List" button which navigates to the Wish List Creator page, which is a two-column page with the list in one column and the search results in the other column
3. User uses global search bar to search for items with filter capabilities across all D2 items
4. User clicks "Add" button on result item or drags item to the list column
5. User clicks "Export Wish List" which compiles the list into the proper wish list format

**Edit Wish List**
1. User navigates to Settings > Wish List
2. User either clicks "Edit" button on one of their existing loaded lists or uses the "Load Wish List Rolls" section to upload a wish list which navigates to the Wish List Creator page
3. Same as above

### Long Term Features
* Create, edit, delete wish lists that can be stored using a service owned by DIM
* Display "source" tag from Light.gg (or from somewhere else) so user can easily determine how to acquire gear in wish lists
* Search community wish lists
* See items in wish lists that are owned by user (either specific roll or general item)
* Copy items from one wish list to another (e.g. grabbing god roll from voltron into a specific list the user wants)
* See what wishlists items are in in item detail popups
* As a side note, we'd pull the wish lists section out from the Settings section as this new panel would replace that functionality.

**Comment by bhollis** [comment] 2024-04-08 17:17
Duplicate of https://github.com/DestinyItemManager/DIM/issues/8629

**Closed by bhollis** 2024-04-08 17:17 UTC
Labels: Enhancement, Feature: Wish List
