### ISSUE TITLE
[Improvement] Add perk reviews and allow voting on said reviews

### ISSUE THREAD

**Issue by DesktopMan** [DestinyItemManager/DIM#1880] opened 2017-07-03 18:29 UTC
The perk descriptions in the game itself are very vague and it's hard to judge if a perk is good or not. Is "more damage" 10% or 50%? Who knows? This does not seem to have improved in Destiny 2 from what we've seen so far.

This feature would allow users to review perks and document more specifically what they actually do. This would be especially helpful for new players who aren't familiar with perks. Over time the most informative review should float to the top.

Followup suggestion: Append the best review to the standard (uninformative) perk text automatically

This feature would complement the gun review system nicely.

**Comment by 48klocs** [comment] 2017-07-04 17:16
Perks are... messy.  Some are easy to figure out (cluster bombs on rockets), some are tied to the class of weapon you have them on (rangefinder), others have the same name and the same rough effect but the effect under the covers (as far as stat changes) can differ from weapon to weapon.

**Comment by kyleshay** [comment] 2017-07-11 23:29
somewhat duplicate of #1737 since d2 perks will not be randomly selected on your weapon, reviews will work a little differently.

**Closed by kyleshay** 2017-07-11 23:29 UTC
Labels: enhancement
