### ISSUE TITLE
DIM not working.

### ISSUE THREAD

**Issue by Volatique** [DestinyItemManager/DIM#8659] opened 2022-08-26 18:33 UTC
Hello.

Since the release of Season 18 of Destiny 2, DIM has not been functional for me.

I've gone through the troubleshooting process (Refreshing Browser, clearing Cache, trying different browser, etc) and I've still had no luck. At one point, I received an Error 503 but I mostly receive the error that it can't sync, can't download, or bungie.net is moving too slowly but they'll continue to work as long as I have DIM open. Sometimes it'll even just continuously cycle through "Loading Destiny Profile..."

**Comment by bhollis** [comment] 2022-08-26 22:09
Fixed now. Further issues are caused by Bungie.net, not DIM.

**Closed by bhollis** 2022-08-26 22:09 UTC

**Comment by Volatique** [comment] 2022-08-27 00:41
Thank-you.
