### ISSUE TITLE
Search bar icons unreadable

### ISSUE THREAD

**Issue by Funktion29** [DestinyItemManager/DIM#5678] opened 2020-08-29 03:55 UTC
![4A03495F-BCC7-4337-8354-8FFCE3C9E6A8](https://user-images.githubusercontent.com/22829473/91627989-706caa00-e970-11ea-936f-54deb1ae9c89.png)
I’m not sure when the icons changed, but it was a bit ago. There was just one at first and I just thought it was a grey box, not realizing it was the X. Until I tried a search recently and the bar became unreadable/unusable with many ‘grey boxes’.  I realized these were supposed to be the previous ‘x’ etc. 

This is on my ipad. Day view, True Tone on, night shift on. Running ios 14 b6. BUT i see this same thing on my iPhone running the standard iOS 13.  Launched DIM via the ‘Home Screen app’ on ipad, and in safari on iPhone w/ same results. 

They are just not readable, or even recognizable as icons to me currently, not sure if its an ios thing or?
Thanks

**Comment by bhollis** [comment] 2020-08-29 03:58
It is most certainly an iOS thing. 

Duplicate of https://github.com/DestinyItemManager/DIM/issues/5656

**Closed by bhollis** 2020-08-29 03:58 UTC
