### ISSUE TITLE
bug: weapons stay while active char has changed

### ISSUE THREAD

**Issue by michabbb** [DestinyItemManager/DIM#5100] opened 2020-04-07 19:16 UTC
I noticed a problem since a while and I wasn't sure, it's a bug, but now I guess, it is.

to reproduce this:

- in game: choose some char
- open DIM 
- don't know if that has something to do with - it: transfer new weapons to char (primary, secondary and heavy)
- while DIM is still open: change char in game 
- press reload button inside DIM 

result: the char banner on top changes to new active char, but all weapons stay in place. only a complete reload of DIM show the correct weapons of the current active char. 

game: xbox 
browser: latest stable chrome (Android) 

thanks

**Comment by delphiactual** [comment] 2020-04-07 22:00
What is your character sort?

**Comment by michabbb** [comment] 2020-04-07 22:04
last active char

**Comment by michabbb** [comment] 2020-04-08 18:26
i don´t notice this problem on desktop (chrome/windows 10)

**Comment by bhollis** [comment] 2020-04-12 04:16
Looks like this is a problem with our ViewPager component (a third party thing). We update the current character ID and set it as `currentView`, but it doesn't select the right one - instead, the order of views is changed and it sticks with the "first entry" rather than the one with the key we select.

**Comment by bhollis** [comment] 2020-04-12 04:18
Looks like react-view-pager is deprecated... guess it's finally time for me to write my own.

**Comment by duckmanBR** [comment] 2020-06-17 12:26
This happened to me yesterday (started playing with the other chars to get twisted energy).

The error is Minified React error #185 and points to the url https://reactjs.org/docs/error-decoder.html/?invariant=185

**Comment by bhollis** [comment] 2020-09-19 04:44
Closing as dupe of #5109

**Closed by bhollis** 2020-09-19 04:44 UTC
Labels: Bug
