### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by wickedadair** [DestinyItemManager/DIM#3234] opened 2018-10-16 03:50 UTC
After I updated DIM I received the following message. Please see attachment. 

![error](https://user-images.githubusercontent.com/44184100/46991020-03303280-d0d2-11e8-84aa-c8536c6c3053.png)

**Comment by bhollis** [comment] 2018-10-16 05:00
Duplicate of #3232

**Closed by bhollis** 2018-10-16 05:00 UTC
