### ISSUE TITLE
Make Wishlisting Easier

### ISSUE THREAD

**Issue by RomaBureacov** [DestinyItemManager/DIM#10695] opened 2024-08-25 08:15 UTC
### Proposed change

Be able to open up armory and have an additional button to append an item to a personal wishlist.

Although I am not too familiar with how DIM is actually setup, I was imagining some sort of user file that is blank by default and we could possibly append wishlist items by having a button in the Armory that appends items to that text file, instead of only being able to copy the roll as a DIM wishlist item. The current implementation of wishlists feels very obtuse and unwieldy.

### How does this fit into your workflow?

1. Inspect weapon rolls on a weapon in my inventory through the armory
2. Choose perks of interest
3. Click on a button that appends the current perk selection to the personal wishlist

This way, instead of having to mess around with copy-pasting individual weapon rolls into a text file and then throwing that somehow into DIM, you can simply append it to a personal wishlist file without hassle.

![image](https://github.com/user-attachments/assets/086fa657-a599-4d10-a52e-5ad47435d8ee)

**Comment by bhollis** [comment] 2024-08-26 02:53
Yep that's the plan. Duplicate of #10313.

**Closed by bhollis** 2024-08-26 02:53 UTC
Labels: Enhancement, Feature: Wish List, Feature: Armory

**Comment by RomaBureacov** [comment] 2024-08-26 02:55
alright good to know it's planned at least 👍
