### ISSUE TITLE
DIM Fails to Update UI when Successfully Transferring an Item

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#3220] opened 2018-10-15 02:15 UTC
Has anyone else seen a behavior where DIM is successfully moving an item in game, but the UI doesn't update?
I've been moving items tonight, cleaning out my vault, and I can hear the game chime when an item is moved, but DIM from time to time, doesn't reflect the change.  In fact, I feel like I've seen an item move to the destination, and then move back.
It's been happening for a few weeks...
I wonder if there is some sort of byproduct of the faster refresh that is out-of-date, and it triggers, with the stale data, pulling the item back.

**Comment by wein3967** [comment] 2018-10-15 02:44
I've seen this from time to time. Pretty rare, and not often enough for me be able to reproduce it on demand.

**Comment by philkernick** [comment] 2018-10-15 14:10
I've seen it a few times recently.

**Comment by philkernick** [comment] 2018-10-16 00:45
I also see it sometimes "rubber band" and item, when transferring through the vault.  In the UI, the item transfers to the vault, then springs back to it's original location.  However the transfer really happened, so trying to move it again generates the red "this item isn't here" warning, and manually refreshing shows it where it was transferred to.

Feels like a race condition between transferring (especially when the API is slow) and refreshing the UI.  Perhaps we should avoid automatic refresh during a sequence of moves.

**Comment by bhollis** [comment] 2018-10-16 01:08
We do already prevent refreshing while we are moving.

**Comment by SunburnedGoose** [comment] 2018-10-17 01:14
Just happened again.  There was a refresh, then the transfer.  They were 1s apart.
![screen shot 2018-10-16 at 8 14 31 pm](https://user-images.githubusercontent.com/984608/47056040-21ed0280-d180-11e8-8831-95d6994ab086.png)
![screen shot 2018-10-16 at 8 14 24 pm](https://user-images.githubusercontent.com/984608/47056041-21ed0280-d180-11e8-8282-6b9f52988b09.png)

**Comment by SunburnedGoose** [comment] 2018-10-17 02:37
Happene
![screen shot 2018-10-16 at 9 37 30 pm](https://user-images.githubusercontent.com/984608/47058681-ba3cb480-d18b-11e8-91ed-9f8e0b69710d.png)
d again.

**Comment by bhollis** [comment] 2018-10-20 02:46
@SunburnedGoose this can happen if there's an error in the `updateItemModel` function so we don't actually apply the state. Did you see any errors in the console?

Otherwise, we should update redux state for both moves and reloads, and they should not be happening concurrently.

**Comment by bmarshall8** [comment] 2018-10-30 07:29
Hey, guys.  I'm just a user (not a developer), but this happens all the time for me.  I frequently see it happen when I'm playing in-game, and something goes to the postmaster.  I click "Refresh Destiny Data", and the new item won't appear.  I can click re-fresh 10 times, and nothing happens.  but, if I transfer something back/forth, then the the automatic refresh after item transfer will notice the new item in the postmaster.  I'm fairly sure I can duplicate it (since it happens so often).  Thank you for considering feedback.  Take care.

**Comment by duckmanBR** [comment] 2018-10-30 12:36
@bmarshall8 that's different from OP...
Your problem (if I'm not mistaken) is with the API.  Sometimes it only return changes when you move items.

**Comment by bhollis** [comment] 2018-11-14 05:39
Are folks still seeing this? I haven't been able to reproduce it.

**Comment by duckmanBR** [comment] 2018-11-14 12:01
Yeah, happened to me yesterday (mobile, so no debug).  Was transferring some armor.  
Transferred 2 helmets.  Both gone.  
Did a chest. Gone, both helmets were "back".
Ignored and transferred a leg. The leg and both helmets gone.
Did another leg. They're back.
Tried to transfer them, but there was no popup.  DIM was still working because all the other items were showing the popup properly.  Only those 2 weren't.

**Comment by bhollis** [comment] 2018-11-14 16:33
I assume you’re moving via the item popup?

**Comment by bhollis** [comment] 2018-11-18 05:14
Can anyone help me come up with a solid repro for this? Detailed instructions, browser/platform, etc?

**Comment by philkernick** [comment] 2018-11-20 03:48
Is there some way to link this to #2926 ?  Being able to turn on at least event debugging would hopefully make it easier to determine the root cause.

**Comment by bhollis** [comment] 2018-11-20 04:10
We already log all item moves to the console

**Comment by bhollis** [comment] 2018-12-31 05:44
Still can't reproduce this, and I haven't seen this. Are people seeing it still?

**Comment by bhollis** [comment] 2019-01-01 20:32
No additional info on how to reproduce it?

**Comment by duckmanBR** [comment] 2019-01-02 13:30
AFAIK if you try to move an item when a refresh is happening DIM will move the item but when the refresh ends it will draw it in the place of origin.
Why "draw": If you try to move it again an message of item not found will pop up.  If you manually refresh the item will appear in the right place.

**Comment by philkernick** [comment] 2019-01-02 15:08
Ok.  Based on this I can now reliably reproduce it.

Click on an item on a character to bring up its properties.
Put your mouse over the vault button (but don't click).
Press r to do manual refresh.
While the refresh is happening click on the vault button.

Visually you will see the item transfer to the vault, and then spring back onto the character.
It isn't really there.
Refresh again to see it really is in the vault.

**Closed** 2019-03-30 22:43 UTC
Labels: Bug, Feature: Item Movement
