### ISSUE TITLE
Subclass, fragments, and aspects missing from links

### ISSUE THREAD

**Issue by HundleBun** [DestinyItemManager/DIM#7955] opened 2022-02-24 21:22 UTC
### DIM Version

Version 7.6.0 and Version 7.6.0.1001353 (beta)

### Browser Details

Edge 98.0.1108.56 and Chrome 98.0.4758.102

### OS Details

Windows 10 and 11 and Android 11

### Describe the bug

Anytime I share a build via DIM link or use someone else's DIM link for a build, the subclass and all it's associated pieces are dropped from the build. This includes using my own shared build link, often the exotic that is selected in a build is also dropped when opening the link. (I have verified that I own the exotics used in the build link)

### Logs

```shell
[app] DIM v7.6.0 (release) - Please report any errors to https://www.github.com/DestinyItemManager/DIM/issues
instrument.ts:125 Language Detected: en-us
instrument.ts:125 Language Assigned: en
instrument.ts:125 [dim sync] globalSettings

Object
Tracking Prevention blocked access to storage for <URL>.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets.js.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets.js.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets/widget_iframe.a58e82e150afc25eb5372dd55a98b778.html?origin=https%3A%2F%2Fapp.destinyitemmanager.com.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets/widget_iframe.a58e82e150afc25eb5372dd55a98b778.html?origin=https%3A%2F%2Fapp.destinyitemmanager.com.
optimizer:1 
Tracking Prevention blocked access to storage for https://syndication.twitter.com/settings?session_id=5028ee0111202e3495b94a573cec007d3108e608.
optimizer:1 
Tracking Prevention blocked access to storage for https://syndication.twitter.com/settings?session_id=5028ee0111202e3495b94a573cec007d3108e608.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets/widget_iframe.a58e82e150afc25eb5372dd55a98b778.html?origin=https%3A%2F%2Fapp.destinyitemmanager.com.
optimizer:1 
Tracking Prevention blocked access to storage for https://platform.twitter.com/widgets/widget_iframe.a58e82e150afc25eb5372dd55a98b778.html?origin=https%3A%2F%2Fapp.destinyitemmanager.com.
log.ts:58 Load manifest: 1378.782958984375 ms
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[114960131]
DestinyObjectiveDefinition[114960131]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[55815981]
DestinyObjectiveDefinition[55815981]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[135682758]
DestinyObjectiveDefinition[135682758]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[33967121]
DestinyObjectiveDefinition[33967121]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[557968429]
DestinyObjectiveDefinition[557968429]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[36795045]
DestinyObjectiveDefinition[36795045]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[139630754]
DestinyObjectiveDefinition[139630754]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[781144468]
DestinyObjectiveDefinition[781144468]
log.ts:34 [hashLookupFailure] DestinyObjectiveDefinition[5982754]
DestinyObjectiveDefinition[5982754]
instrument.ts:125 [dim sync] Saving profile data to IDB
log.ts:58 Process inventory: 106.5517578125 ms
log.ts:58 Inventory state update: 179.69287109375 ms
optimizer:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
​ [loadout optimizer] Processing 0 combinations from 27 items [object Object]
instrument.ts:125 [loadout optimizer] useProcess: worker time 92.30000001192093ms
instrument.ts:125 [loadout optimizer] useProcess 109.30000001192093ms
instrument.ts:125 [dim sync] Saving profile data to IDB
log.ts:58 prepareUpdateQueue: 0.359130859375 ms
instrument.ts:125 [flushUpdates] Flushing queue of 1 updates
instrument.ts:125 [flushUpdates] got results 
instrument.ts:125 [dim sync] Saving profile data to IDB
```

**Comment by bhollis** [comment] 2022-02-25 05:22
Duplicate of https://github.com/DestinyItemManager/DIM/issues/7592, fixed in #7929

**Closed** 2022-02-28 20:31 UTC
Labels: Bug
