### ISSUE TITLE
Mod element swapper

### ISSUE THREAD

**Issue by rhaydock** [DestinyItemManager/DIM#9772] opened 2023-08-25 19:06 UTC
### Proposed change

A function which swaps all instances in your equipped loadout of an <element> mod (e.g. solar targeting) with one of another element. 

### How does this fit into your workflow?

I frequently save multiple loadouts for PvP with combinations of targeting, unflinching, holster etc. mods for different elements (stasis/void, strand/solar). Although it works perfectly, I end up with a large number of loadouts per subclass so I can quickly swap from voidwalker to dawnblade with the fleibility of weapon elements too. Having an option to simply save a generic loadout per subclass with one set of element-based mods, and quickly swap these out for an alternative element would be a huge time saver!

**Comment by bhollis** [comment] 2023-08-25 19:08
Possibly a duplicate of https://github.com/DestinyItemManager/DIM/issues/8995?

**Comment by rhaydock** [comment] 2023-08-25 20:09
For completeness, discussion continued in Discord [here](https://discord.com/channels/316217202766512130/1144709558451839088).

Whilst not intended to be a duplicate of #8995 the solution to that issue would likely meet the primary intention for my suggestion whilst requiring fewer alterations to the frontend.

**Comment by bhollis** [comment] 2023-11-08 08:07
Closing as the conclusion of those discussions got recorded in https://github.com/DestinyItemManager/DIM/issues/8995

**Closed by bhollis** 2023-11-08 08:07 UTC
Labels: Enhancement
