### ISSUE TITLE
Expanding the "randomize loadout" feature

### ISSUE THREAD

**Issue by justintricate** [DestinyItemManager/DIM#9358] opened 2023-04-03 17:52 UTC
### Proposed change

Inspired by Frostbolt's recent YouTube video, it'd be nice if the loadout randomizer could have some rules applied to it. Eg "disallow sunset weapons" for things like trials, or "require at least 1 primary weapon"

### How does this fit into your workflow?

This change would be aimed at content creators, for challenges on stream, or YouTube videos. Could also be fun just for weekend trials with your own gang, a la the old league of legends "ultimate bravery" challenge

**Comment by justintricate** [comment] 2023-04-03 17:54
![Screenshot_20230403-125014](https://user-images.githubusercontent.com/47122570/229588378-bafd7598-4f1d-4461-9075-922c19e3e83a.png)

I believe this would be a great place to put some knobs that allow tweaking the randomize rules. I'd be happy to work on this if it's deemed A-OK by the DIM team. Could include things like "only void weapons" or the ability to exclude certain weapons/types of weapons, down the line

**Comment by robojumper** [comment] 2023-04-03 21:57
Duplicate of #9000?

**Comment by bhollis** [comment] 2023-04-05 04:57
Also, check out the user guide for this feature: https://github.com/DestinyItemManager/DIM/wiki/Randomize-Loadout - you can already quite comprehensively choose what gets randomized.

**Closed by bhollis** 2023-04-05 04:57 UTC
Labels: Enhancement

**Comment by justintricate** [comment] 2023-04-05 05:15
I wonder if it'd be worth more prominent documentation on this feature, somewhere on the tool itself? I have a sneaking suspicion the github wiki isn't going to be read by many, unfortunately.

**Comment by justintricate** [comment] 2023-04-05 05:17
@bhollis beat me to the punch, good call :)

https://github.com/DestinyItemManager/DIM/pull/9362 addresses this, thanks Ben!

**Comment by bhollis** [comment] 2023-04-05 14:37
There are lots of links to the user guide all over the app but yeah, nobody reads it.
