### ISSUE TITLE
DIM beta won't load the "Loadouts" screen on iOS

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#9188] opened 2023-03-05 22:05 UTC
When clicking Loadouts in the menu of DIM beta (saved as a web app; I haven't tried it in Safari) it says "Loading DIM code…" and it never stops. 

This does work on the AppStore DIM fine. 

This has been happening for a few months. 

DIM beta and iOS are update to the latest versions.

**Comment by mannyrye** [comment] 2023-03-05 22:09
It doesn't work in Safari either.

**Comment by bhollis** [comment] 2023-03-06 18:21
Hmm, I can't reproduce on desktop Safari. I saw it once on iOS safari but a reload fixed it and I haven't seen it.

**Comment by liminalAce** [comment] 2023-03-06 22:29
Someone on discord already recently mentioned this, it ended up being a content blocker thing adGuardPro

**Comment by mannyrye** [comment] 2023-03-06 23:00
It is indeed my adblocker. 

Do you know the address of the site I have to whitelist?

Thanks

**Comment by delphiactual** [comment] 2023-03-06 23:19
*.bungie.net

**Comment by bhollis** [comment] 2023-03-07 00:50
In this case it'd be *.destinyitemmanager.com

**Comment by bhollis** [comment] 2023-03-08 00:59
I don't really get why an adblocker would be blocking this though. It should be coming from the service worker, and it's clearly part of the app.

**Comment by bhollis** [comment] 2023-04-13 02:30
Probably a dupe of #9308

**Closed by bhollis** 2023-04-13 02:30 UTC
