### ISSUE TITLE
Multiple custom totals

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#8873] opened 2022-12-18 03:06 UTC
### Proposed change

Instead of just one per class, allow two/tree (or more) custom totals (for every class).

### How does this fit into your workflow?

I have different needs for specific purposes. For example, the stats I want to maximize for PVE is different than for PVP.

**Comment by Revadike** [comment] 2022-12-18 03:07
Or perhaps, allow us to edit the total formula on-the-fly.

**Comment by nev-r** [comment] 2022-12-19 06:24
someday yes

**Comment by bhollis** [comment] 2022-12-24 00:04
Duplicate of #7973

**Closed by bhollis** 2022-12-24 00:04 UTC
Labels: Enhancement
