### ISSUE TITLE
Organizer not showing reaquireable for Exotics 

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [DestinyItemManager/DIM#5575] opened 2020-08-11 18:38 UTC
**What version of DIM are you using?**
6.24.0 Orange 

**What Browser and OS are you using?**
Chrome Android

**Describe the bug and how to make it happen**
I filtered by warlock helmet and the reaquireable column has no check for exotic items. But you can get them from collection.

**Comment by delphiactual** [comment] 2020-08-11 19:38
That roll?

**Comment by bhollis** [comment] 2020-08-12 06:29
Duplicate of #4568

**Closed** 2020-08-12 06:29 UTC
Labels: Bug
