### ISSUE TITLE
Item Leveling doesn't offer to transfer motes from other characters

### ISSUE THREAD

**Issue by floatingatoll** [DestinyItemManager/DIM#1435] opened 2017-01-28 19:26 UTC
I switched from my Hunter to my Titan to continue leveling gear, but ended up without any motes on the Titan because I'd left them behind on the Hunter. It would be swell if Item Leveling offered to gather all my motes to the Titan for leveling.

**Comment by bhollis** [comment] 2017-01-29 00:06
Marking as a duplicate of #1435.

**Closed by bhollis** 2017-01-29 00:06 UTC
