### ISSUE TITLE
Notify users they need to update Chrome if less than v50

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#690] opened 2016-07-10 07:06 UTC
Apparently our changes to the icon have broken DIM for users that have 'marginally' old versions of Chrome.

http://puu.sh/pWrTb/877176ad77.png

Can we notify them that they need to upgrade to latest to make DIM look normal?

**Comment by bhollis** [comment] 2016-07-10 16:41
Duplicate of #676.

**Closed by bhollis** 2016-07-10 16:41 UTC
