### ISSUE TITLE
[Add Feature] Group Items

### ISSUE THREAD

**Issue by assasinitachi123** [DestinyItemManager/DIM#8729] opened 2022-09-25 21:12 UTC
Right now, there is only option for sorting. But need another way to group them as well.
i.e., giving a bit of gap/padding when using groups. Right now, they seem very cluttered.

Ex: Let's say I want all my Auto-rifles (Kinetic/Energy at their respective lanes) at same place together) I do that using the Sort type, but there is no separation/gap after the last auto-rifle. This would make it look cleaner. Also Sorting and Grouping works well together.

**Comment by robojumper** [comment] 2022-09-25 22:02
Duplicate of #3613, also see #7206.

**Closed by robojumper** 2022-09-25 22:02 UTC
