### ISSUE TITLE
ghost dupe by perk, not name

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#2482] opened 2017-12-14 16:21 UTC
The 'is:dupe' should consider each Ghost's perks, not names, when detecting duplicates. DIM obviously knows the perks, so it'd be great if the is:dupe flag worked differently on ghosts. (Or if there was another different flag to use, if that's too complicated.)

re this reddit post: https://redd.it/7bg8x9

**Comment by kyleshay** [comment] 2018-11-09 07:48
duplicate of #3255

**Closed by kyleshay** 2018-11-09 07:48 UTC
Labels: Enhancement, Feature: Search, Help Wanted: Developer
