### ISSUE TITLE
Item Auditor? List what ones you have, and don't have. 

### ISSUE THREAD

**Issue by pricelessbrewing** [DestinyItemManager/DIM#2529] opened 2018-01-06 23:51 UTC
Auto - generate a list of exotics you don't have seems useful, or say you want to check that you have all auto rifles, or hand cannons etc.

**Comment by bhollis** [comment] 2018-01-07 01:34
Check out destinysets.com!

-Ben

**Comment by bhollis** [comment] 2018-01-15 04:26
Closing as a duplicate of #2363

**Closed by bhollis** 2018-01-15 04:26 UTC
