### ISSUE TITLE
Search input value disappears when resizing from widescreen to mobile layout and back

### ISSUE THREAD

**Issue by nwLSteam** [DestinyItemManager/DIM#8612] opened 2022-08-02 13:22 UTC
### DIM Version

Version 7.28.0.1001899 (beta), built on 1.8.2022, 05:39:18

### Browser Details

Microsoft Edge Version 103.0.1264.77 (64 bit)

### OS Details

Windows 10

### Bug reproduction
1. Search for something while on desktop.
![Search for something while on desktop](https://user-images.githubusercontent.com/25863799/182383430-70323e56-57b2-46f5-b770-9f19d94ca27a.png)
2. Resize the window so DIM switches to mobile view.
![Resize the window so DIM switches to mobile view](https://user-images.githubusercontent.com/25863799/182383573-cf563852-90fe-4326-ab8b-4ca50f8e0a69.png)
3. Resize the window back to desktop view. Search value has disappeared but search results are still correct.
![Resize the window back to desktop view](https://user-images.githubusercontent.com/25863799/182384058-51987690-c478-48ac-856f-66bbbc089ce8.png)

### Bug description
- Expected: Search value reappears when resizing back to desktop.
- Actual: Search value does not reappear.

### Logs

```shell
// there are no other logs except for the following warnings by Edge itself:

[Violation]Forced reflow while executing JavaScript took 152ms
[Violation]Forced reflow while executing JavaScript took 148ms
[Violation]Forced reflow while executing JavaScript took 58ms
[Violation]Forced reflow while executing JavaScript took 63ms
[Violation]Forced reflow while executing JavaScript took 75ms
[Violation]Forced reflow while executing JavaScript took 131ms
218-8c7f0542.js:2 [Violation]'change' handler took 527ms
218-8c7f0542.js:2 [Violation]'change' handler took 462ms
```

**Comment by bhollis** [comment] 2022-08-08 04:20
My fix for this in #8621 made it so you couldn't edit a filter from the middle.

**Comment by liamdebeasi** [comment] 2024-06-05 01:55
Are you still able to reproduce this issue? I am testing with Edge 125 on Windows 11, and I cannot reproduce the reported behavior.


https://github.com/DestinyItemManager/DIM/assets/2721089/762edd60-f1c9-4b14-9b3d-e5692726f656

**Comment by bhollis** [comment] 2024-06-05 06:00
Huh, I'm not. I wonder when it was fixed.

**Closed** 2024-06-12 19:14 UTC
Labels: Bug, Feature: Search
