### ISSUE TITLE
Loadouts disappearing.  

### ISSUE THREAD

**Issue by TerraReef** [DestinyItemManager/DIM#1470] opened 2017-02-12 17:13 UTC
I have spoken with three people who are all ready to leave DIM.  Loadouts are now being lost on a regular basis.  I suspect it may be happening when a user refreshes google chrome in Windows 10 while DIM is trying to do something else, but this may not be the case.  Often 3-4 loadouts disappear at a time.  I spoke with one user who lost everyone of his loadouts.

**Comment by SunburnedGoose** [comment] 2017-02-12 17:14
Duplicate of #1400

**Closed by SunburnedGoose** 2017-02-12 17:14 UTC
