### ISSUE TITLE
Dialogs stop opening when an error is thrown.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#483] opened 2016-04-17 02:35 UTC
https://www.reddit.com/r/DestinyItemManager/comments/4f4no3/353_is_not_usable_getting_an_error_that_disables/

Users are getting errors in the app when interacting with the dialogs.

![image](https://cloud.githubusercontent.com/assets/984608/14584748/fddd8bb0-041a-11e6-8401-b41dfc81d537.png)

This seems like a new error that has appeared since the April update code went out.

**Comment by bhollis** [comment] 2016-04-17 05:49
That sucks, I thought I fixed it in 9a6a4eab227b42bfe1b314d99e5f9c0caf5eee25.

**Comment by bhollis** [comment] 2016-04-17 07:35
Looks like I fixed one but boat all of the causes. More fixes incoming.

**Closed** 2016-04-17 17:19 UTC
Labels: bug
