### ISSUE TITLE
Vault Organizer stat values aren't aligned with stat icon

### ISSUE THREAD

**Issue by tedcarstensen** [DestinyItemManager/DIM#6732] opened 2021-05-07 05:51 UTC
**What version of DIM are you using?**
Version 6.63.0.1000441 (beta), built on 5/4/2021, 5:52:53 PM

**What Browser and OS are you using?**
Safari 14.1 on macOS 11.3.1

**Describe the bug and how to make it happen**
This could be a result of a large-ish (15" MBP) screen + most columns turned off, but the stat values aren't aligning with the stat header icon, making it hard to track and organize.

Turning the `text-align: right !important;` css rule **off** fixes this issue for me.

![organizer-align-right](https://user-images.githubusercontent.com/1002132/117353175-aac60980-ae64-11eb-8fd4-9fd7299191bb.png)

**Comment by bhollis** [comment] 2021-05-07 15:40
Hmm, these columns aren't supposed to expand. That's the issue that should be fixed.

**Comment by alexcnichols** [comment] 2021-07-14 18:26
Looked at this a bit. I am able to reproduce simply by disabling the "Notes" column within Organizer. 

That column seems to have a special `minmax(200px, 1fr)` width, which would effectively allow it to consume the available space, since all the other columns are `min-content` width. 

https://github.com/DestinyItemManager/DIM/blob/cf4f4cd479e49c05ab180c279cd3f5c96bd1bb12/src/app/organizer/Columns.tsx#L494-L501

https://user-images.githubusercontent.com/19493383/125671215-0d119064-67d4-4e94-bf45-a99442dd215d.mp4

#### Workaround

Make sure the "Notes" column is enabled in Organizer

#### Potential fixes

- Make sure Notes is always enabled in Organizer
- Center align the Stats column (and Base Stats column) (which might break things elsewhere)
- Otherwise address the column width expansion so that at least one column can expand to fill. Icon seems to be the only other required column

**Closed** 2022-03-16 04:05 UTC
Labels: Bug, Good First Issue, Feature: Vault Organizer
