### ISSUE TITLE
Tags in vault not appearing until restore

### ISSUE THREAD

**Issue by greggtavares** [DestinyItemManager/DIM#2416] opened 2017-11-10 18:13 UTC
I'm having a concern where the tags for my items in my vault do not appear until I perform a restore. The google drive data doesn't match either even after a forced sync I see the data numbers matching but even after a forced sync the data numbers match but no tags appear.

**Comment by bhollis** [comment] 2017-11-12 03:17
I think this is a duplicate of #2195 - occasionally the vault doesn't load, and this wipes out your tags. We haven't caught it in action in order to devise a good fix yet.

**Comment by greggtavares** [comment] 2017-11-13 16:03
If it happens to me again what do you want me to capture? My history is set to remember all and cookies are enabled. Do you need a screenshot of something? Let me know. I’d love to help if I can.

**Closed** 2018-03-04 23:42 UTC
Labels: Bug, Infrastructure: Sync
