### ISSUE TITLE
DIM Inventory page overlapping

### ISSUE THREAD

**Issue by D2XBOX** [DestinyItemManager/DIM#4611] opened 2019-10-28 23:15 UTC
Hello,

At the top of the inventory page the info for the vault tab "vault space used / total vault space" and other fields / values are overlapping and are not legible. Windows 10 / Edge machine. Checked Alpha and Beta pages, same result. The information is there, just seems to be a formatting issue.

Thank you for your attention

**Comment by bhollis** [comment] 2019-10-29 02:12
Can you attach a screenshot?

**Comment by wiseman-tex** [comment] 2019-10-31 02:10
@bhollis.  I opened a second ticket on this same issue (didn't see this one), see #4623 a screenshot is attached.

**Comment by bhollis** [comment] 2019-11-01 01:23
Duplicate of #4623 (which has more detail)

**Closed by bhollis** 2019-11-01 01:23 UTC
