### ISSUE TITLE
Item comparison can’t sidescroll on mobile

### ISSUE THREAD

**Issue by tcurtin** [DestinyItemManager/DIM#4556] opened 2019-10-23 17:13 UTC
Any time I try to run a comparison and the list of items is more than one screen wide, scrolling side to side on mobile works rarely and seemingly randomly.  If I repeatedly try dragging in various spots within the items being compared once in a while it **will** scroll, but I can’t make it happen twice in a row, and I haven’t found any consistency to when or where it does work.  iPad/iPhone, Beta/release, landscape/portrait, nothing I change seems to matter.

I’m guessing this is a tricky bug, but just in case, is there something I’m missing?

iPhone XS iOS 13.1.2, iPad Pro iOS 12.4.1

**Comment by bhollis** [comment] 2019-10-23 20:53
Dupe of #3424, seems to be an iOS Safari bug.

This will get replaced in #4377.

**Closed by bhollis** 2019-10-23 20:53 UTC
