### ISSUE TITLE
"is:purple" or other, similar commands should exclude items from being considered by commands like "maxstatvalue:any"

### ISSUE THREAD

**Issue by NevanNedall** [DestinyItemManager/DIM#5327] opened 2020-06-15 20:15 UTC
At the moment, if you perform a search for "is:purple is:maxpower" or "is:purple maxstatvalue:any", DIM will first find each item that has the max of a given state, then will exclude anything that is not a purple, which means it could fail to show results entirely, in some circumstances, or show less than it would if those exotics/blues/etc simply weren't there.

I feel this behavior is unintuitive to a user, and more importantly, limiting in terms of finding the gear you're looking for.

Instead, I feel like any command that excludes one or more categories should be applied before searching for things like max stats, max power, and anything else that is exclusive to a single item in most cases.

**Comment by bhollis** [comment] 2020-06-15 23:47
Duplicate of https://github.com/DestinyItemManager/DIM/issues/4658

**Closed by bhollis** 2020-06-15 23:47 UTC
