### ISSUE TITLE
Let users choose perks in Loadouts

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#767] opened 2016-08-08 19:04 UTC
We cannot change perks for items using the API.  What we can do is let users choose perks in their loadouts, and when they apply the loadout, we can notify them in the toaster if their loadout items don't match the perks they selected.  

I think of it as my PVE and PVP loadouts.  I so often forget that I need to change the subclass when moving between gametypes.

The user can click on a link in the toaster that will show them the items that differ, and which perks need to be changed in a new popup view.

**Comment by bhollis** [comment] 2016-08-09 04:09
Duplicate of #720?

**Closed** 2016-08-09 08:29 UTC
Labels: duplicate, enhancement, help wanted
