### ISSUE TITLE
No roll percent and light level on Vendors

### ISSUE THREAD

**Issue by Anakros** [DestinyItemManager/DIM#1088] opened 2016-10-27 12:50 UTC
Vendors API just got up, but there is no roll percents and light levels

And something wrong with armsday orders (all tuonela/thesan rolls are identical and there is just one jlb-47, dis-43 and dis-47)
<img width="537" alt="screen shot 2016-10-27 at 19 48 07" src="https://cloud.githubusercontent.com/assets/1309035/19767733/650e5a02-9c7e-11e6-90c5-33c015fe5d4d.png">
<img width="548" alt="screen shot 2016-10-27 at 19 48 45" src="https://cloud.githubusercontent.com/assets/1309035/19767734/6511bf3a-9c7e-11e6-80ee-b461556c71ba.png">

I'm using the latest beta version, 3.11.1.510

**Comment by SunburnedGoose** [comment] 2016-10-27 14:52
The stat quality on Vendor armors is an important feature of the Vendor page.

**Comment by bhollis** [comment] 2016-10-27 15:42
Looks like Bungie put back the vendors info, but without any stats. Makes
sense as they said stats were the cause of the performance problems.
Hopefully the stats will come back soon.

**Comment by SunburnedGoose** [comment] 2016-10-27 16:03
Stats and Perks are in the item object.  I'll look at it.

**Comment by delphiactual** [comment] 2016-10-29 02:46
Light level for vendors is at .stats[3897883278]

**Comment by bhollis** [comment] 2016-10-29 05:05
Good find!

**Comment by delphiactual** [comment] 2016-10-29 07:25
https://github.com/DestinyItemManager/DIM/pull/1098

**Comment by bhollis** [comment] 2016-11-05 20:05
Closing since we'll hopefully get stats back on 11/8 when Bungie does their next API deployment.

**Closed by bhollis** 2016-11-05 20:05 UTC
Labels: bug
