### ISSUE TITLE
Calculation of Destiny 2 armor Base Stats incorrectly includes disabled Armor Mods

### ISSUE THREAD

**Issue by darkthing41** [DestinyItemManager/DIM#6459] opened 2021-01-22 16:50 UTC
**What version of DIM are you using?**
Version 6.48.0 (release), built on 18/01/2021, 02:47:29
Orange DIM icon.

**What Browser and OS are you using?**
Firefox 84.0.2 (64-bit)

**Describe the bug and how to make it happen**
Calculation of base stats incorrectly includes Armor Mods that are disabled.
![Capture](https://user-images.githubusercontent.com/17741825/105518615-6b6a1780-5cd0-11eb-88e3-5c23dbdd2d41.PNG)
This armour has 7 Resilence and 62 total base stats; the Armor Mods are disabled and do not affect the stats.
It is calculated as -3 Resilience and 52 total base stats. (Affects the web application and .csv export.)
In this case the Armor Mods were disabled upon the release of Beyond Light, which increased the energy costs.

**Comment by ryan-rushton** [comment] 2021-01-22 20:26
I wonder if there is anything from the API data on those items/mods to indicate that they are disabled? I will have a dig through my gear to see if I have anything that is disabled too.

**Comment by darkthing41** [comment] 2021-01-22 20:36
Those mods are greyed out, so I think DIM has noticed that they are disabled.

**Comment by darkthing41** [comment] 2021-01-25 13:40
I think this change was included in version 6.49, but the issue still exists for me. (Version 6.49.0 (release), built on 25/01/2021, 02:52:03)

From a quick look at the surrounding code, I think that the change to "enhanceStatsWithPlugs" probably only addressed disabled weapon mods.
Function "buildStats" looks to me like it overwrites the result ("investmentStats") in a couple of places if it later decides that the item in question is armor (distinguishing between class items / other armor).
https://github.com/DestinyItemManager/DIM/blob/2f66db513995de04f361d336956cd4f2999755bd/src/app/inventory/store/stats.ts#L100

I could be wrong; it's not my codebase and not my language.

**Comment by ryan-rushton** [comment] 2021-01-25 22:20
That is correct we recalculate the investment stats as we need to use the stats that belong to each item instance rather than the ones from the definitions.

Those mod stats are calculated a few times around the app so it might be happening away from that stats file.

It sounds like you are a bit dev handy, do you think you could install the react dev tools extension for chrome, open the beta site, and get the details from the item used in that popup for me? I can't reproduce so I am basically taking guesses at it.

**Comment by darkthing41** [comment] 2021-01-26 00:32
This is the "item" definition I get with the stat block highlighted in the item popip.
Apologies for the lack of formatting; it seems to be a choice between that or having to manually expand each node in the tree.

```
{"owner":"vault","destinyVersion":2,"location":{"description":"Gloves and gauntlets.","name":"Gauntlets","hash":3551918588,"hasTransferDestination":true,"capacity":10,"accountWide":false,"category":3,"type":"Gauntlets","sort":"Armor","inArmor":true,"vaultBucket":{"description":"Safe storage for general items. Accessible to all your characters.","name":"General","hash":138197802,"hasTransferDestination":false,"capacity":500,"accountWide":true,"category":1,"type":"General"}},"hash":2976484617,"type":"Gauntlets","itemCategoryHashes":[22,46,20],"tier":"Legendary","isExotic":false,"isVendorItem":false,"name":"Notorious Invader Gauntlets","description":"Let them run. You will hunt them where they hide.","icon":"/common/destiny2_content/icons/577468959302b4b20e3f793ddc66f762.jpg","hiddenOverlay":"/common/destiny2_content/icons/f9110e633634d112cff72a67159e3b12.png","iconOverlay":"/common/destiny2_content/icons/e4a1a5aaeb9f65cc5276fd4d86499c70.png","notransfer":false,"canPullFromPostmaster":true,"id":"6917529179277011050","equipped":false,"equipment":true,"complete":false,"amount":1,"primStat":{"statHash":3897883278,"value":1050,"stat":{"displayProperties":{"description":"Reduces incoming damage from your enemies.","name":"Defense","hasIcon":false},"aggregationType":2,"hasComputedBlock":false,"statCategory":3,"interpolate":false,"hash":3897883278,"index":2,"redacted":false,"blacklisted":false}},"typeName":"Gauntlets","equipRequiredLevel":50,"maxStackSize":1,"uniqueStack":false,"classType":0,"classTypeNameLocalized":"Titan","element":{"displayProperties":{"description":"Requires Solar energy.","name":"Solar","icon":"/common/destiny2_content/icons/DestinyEnergyTypeDefinition_2a1773e10968f2d088b97c22b22bba9e.png","hasIcon":true},"transparentIconPath":"/img/destiny_content/damage_types/destiny2/thermal_trans.png","showIcon":true,"enumValue":2,"capacityStatHash":2018193158,"costStatHash":3344745325,"hash":591714140,"index":2,"redacted":false,"blacklisted":false},"energy":{"energyTypeHash":591714140,"energyType":2,"energyCapacity":7,"energyUsed":8,"energyUnused":-1},"powerCap":1060,"lockable":true,"trackable":false,"tracked":false,"locked":true,"masterwork":false,"classified":false,"isEngram":false,"previewVendor":0,"ammoType":0,"missingSockets":false,"displaySource":"Random Perks: This item cannot be reacquired from Collections.","breakerType":null,"percentComplete":0,"hidePercentage":false,"talentGrid":null,"stats":[{"investmentValue":7,"statHash":2996146975,"displayProperties":{"description":"Increases your movement speed and maximum jump height.","name":"Mobility","icon":"/common/destiny2_content/icons/c9aa8439fc71c9ee336ba713535569ad.png","hasIcon":true},"sort":22,"value":7,"base":7,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":7,"statHash":392767087,"displayProperties":{"description":"Increases the amount of damage you can take before dying.","name":"Resilience","icon":"/common/destiny2_content/icons/9f5f65d08b24defb660cebdfd7bae727.png","hasIcon":true},"sort":23,"value":7,"base":-3,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":16,"statHash":1943323491,"displayProperties":{"description":"Increases the speed at which you regain lost health.","name":"Recovery","icon":"/common/destiny2_content/icons/47e16a27c8387243dcf9b5d94e26ccc4.png","hasIcon":true},"sort":24,"value":16,"base":16,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":17,"statHash":1735777505,"displayProperties":{"description":"Discipline decreases the cooldown time of your grenades, allowing you to use them more often.","name":"Discipline","icon":"/common/destiny2_content/icons/ca62128071dc254fe75891211b98b237.png","hasIcon":true},"sort":25,"value":17,"base":17,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":9,"statHash":144602215,"displayProperties":{"description":"Intellect decreases the cooldown of your Super ability, allowing you to use it more often.","name":"Intellect","icon":"/common/destiny2_content/icons/59732534ce7060dba681d1ba84c055a6.png","hasIcon":true},"sort":26,"value":9,"base":9,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":6,"statHash":4244567218,"displayProperties":{"description":"Strength decreases the cooldown time of your melee ability, allowing you to use it more often.","name":"Strength","icon":"/common/destiny2_content/icons/c7eefc8abbaa586eeab79e962a79d6ad.png","hasIcon":true},"sort":27,"value":6,"base":6,"statMayBeWrong":false,"maximumValue":42,"bar":true,"smallerIsBetter":false,"additive":true,"isConditionallyActive":false},{"investmentValue":62,"statHash":-1000,"displayProperties":{"name":"Total"},"sort":28,"value":62,"base":52,"statMayBeWrong":false,"maximumValue":100,"bar":false,"smallerIsBetter":false,"additive":false,"isConditionallyActive":false}],"objectives":null,"pursuit":null,"taggable":true,"comparable":true,"basePower":1050,"index":"6917529179277011050","infusable":true,"infusionFuel":true,"sockets":{"allSockets":[{"socketIndex":0,"plugged":{"plugDef":{"displayProperties":{"description":"","name":"Resilience Mod","icon":"/common/destiny2_content/icons/195f4f173adb52b336b4ecd67101004d.png","iconSequences":[{"frames":["/common/destiny2_content/icons/195f4f173adb52b336b4ecd67101004d.png"]},{"frames":["/common/destiny2_content/icons/7d2a4def8a3cfdbc23da47797d89919c.png"]}],"hasIcon":true},"tooltipNotifications":[],"collectibleHash":3993840158,"backgroundColor":{},"itemTypeDisplayName":"General Armor Mod","uiItemDisplayStyle":"ui_display_style_energy_mod","itemTypeAndTierDisplayName":"Common General Armor Mod","displaySource":"","tooltipStyle":"build","inventory":{"maxStackSize":1,"bucketTypeHash":2422292810,"recoveryBucketTypeHash":0,"tierTypeHash":3340296461,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Common","tierType":2,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"enhancements.v2_general","plugCategoryHash":2487827355,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":1564811296,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":0,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"energyCost":{"energyCost":3,"energyTypeHash":1198124803,"energyType":0},"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[{"statTypeHash":3578062600,"value":3,"isConditionallyActive":false},{"statTypeHash":392767087,"value":10,"isConditionallyActive":false}],"perks":[{"requirementDisplayString":"","perkHash":833744803,"perkVisibility":0}],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":true,"itemCategoryHashes":[59,4104513227],"specialItemType":0,"itemType":19,"itemSubType":0,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"hash":2850583378,"index":7487,"redacted":false,"blacklisted":false},"enabled":false,"enableFailReasons":"","plugObjectives":[],"perks":[{"displayProperties":{"description":"+10 Resilience ▲","name":"Stat Increase","icon":"/common/destiny2_content/icons/cd042d8338050f8837cd7e90ef1938db.jpg","hasIcon":true},"isDisplayable":true,"damageType":0,"hash":833744803,"index":2583,"redacted":false,"blacklisted":false}],"stats":{"392767087":10,"3578062600":3}},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"isPerk":false,"socketDefinition":{"socketTypeHash":1718047805,"singleInitialItemHash":481675395,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":false,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":5,"reusablePlugSetHash":3559124992,"overridesUiAppearance":false,"defaultVisible":true}},{"socketIndex":1,"plugged":{"plugDef":{"displayProperties":{"description":"","name":"Rocket Launcher Loader","icon":"/common/destiny2_content/icons/776cbdeb79b0e5b002daa1eed3330fe2.png","iconSequences":[{"frames":["/common/destiny2_content/icons/776cbdeb79b0e5b002daa1eed3330fe2.png"]},{"frames":["/common/destiny2_content/icons/aae0b55d07f23c0a84a1e3c98dd987ae.png"]}],"hasIcon":true},"tooltipNotifications":[],"collectibleHash":1073899371,"itemTypeDisplayName":"Arms Armor Mod","uiItemDisplayStyle":"ui_display_style_energy_mod","itemTypeAndTierDisplayName":"Common Arms Armor Mod","displaySource":"","tooltipStyle":"build","inventory":{"maxStackSize":1,"bucketTypeHash":2422292810,"recoveryBucketTypeHash":0,"tierTypeHash":3340296461,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Common","tierType":2,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"enhancements.v2_arms","plugCategoryHash":3422420680,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":1564811296,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":0,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"energyCost":{"energyCost":5,"energyTypeHash":1198124803,"energyType":0},"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[{"statTypeHash":3578062600,"value":5,"isConditionallyActive":false}],"perks":[{"requirementDisplayString":"","perkHash":47235935,"perkVisibility":0}],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":true,"itemCategoryHashes":[59,4104513227,3872696960],"specialItemType":0,"itemType":19,"itemSubType":0,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"hash":2324400338,"index":7547,"redacted":false,"blacklisted":false},"enabled":false,"enableFailReasons":"","plugObjectives":[],"perks":[{"displayProperties":{"description":"Increases reload speed of Rocket Launchers.","name":"Rocket Launcher Loader","icon":"/common/destiny2_content/icons/776cbdeb79b0e5b002daa1eed3330fe2.png","hasIcon":true},"isDisplayable":true,"damageType":0,"hash":47235935,"index":1408,"redacted":false,"blacklisted":false}],"stats":{"3578062600":5}},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"isPerk":false,"socketDefinition":{"socketTypeHash":1108765570,"singleInitialItemHash":1844045567,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":false,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":13,"reusablePlugSetHash":451325587,"overridesUiAppearance":false,"defaultVisible":true}},{"socketIndex":2,"plugged":{"plugDef":{"displayProperties":{"description":"No mod currently selected.","name":"Empty Mod Socket","icon":"/common/destiny2_content/icons/18bb744532b78a20164f150c770c5f89.png","iconSequences":[{"frames":["/common/destiny2_content/icons/18bb744532b78a20164f150c770c5f89.png"]},{"frames":["/common/destiny2_content/icons/30b27caf8a26b3ef54abb49014abf261.png"]}],"hasIcon":true},"tooltipNotifications":[],"itemTypeDisplayName":"Arms Armor Mod","uiItemDisplayStyle":"","itemTypeAndTierDisplayName":"Common Arms Armor Mod","displaySource":"","tooltipStyle":"vendor_action","inventory":{"maxStackSize":1,"bucketTypeHash":2422292810,"recoveryBucketTypeHash":0,"tierTypeHash":3340296461,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Common","tierType":2,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"enhancements.v2_arms","plugCategoryHash":3422420680,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":0,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":0,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[],"perks":[],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":true,"itemCategoryHashes":[59,4104513227,3872696960],"specialItemType":0,"itemType":19,"itemSubType":0,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"hash":1844045567,"index":7528,"redacted":false,"blacklisted":false},"enabled":true,"enableFailReasons":"","plugObjectives":[],"perks":[],"stats":null},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"isPerk":false,"socketDefinition":{"socketTypeHash":1108765570,"singleInitialItemHash":1844045567,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":false,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":13,"reusablePlugSetHash":451325587,"overridesUiAppearance":false,"defaultVisible":true}},{"socketIndex":3,"plugged":{"plugDef":{"displayProperties":{"description":"No mod currently selected.\n\nYou can select Charged with Light mods, Garden of Salvation mods, Nightmare mods, Raid mods, and Warmind Cell mods to use in this socket.","name":"Empty Mod Socket","icon":"/common/destiny2_content/icons/6bf9ba37386b907ddb514ec422fc74c9.png","iconSequences":[{"frames":["/common/destiny2_content/icons/6bf9ba37386b907ddb514ec422fc74c9.png"]},{"frames":["/common/destiny2_content/icons/bffd0026c0e32f7601a39fcdf58c2f27.png"]}],"hasIcon":true},"tooltipNotifications":[],"itemTypeDisplayName":"Legacy Armor Mod","uiItemDisplayStyle":"","itemTypeAndTierDisplayName":"Common Legacy Armor Mod","displaySource":"","tooltipStyle":"vendor_action","inventory":{"maxStackSize":1,"bucketTypeHash":2422292810,"recoveryBucketTypeHash":0,"tierTypeHash":3340296461,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Common","tierType":2,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"enhancements.season_maverick","plugCategoryHash":1081029832,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":0,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":0,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[],"perks":[],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":true,"itemCategoryHashes":[59,4104513227],"specialItemType":0,"itemType":19,"itemSubType":0,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"hash":2620967748,"index":7654,"redacted":false,"blacklisted":false},"enabled":true,"enableFailReasons":"","plugObjectives":[],"perks":[],"stats":null},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"isPerk":false,"socketDefinition":{"socketTypeHash":4127539203,"singleInitialItemHash":2620967748,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":false,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":5,"reusablePlugSetHash":764967870,"overridesUiAppearance":false,"defaultVisible":true}},{"socketIndex":4,"plugged":{"plugDef":{"displayProperties":{"description":"Restores your gear to its default colors.","name":"Default Shader","icon":"/common/destiny2_content/icons/aeacc06cbe147ec400a10225a4dcd504.png","hasIcon":true},"tooltipNotifications":[],"itemTypeDisplayName":"Restore Defaults","uiItemDisplayStyle":"","itemTypeAndTierDisplayName":"Common Restore Defaults","displaySource":"","tooltipStyle":"vendor_action","inventory":{"maxStackSize":1000,"bucketTypeHash":2973005342,"recoveryBucketTypeHash":0,"tierTypeHash":3340296461,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Common","tierType":2,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"shader","plugCategoryHash":2973005342,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":0,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":0,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[],"perks":[],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":false,"itemCategoryHashes":[41,52],"specialItemType":0,"itemType":19,"itemSubType":20,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"traitIds":["item_type.shader"],"hash":4248210736,"index":251,"redacted":false,"blacklisted":false},"enabled":true,"enableFailReasons":"","plugObjectives":[],"perks":[],"stats":null},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"isPerk":false,"socketDefinition":{"socketTypeHash":2321980680,"singleInitialItemHash":3735277403,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":true,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":7,"reusablePlugSetHash":2,"overridesUiAppearance":false,"defaultVisible":true}},{"socketIndex":5,"plugged":{"plugDef":{"displayProperties":{"description":"Upgrade this armor to increase its energy capacity by 1. Fully upgrading this armor to Masterwork provides a bonus to all stats.\n\nThis armor cannot accept mods that require Void or Arc energy.","name":"Upgrade Armor","icon":"/common/destiny2_content/icons/c926fa331c3d658c38c8a22d718936df.jpg","hasIcon":true},"tooltipNotifications":[],"iconWatermark":"/common/destiny2_content/icons/b324e267afe13d9e9e3838fbd24efe2d.png","itemTypeDisplayName":"","uiItemDisplayStyle":"","itemTypeAndTierDisplayName":"","displaySource":"","tooltipStyle":"vendor_action","inventory":{"maxStackSize":1,"bucketTypeHash":3313201758,"recoveryBucketTypeHash":215593132,"tierTypeHash":4008398120,"isInstanceItem":false,"nonTransferrableOriginal":false,"tierTypeName":"Legendary","tierType":5,"expirationTooltip":"","expiredInActivityMessage":"","expiredInOrbitMessage":"","suppressExpirationWhenObjectivesComplete":true},"plug":{"insertionRules":[],"plugCategoryIdentifier":"v460.plugs.armor.masterworks.stat.resistance_3","plugCategoryHash":400813042,"onActionRecreateSelf":false,"actionRewardSiteHash":0,"actionRewardItemOverrideHash":0,"insertionMaterialRequirementHash":3549770948,"previewItemOverrideHash":0,"enabledMaterialRequirementHash":0,"enabledRules":[],"uiPlugLabel":"","plugStyle":0,"plugAvailability":2,"alternateUiPlugLabel":"","alternatePlugStyle":0,"isDummyPlug":false,"energyCapacity":{"capacityValue":7,"energyTypeHash":591714140,"energyType":2},"applyStatsToSocketOwnerItem":false},"acquireRewardSiteHash":0,"acquireUnlockHash":0,"investmentStats":[{"statTypeHash":2018193158,"value":7,"isConditionallyActive":false}],"perks":[],"allowActions":true,"doesPostmasterPullHaveSideEffects":false,"nonTransferrable":false,"itemCategoryHashes":[59],"specialItemType":0,"itemType":19,"itemSubType":0,"classType":3,"breakerType":0,"equippable":false,"defaultDamageType":0,"isWrapper":false,"hash":3020065859,"index":8005,"redacted":false,"blacklisted":false},"enabled":true,"enableFailReasons":"","plugObjectives":[],"perks":[],"stats":{"2018193158":7}},"plugOptions":[null],"curatedRoll":null,"hasRandomizedPlugItems":false,"reusablePlugItems":[{"plugItemHash":3020065868,"canInsert":true,"enabled":true},{"plugItemHash":4048086880,"canInsert":false,"enabled":true,"insertFailIndexes":[0]},{"plugItemHash":3003114972,"canInsert":false,"enabled":true,"insertFailIndexes":[0]},{"plugItemHash":3437002243,"canInsert":false,"enabled":true,"insertFailIndexes":[0]},{"plugItemHash":3652771141,"canInsert":false,"enabled":true,"insertFailIndexes":[0]}],"isPerk":false,"socketDefinition":{"socketTypeHash":1843767421,"singleInitialItemHash":4048086880,"reusablePlugItems":[],"preventInitializationOnVendorPurchase":true,"preventInitializationWhenVersioning":false,"hidePerksInItemTooltip":false,"plugSources":2,"reusablePlugSetHash":736994026,"overridesUiAppearance":false,"defaultVisible":true}}],"categories":[{"category":{"displayProperties":{"description":"The energy type and tier of a piece of armor determines which armor mods you can attach to it. Upgrade its armor tier to increase its capacity for more expensive armor mods.","name":"ARMOR TIER","hasIcon":false},"uiCategoryStyle":750616615,"categoryStyle":5,"hash":760375309,"index":6,"redacted":false,"blacklisted":false},"sockets":[null]},{"category":{"displayProperties":{"description":"Attach a mod to a piece of armor to improve or add to its perks. Doing so consumes the mod.","name":"ARMOR MODS","hasIcon":false},"uiCategoryStyle":1469714392,"categoryStyle":2,"hash":590099826,"index":7,"redacted":false,"blacklisted":false},"sockets":[null,null,null,null]},{"category":{"displayProperties":{"description":"Attach a cosmetic to a piece of armor to customize its appearance.","name":"ARMOR COSMETICS","hasIcon":false},"uiCategoryStyle":1469714392,"categoryStyle":2,"hash":1926152773,"index":8,"redacted":false,"blacklisted":false},"sockets":[null]},{"category":{"displayProperties":{"description":"Perks are built into a given piece of armor. They cannot be swapped out.","name":"ARMOR PERKS","hasIcon":false},"uiCategoryStyle":2251952357,"categoryStyle":6,"hash":3154740035,"index":9,"redacted":false,"blacklisted":false},"sockets":[]}]},"perks":null,"masterworkInfo":{"tier":7,"stats":[{"hash":2018193158,"name":"Solar Energy Capacity","value":7}]},"infusionQuality":{"itemLevels":[],"qualityLevel":0,"infusionCategoryName":"3647016162","infusionCategoryHash":3647016162,"infusionCategoryHashes":[3647016162],"progressionLevelRequirementHash":3768955166,"currentVersion":0,"versions":[{"powerCapHash":1862490584}],"displayVersionWatermarkIcons":["/common/destiny2_content/icons/e4a1a5aaeb9f65cc5276fd4d86499c70.png"]}}
```

**Comment by ryan-rushton** [comment] 2021-02-17 10:12
Hey @darkthing41, can you see if this is now fixes on beta (build number 6.52.0.1000223, find it https://beta.destinyitemmanager.com/about).

**Comment by darkthing41** [comment] 2021-02-18 02:25
The stats now calculate correctly in the beta build. For some reason the UI still shows the "+10" in the total row, but I'll call that a quirk rather than an issue.
![Capture](https://user-images.githubusercontent.com/17741825/108295732-1cf54f00-7190-11eb-8bea-ac1056f00f53.PNG)

**Comment by bhollis** [comment] 2021-02-18 02:27
I'll call it an issue

**Comment by ryan-rushton** [comment] 2021-02-18 03:21
Gah it never ends, I will look into it

**Comment by ryan-rushton** [comment] 2021-02-24 01:54
@darkthing41, another fix has gone in, can you let me know if you are still seeing the issue

**Comment by darkthing41** [comment] 2021-02-24 03:19
I can't see any issues in Version 6.53.0.1000238 (beta), built on 24/02/2021, 02:30:39.
I think you're clear.

**Comment by ryan-rushton** [comment] 2021-02-24 03:21
Awesome, closing this issue then. Let up know if anything else weird pops up and I will reopen it.

**Closed by ryan-rushton** 2021-02-24 03:21 UTC
Labels: Bug
