### ISSUE TITLE
Double-tap on mobile does not equip item.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2616] opened 2018-01-31 20:31 UTC
On desktop, players can double-click and equip an item to their current player.  On mobile, double-tap does not equip an item.  Instead, it opens the item popup.

**Comment by bhollis** [comment] 2018-02-01 07:50
I'll have to check but I think this is intentional. Double tap is zoom in ios

**Comment by duckmanBR** [comment] 2018-02-01 11:42
This is a duplicate of #2286 :sweat_smile: 
But it's not that.  It's something related to how the popup opening works.  If you have the "always show expanded..." unchecked, double tap always work.  If you check that it will only work for items that have a popup that doesn't cover the item when open.  Or I'm too slow on my double click.

**Closed** 2018-02-01 15:30 UTC
Labels: Bug
