### ISSUE TITLE
Ability to seek out specific masterwork in wishlist

### ISSUE THREAD

**Issue by AlexMax** [DestinyItemManager/DIM#4825] opened 2019-12-22 19:29 UTC
Is there some way of seeking out a specific weapon masterwork in a wishlist?  The COMMUNITY_CURATIONS.md document mentions them in passing as an option in "expert mode", but I couldn't figure out how to generate a wishlist with a specific stat masterworks pointed out.

I'm currently working on a [utility of my own](https://github.com/AlexMax/destiny-wishlist-generator) to generate wishlists, and I wanted to add support for masterworks, but at the moment the best way I know how to add them is to simply add them to the notes).

**Comment by imeredith** [comment] 2019-12-24 04:45
If you add perk=<masterwork id> I believe it will work. Basically anything that is socketable in an item can be used. Intrinsic perks, masterwork, probably even shader and ornament

**Comment by AlexMax** [comment] 2019-12-24 17:47
Oh.  So if I'm interested in masterworks of a certain stat, what should I be looking for?  Because I tried putting in the stat ID (like `4188031367` for Reload Speed) and that didn't seem to work, and I didn't see any other obvious "masterwork stat" ID's.

**Comment by 48klocs** [comment] 2019-12-26 13:27
Masterworks are finicky, since you currently need to account for all the levels of masterworking that there can be, as well as the possibility that you've got the wrong MW. Plus there are multiple versions of the "same" MWs.

I've moved to putting recommended MWs into wish list notes.

I named it expert mode for a reason. C-:

**Comment by AlexMax** [comment] 2019-12-26 18:09
> I named it expert mode for a reason. C-:

Hah. 😀 

No worries, I had some idea what I was getting into, but I didn't realize that masterworks had such a bonkers internal representation in Bungie's API.  Doesn't sound like I can do anything on my end until the wishlist format adds some sort of masterwork-specific feature to work around it - if that's even possible.

I appreciate the responses anyway.

**Comment by 48klocs** [comment] 2019-12-26 23:39
I have no plans to extend the format for that.

XM lists can represent masterworks today, it just explodes the number of permutations (one for every level of masterwork type you want + the roll without, since re-rolling is an option) you need to build to get there.

**Comment by AlexMax** [comment] 2019-12-27 00:43
I hope you might reconsider.  If I'm looking for a weapon with a specific masterwork, I don't particularly care what level masterwork it is, only which skill that is masterworked, and it seems kind of silly to require wishlists to balloon in size by 5 to 10 times in order to account for every possible masterwork per unique roll.  The code to do so would be trivial to implement, but I worry about file size and the time it would take to parse such a file.  Is there a practical upper limit on how big a wishlist file can be?

**Comment by delphiactual** [comment] 2019-12-30 07:32
plugCategoryHash maybe a workaround e.g. `https://data.destinysets.com/i/InventoryItem:186337601`

all 199786516 are handling mw

**Comment by bhollis** [comment] 2021-02-17 19:27
Dupe of #4299

**Closed by bhollis** 2021-02-17 19:27 UTC
Labels: Feature: Wish List
