### ISSUE TITLE
Error authorizing DIM

### ISSUE THREAD

**Issue by bhargavkaranam1** [DestinyItemManager/DIM#10056] opened 2023-11-06 09:24 UTC
### DIM Version

Version 7.93.0 (release), built on 06/11/2023, 07:26:53

### Browser Details

Chrome Version 119.0.6045.105 (Official Build) (64-bit)

### OS Details

Windows 10

### Describe the bug

Error authorizing DIM: A content blocker is interfering with either DIM or Bungie.net, or you are not connected to the internet. This might be a problem with DIM, or it might be an issue with Bungie.net or your browser.

Please follow our [Troubleshooting Guide](https://github.com/DestinyItemManager/DIM/wiki/Troubleshooting) to find a solution, and contact us if those steps don't work.

[Go back to DIM and try again](https://app.destinyitemmanager.com/)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

I am experiencing this issue from 06/11/23

**Comment by MakflyBes** [comment] 2023-11-06 09:48
Yes, yesterday there was such a problem, tell me what is the reason?

**Comment by robojumper** [comment] 2023-11-06 12:42
Duplicate of #10047.

**Closed by robojumper** 2023-11-06 12:42 UTC
Labels: Bug
