### ISSUE TITLE
Add +10/ +5 mods automatically

### ISSUE THREAD

**Issue by Daniel3009** [DestinyItemManager/DIM#8147] opened 2022-03-13 10:28 UTC
### Proposed change

Loadout Optimizer: Use +10 mods automatically:

Active this feature to select the END RESULTS in the stat filter 

For example T10 Dis T10 Recov 

Currently it only shows the armor pieces which can go up to T10/T10 while masterworked
In reality you have to check T5/T10  T6/T9 T7/T8 .... all possible combinations to see which armor gets T10/T10 when mods are applied

### How does this fit into your workflow?

Set up the wanted end results like  T10 Rec and T10 Dis

Optionally chose your subclass with stat boni

Click the button "use stat mods on armor if possible" 

If the stat mods don't fit because other mods were used - fine exclude them obviously. But if no other mods were used fit the stat mods in.

Show the results which have my desired stat combination after all possible mods were applied

Profit.

**Comment by robojumper** [comment] 2022-03-13 11:00
Duplicate of #7090.

**Closed by robojumper** 2022-03-13 11:00 UTC
Labels: Enhancement
