### ISSUE TITLE
Be able to change the shader and ornaments of the guns in a loadout

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#8574] opened 2022-07-14 11:21 UTC
### Proposed change

Be able to change the shader and ornaments of the guns in a loadout

### How does this fit into your workflow?

A chose fashion button for guns would be neat.

**Comment by bhollis** [comment] 2022-07-15 00:34
Duplicate of https://github.com/DestinyItemManager/DIM/issues/8097 (or at least, it'll be implemented by that)

**Closed by bhollis** 2022-07-15 00:34 UTC
Labels: Enhancement
