### ISSUE TITLE
Loadout Optimizer: Add option to change gear element.

### ISSUE THREAD

**Issue by akandratovich** [DestinyItemManager/DIM#5241] opened 2020-05-26 11:57 UTC
**Proposed change**
As you can select mods for the gear or assume it's masterwork, add option to override item element.

**How does this fit into your workflow?**
While trying to maximise the stats for the build and use particular elemental mods, I don't care if I need to change its' element. The same as I can assume it's masterworked, I'd like to have an option to override the element to unlock elemental mods.

**Comment by ryan-rushton** [comment] 2020-05-28 10:33
@bhollis I was talking about doing this the other day. 

Rather then override an element, I was thinking of ignoring the element on all gear. I would likely do this as part of the new mod picker stuff I am working on.

**Comment by bhollis** [comment] 2020-05-28 16:05
I don’t think we should necessarily ignore element by default since it does cost quite a lot to change. Maybe better to just have a checkbox like Assume Masterworked.

**Comment by ryan-rushton** [comment] 2020-05-28 22:52
Sorry, I should have included that, but yes that is the plan.

**Comment by nabsltd** [comment] 2020-06-02 00:25
I think you need more than a checkbox, because once gear actually is masterworked, changing the element is expensive.
Having an "ignore element if energy <= X", where the user can enter the "X" value. Default it to 10, and it will ignore all, but a user could pick 8 (no prisms or Ascendant Shards) if that's their threshold.

**Comment by bhollis** [comment] 2020-06-04 19:29
That's an interesting suggestion, and could be a good way to let people decide what their threshold for "this is changeable" is.

**Comment by ryan-rushton** [comment] 2020-06-04 22:34
I have a bit of time this weekend so I will see how feasible it is.

**Comment by nabsltd** [comment] 2020-06-19 15:18
#5329 is a completely different issue, and is an actual bug as far as current code is concerned.
The issue is Loadout Optimizer doesn't think that the mods can be slotted, even though the rest of DIM knows they can be.
It just happens that the mods that are affected are Seasonal mods that have no energy alignment.

**Comment by joshhunt** [comment] 2020-06-24 23:53
@ryan-rushton to provide a counter-viewpoint, I do not think that LO should _by default_ generate loadouts that ignore elemental affinities, requireing you to potentially change the affinity on gear.

LO now will generate load outs that can be quite costly to compare

![image](https://user-images.githubusercontent.com/46142/85638389-b14cf780-b67d-11ea-83a4-0d05bb7dfbdb.png)

Consider this - the top loadout (usually the only one I ever consider, the rest are superfluous) has no Arc + Arrivals mod slot, so i would need to spend quite a lot of mats to make it work.

![image](https://user-images.githubusercontent.com/46142/85638529-07219f80-b67e-11ea-8dc1-208cd0d1c58f.png)

If LO is going to suggest loadouts like this, it should make it clear that it requires changing elemental affinity at a (potentially significant) cost. Personally, I have no need for this.

**Comment by ryan-rushton** [comment] 2020-06-25 00:33
Just an update on this. I am planning on getting a slider happening so people can pick their energy threshold where they care about this. For me personally I will be making it so that 8-10 I care about energy and anything lower I dont.

The current state of this is that the seasonal mods section in the Perk Picker ignores energy. I might change this for the moment so we have something a little more consistent across the different ways of locking mods. When the mod picker is ready to go into beta I plan on having the energy threshold setting come in along side that.

**Comment by ryan-rushton** [comment] 2021-06-16 10:47
I am going to close this since I just added a select asking what you are willing to spend. In that we are allowing energy swaps as long as they fall into the chose material boundary. Happy to reopen should this not be enough but I think it is likely that we might just want some more options.

**Closed by ryan-rushton** 2021-06-16 10:47 UTC
Labels: Enhancement, Feature: Loadout Optimizer
