### ISSUE TITLE
Avoid moving recently transferred items when making room in a store.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#1180] opened 2016-11-13 03:31 UTC
When moving blue engrams to a character manually (for example), DIM will remove the least desirable item from the inventory to make room.  This often means that when transferring multiple blue engrams, that DIM will move an item I just transferred to make room.  This applies to any least desirable item as based on the function to get similar items.

It would be beneficial to create a lit of items that have been recently added to a store and avoid moving them when room  needs to be made.

**Comment by bhollis** [comment] 2017-10-18 03:11
Mostly duplicate of #739

**Closed by bhollis** 2017-10-18 03:11 UTC
Labels: Enhancement
