### ISSUE TITLE
Issues with losing my DIM Storage Saves

### ISSUE THREAD

**Issue by ness33** [DestinyItemManager/DIM#2328] opened 2017-10-08 14:04 UTC
Hi,
I'm currently using v4.18.0. In previous versions I've had issues with my tagged items and saved loadouts reverting to an earlier state (e.g. I had 40 loadouts and 400 items with tags or notes, then it goes back to about 25 loadouts and 150 items with tags or notes).

I am using my google drive save, which seems to work fine. But every now and again, I lose my progress, even though I have my save... and since its auto-saving, it overwrites my existing google drive save. I've had this happen to me at least 5 times now. I posted about this on the DIM subreddit, and was asked to post it here.

I didn't immediately post on here because I was waiting on the next occurrence. It never came. Now it is doing something slightly different. In the past, the loadouts and tagged items that I was losing was all for Destiny 2 (while my old Destiny 1 loadouts and tags remained). Currently, anything in my vault (in Destiny2) is suddenly being marked as new items, and it wipes the notes & tags I had on those items.

Because I've had these issues lately, I've been consistently generating backup data files, and so I'm not losing much anymore (restoring from a backup DIM Data file always restores the tags to the items in my vault).

Here's a screenshot before I lose my items:
https://i.imgur.com/HU33CjA.png
https://i.imgur.com/EwZ0N24.png

And here's a screenshot after all items in my vault get marked as new (as in, all items in my Vault have the shiny overlay, like they are new items) and I lose the notes & tags on those items:
https://i.imgur.com/SgAkQT3.png
https://i.imgur.com/1Q5l1et.png

Let me know if there's any other pertinent information I should be providing on here.

As always, thanks for everything DIM has done for the Destiny community. This is but a minor inconvenience compared to the improved QOL DIM has brought us!

**Comment by bhollis** [comment] 2017-10-10 07:12
I notice all the items that lost tags are from the vault. It seems like this may be caused by https://github.com/DestinyItemManager/DIM/issues/2195, which can be caused by loading DIM while Bungie.net is undergoing maintenance (though we haven't quite pinned it down). That'd explain why you only lose some but not all of the info, and why all your vaulted items look "new".

**Comment by ness33** [comment] 2017-10-15 03:27
Just thought I'd mention its happening again today. This time, all my items in my vault are showing as new (no Maintenance going on with the Bungie.net website that I know of). This time, it's clearing all my tags in the vault, and I load up a saved file, which restores it. Then like 5 mins later, it clears them all again and marks each item as new. Not sure why that is, or if others are having similar issues.

**Comment by bhollis** [comment] 2017-10-18 03:09
OK, this is definitely the same as #2195, then. I'm going to close this but link it to that issue.

**Closed by bhollis** 2017-10-18 03:09 UTC
Labels: Bug, Help Wanted: Developer
