### ISSUE TITLE
Classified items that have known power, are not contributing to is:maxpower

### ISSUE THREAD

**Issue by philkernick** [DestinyItemManager/DIM#9217] opened 2023-03-14 07:00 UTC
### DIM Version

current beta

### Browser Details

Chrome

### OS Details

Windows 11

### Describe the bug

A recent change to the API seems to be that classified items now report a power level, but no other details.  We are not considering this case in the calculation of is:maxpower.

Example, I have a RON Bond showing in DIM as power 1805.  The bond is classified, but does have a power level, but the is:maxpower filter picks the 1802 bond instead.

![image](https://user-images.githubusercontent.com/25425159/224920553-87dca9a0-ff52-44ad-b105-114503c37484.png)

**Comment by robojumper** [comment] 2023-03-14 10:48
Classified items report their power level if they're not vaulted but in one of your characters. The problem is that DIM cannot tell that this class item is a bond because it is classified -- the only thing we know is that it's something that goes in a class item slot.

**Comment by bhollis** [comment] 2023-03-16 02:19
Duplicate of #8430.

**Closed** 2023-03-16 02:19 UTC
Labels: Bug
