### ISSUE TITLE
Multiple exotics showing in loadout view due to new subclass exotic

### ISSUE THREAD

**Issue by ethano8225** [DestinyItemManager/DIM#10554] opened 2024-06-15 20:35 UTC
### DIM Version

Version (release), built on 6/9/2024, 10:04:20 PM

### Browser Details

Edge 126.0.0.0

### OS Details

Windows 10

### Describe the bug

Select loadouts - click optimize armor - clear existing build stats, exotic armor, mods, and pinned items - select no exotic or any exotic.
![image](https://github.com/DestinyItemManager/DIM/assets/29294321/454d5eda-34bf-4df3-ab39-c3554886e4b4)
![image](https://github.com/DestinyItemManager/DIM/assets/29294321/6774aed7-cbfd-4f0b-b89e-84e7a2b9c04c)

### Logs

```shell
I don't think logs are necessary?
```

**Comment by bhollis** [comment] 2024-06-15 22:39
Duplicate of #10547, already fixed in beta.

**Closed by bhollis** 2024-06-15 22:39 UTC
Labels: Bug
