### ISSUE TITLE
Can't access filter help on iPhone

### ISSUE THREAD

**Issue by mannyrye** [DestinyItemManager/DIM#9240] opened 2023-03-16 14:10 UTC
On my iPhone on the latest DIM and the beta, I can’t properly access the find help. The help pane appears clipped or only partially visible. 

![image](https://user-images.githubusercontent.com/20385998/225643468-0ff18003-d90b-4bf6-b981-b4682001322e.png)

![image](https://user-images.githubusercontent.com/20385998/225643543-cb430772-404d-4b3c-993a-031dab2688ec.png)

**Comment by bhollis** [comment] 2023-03-16 19:29
How are you using DIM? Installed from the App Store, added to Home Screen from Safari, directly from Safari, from another browser like Chrome, etc?

**Comment by mannyrye** [comment] 2023-03-16 19:47
AppStore app and beta saved as desktop bookmark. Both have the same behavior.

**Comment by bhollis** [comment] 2023-03-17 00:14
Can you find your user agent by visiting https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and paste it here?

**Comment by mannyrye** [comment] 2023-03-20 01:56
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

**Comment by bhollis** [comment] 2023-03-20 02:52
Did you select "Request Desktop Site"? Because the app thinks you're on macOS, not iOS.

**Comment by mannyrye** [comment] 2023-03-20 04:42
Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1

**Comment by mannyrye** [comment] 2023-03-20 04:47
As you can see in both these movies "Filters Help…" does not work on the AppStore app or the beta. I hope this helps. 

https://user-images.githubusercontent.com/20385998/226248961-875b0ff2-fb25-47cb-b40a-fba1a721fd34.MOV

https://user-images.githubusercontent.com/20385998/226248995-f4b08520-6620-4e76-ab49-fd68838a18c0.MOV

**Comment by bhollis** [comment] 2023-03-20 05:33
Hmm interesting now it's reproducing for me. I wonder what changed.

**Comment by bhollis** [comment] 2023-03-22 16:26
I think that this is the sheet chnage - it's locking the max height before the contents have loaded

**Comment by ryan-rushton** [comment] 2024-05-08 22:33
@mannyrye can you test and report back for me? I believe this should be fixed now.

**Comment by mannyrye** [comment] 2024-05-08 22:35
Hi,

It works. Thanks.

--
Dr. Ramón M. Figueroa-Centeno, Ph.D.
Associate Professor of Mathematics
University of Hawai‘i at Hilo
________________________________

**Closed** 2024-05-09 08:31 UTC
Labels: Mobile Interface
