### ISSUE TITLE
Remove "Any Class" loadout option

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/DIM#9624] opened 2023-07-17 20:00 UTC
Only 0.6% of saved loadouts have chosen the "Any Class" option. Instead of having an "Any Class" switch, we should set the class type automatically based on what items are in the loadout. A loadout with nothing class-specific can be implicitly "Any Class".

**Comment by robojumper** [comment] 2023-07-17 21:17
Duplicate of #9535?

**Closed** 2023-07-17 23:43 UTC
Labels: Feature: Loadouts
