### ISSUE TITLE
Counts below "Vault" are wrong

### ISSUE THREAD

**Issue by DaoFerret** [DestinyItemManager/DIM#2268] opened 2017-09-28 21:40 UTC
The counts below Vault are wrong.
Currently in D2 the Vault has 200 slots.  Any weapons, armor, consumables, mods or shaders placed in the vault use one of those slots.

Additionally, the user inventory (shared across all three characters) contains 50 slots each for consumables, mods, and shaders.

DIM currently does not properly include consumables, mods and shaders that are in the Vault in its "Vault used" count.

Additionally, the Consumables, Mods, and Shaders that are in the Vault that should be included are instead used as the "in use" portion of the three aforementioned 50 slot groups.

For example, in the attached file, the total vault size used should be 142 (124 weapons/armor+3 shaders+15 mods), the Consumables should be: 25/50, Mods should be: 47/50 and Shaders should be: 48/50
![capture1](https://user-images.githubusercontent.com/28707596/30991661-f94581de-a473-11e7-9a05-0e1f717de783.PNG)

**Comment by thezoggy** [comment] 2017-09-29 23:08
dupe of https://github.com/DestinyItemManager/DIM/issues/2245 ?

**Comment by bhollis** [comment] 2017-09-30 02:33
Yup! The only issue here appears to be related to transmat effects and ornaments.

**Closed by bhollis** 2017-09-30 02:33 UTC
