### ISSUE TITLE
Display filtered item count in search bar

### ISSUE THREAD

**Issue by vivekhnz** [DestinyItemManager/DIM#4001] opened 2019-07-14 02:25 UTC
A nice-to-have feature would be displaying the number of items that match the current filter. 

Possible use cases include:
- Counting how much inventory space can be reclaimed by deleting all items tagged as junk (`tag:junk`)
- Counting how many junk items are being 'saved' for infusion fuel (`tag:junk power:750`)

I think this count should be displayed inside the search bar at wider page widths only. For example:

![dim-search-match-count](https://user-images.githubusercontent.com/17512262/61178539-e5810100-a642-11e9-90ae-f6de361f5996.gif)

For the above GIF, I hid the matched item count when the page width is less than 1445px.

**Comment by bhollis** [comment] 2019-07-14 02:29
I like the idea of hiding it on smaller screen sizes.

I'd hoped to save this for our big search revamp, since it requires looping through all the items to count the matches, which is in addition to the items themselves filtering, so it doubles the work that gets done on searches. But maybe that's not a big deal?

**Comment by philkernick** [comment] 2019-07-17 03:33
Dupe of #3478

**Closed** 2019-07-19 03:46 UTC
Labels: Feature: Search
