### ISSUE TITLE
When comparing weapons, include weapons currently available from vendors

### ISSUE THREAD

**Issue by CallumHibbert** [DestinyItemManager/DIM#8799] opened 2022-10-22 17:39 UTC
Sometimes a vendor sells a good roll of something I already own. To compare the rolls I have to switch between the "Inventory" and "Vendors" screens.

It would be really convinient to have a compare option that included all my currently owned items and the vendor item.

Thanks.

**Comment by humandxp** [comment] 2022-11-10 23:59
how about do that in reverse, go to vendor click weapon and then you have compare. what you say would be more usefull to use with armors and in loadout organizer. so dim would show if any xur armor is worth buying

**Comment by humandxp** [comment] 2022-12-05 00:06
how that isnt yet as solved?

**Comment by bhollis** [comment] 2023-03-08 02:03
Duplicate of https://github.com/DestinyItemManager/DIM/issues/6878

**Closed by bhollis** 2023-03-08 02:03 UTC
Labels: Enhancement, Feature: Vendors, Feature: Compare
