### ISSUE TITLE
Vault is empty when the players data loads.

### ISSUE THREAD

**Issue by SunburnedGoose** [DestinyItemManager/DIM#2195] opened 2017-09-21 21:21 UTC
This issue is referenced by #2194 and I been getting reports about the vault not rendering.

![image uploaded from ios](https://user-images.githubusercontent.com/984608/30719360-d68f1942-9ee8-11e7-9a51-333c93dba5bd.jpg)

**Comment by kyleshay** [comment] 2017-09-21 22:26
any details on how to reproduce? re-occurring issue?

**Comment by bhollis** [comment] 2017-09-22 02:44
It'd be good to even understand what the response is (`privacy`?) so we know how to detect and handle it.

**Comment by DaoFerret** [comment] 2017-09-26 17:41
Just loaded new version (16.1), filtered for is:dupe, clicked "refresh data" button, not seeing any vault items.  Running in chrome, tried closing and reopening the tab, vault items still not there.  Will try closing and reopening browser completely next.

**Comment by SunburnedGoose** [comment] 2017-10-01 22:44
https://twitter.com/taknliv3s/status/914611986993790976

Another user.

**Comment by SunburnedGoose** [comment] 2017-10-01 22:44
https://twitter.com/taknliv3s/status/914611986993790976

Another user.

**Comment by DaoFerret** [comment] 2017-10-02 16:45
Have not noticed DIM missing my vault recently (thank you all for all your hard work).  Whatever changed may have fixed it (for me).

I also have been subject to the lovely "game crash when flying into tower" bug ... is it possible that they're both related to some instability in Bungie's API?

**Comment by bhollis** [comment] 2017-10-06 01:55
We've gotten more reports of this during API downtime. I'm not sure how we'd plumb through the info that it's not there, especially when we can't reproduce it to test.

**Comment by bhollis** [comment] 2018-01-29 08:14
Anyone seen this recently?

**Closed** 2018-03-05 00:05 UTC
Labels: Bug, Need More Details
