### ISSUE TITLE
Enhance is:duplicate  command

### ISSUE THREAD

**Issue by inoah1** [DestinyItemManager/DIM#3517] opened 2019-01-04 03:07 UTC
Would it be possible to update the is:duplicate command or create a new command similar that shows duplicate weapons/armor that have the same perks.

For example, if I have two Kindled Orchid with outlaw and ambitious assassin, I'd like to know this so I can delete one.

Don't need to have duplicate weapons with the same exact rolls.

**Comment by bhollis** [comment] 2019-01-04 04:40
Duplicate of https://github.com/DestinyItemManager/DIM/issues/3255

**Closed by bhollis** 2019-01-04 04:40 UTC
