### ISSUE TITLE
Crimson Not showing up

### ISSUE THREAD

**Issue by Ciarston** [DestinyItemManager/DIM#2459] opened 2017-12-09 00:06 UTC
After I received my Crimson Exotic Hand Cannon, it doesn't actually show up in DIM at all.

**Comment by sirdoombox** [comment] 2017-12-09 01:20
#2453 already have an active issue for this.

**Comment by Ciarston** [comment] 2017-12-09 02:56
Thanks!

**Comment by bhollis** [comment] 2017-12-09 03:08
Duplicate of #2453

**Closed by bhollis** 2017-12-09 03:08 UTC
