### ISSUE TITLE
Mods in Loadout Optimizer not working

### ISSUE THREAD

**Issue by GreySkylet** [DestinyItemManager/DIM#6280] opened 2020-12-05 13:11 UTC
6.41.1

Google Chrome OS

I started a blank loadout in optimizer, selected a mod which cost 1 energy, and I expected all valid loadouts to appear (there should be many), but instead I got the "No builds found" message.

**Comment by delphiactual** [comment] 2020-12-05 15:42
Screenshot

**Comment by GreySkylet** [comment] 2020-12-05 15:45
![loadout-optimizer](https://user-images.githubusercontent.com/75529288/101247325-e66f7280-3710-11eb-83de-cf9cc6e32262.png)

**Comment by GreySkylet** [comment] 2020-12-05 16:04
Wanted to add, I've tried it on my other character, and it works fine. Seems to only be bugged for the second character I made.

**Comment by ryan-rushton** [comment] 2020-12-06 08:23
I will have a dig and see what I can find.

**Comment by GreySkylet** [comment] 2020-12-06 08:27
Thanks

**Comment by GreySkylet** [comment] 2020-12-07 06:57
After messing around with optimizer some more, most mods will work, but equipping any "general" stat boosting mod automatically returns 0 results.

**Comment by ryan-rushton** [comment] 2020-12-07 08:30
@GreySkylet, can you give me some screen shots of what armour you have available when no mods are selected and you have results? I can't reproduce it by just locking mods general stat mods.

**Comment by GreySkylet** [comment] 2020-12-07 08:33
Ok, will do as soon as I get home.

**Comment by GreySkylet** [comment] 2020-12-07 18:24
![image](https://user-images.githubusercontent.com/75529288/101389368-3c7f1a00-38b9-11eb-9c7a-72a7782a61b6.png)
![image](https://user-images.githubusercontent.com/75529288/101389416-4f91ea00-38b9-11eb-8bed-a2af5015c3ed.png)
![image](https://user-images.githubusercontent.com/75529288/101389456-5fa9c980-38b9-11eb-86fa-cdc7ce995b50.png)
![image](https://user-images.githubusercontent.com/75529288/101389494-6df7e580-38b9-11eb-8cf5-5403f11de8a1.png)
Here.

**Comment by delphiactual** [comment] 2020-12-07 18:27
Can you post logs from the developer console

**Comment by GreySkylet** [comment] 2020-12-07 18:31
No, I can't access it.

**Comment by bhollis** [comment] 2020-12-07 18:31
I'll go out on a limb and guess that green warlock bond is the problem.

**Comment by GreySkylet** [comment] 2020-12-07 19:14
Huh, ok. I'll try _obliterating_ it.

**Comment by GreySkylet** [comment] 2020-12-07 19:16
Moved it to the vault,and hey, it worked! Thanks everyone!

**Comment by bhollis** [comment] 2020-12-07 19:36
... the fact that moving it to the vault changed anything is *also* concerning

**Comment by GreySkylet** [comment] 2020-12-08 06:39
Hmm. I've kept the full Warlock starter set (and moved it all to the vault), if you want to use my account to test anything just @ me.

**Comment by delphiactual** [comment] 2020-12-08 06:55
Thanks for the offer but it is not needed

**Closed** 2020-12-13 00:06 UTC
Labels: Bug, Feature: Loadout Optimizer
