### ISSUE TITLE
Iron Banner focusing set not marked as unlocked

### ISSUE THREAD

**Issue by Revadike** [DestinyItemManager/DIM#9360] opened 2023-04-04 20:49 UTC
###
![image](https://user-images.githubusercontent.com/4411977/229917266-32fab247-06bb-46c6-b70b-4098a5ccc640.png)
****

**Comment by robojumper** [comment] 2023-04-04 21:37
I think this is not a bug. There are two different version of the Iron Truage suit (that look a fair bit different) in collections and even the game agrees -- focusing legacy IB armor that you have unlocked costs 1 engram and 25 legendary shaders, while focusing focusing legacy IB armor you haven't unlocked costs 3 engrams and 50 shards. In your screenshot, the set you expect to be marked as unlocked costs the increased amount, leading me to believe that the game itself considers this set not yet unlocked and DIM has the same behavior.

**Comment by Revadike** [comment] 2023-04-04 21:42
I didn't spot any other Iron Truage entries in my collections, though

**Comment by robojumper** [comment] 2023-04-04 21:47
Chances are one might pop up if you focus one of these items. Iron Truage is definitely a uniquely weird set with its two copies, but DIM really simply follows what the game says here and I'd argue behaving differently here would be wrong.

**Closed** 2023-04-08 20:07 UTC
Labels: Bug, Feature: Vendors
