### ISSUE TITLE
u.g(t) is undefined

### ISSUE THREAD

**Issue by mc711** [DestinyItemManager/DIM#4700] opened 2019-11-11 09:14 UTC
i don't know what happened. was working one minute then started showing this error. have to delete local cache, but error returns once it syncs to google. tried restoring older version but error returns.

**Comment by 48klocs** [comment] 2019-11-14 01:01
Could you give us some more details about the error?

What version of DIM, what browser, what OS, anything specific you're doing when you see the error, and a console log of the error (if you're on desktop) would be helpful.

**Comment by mc711** [comment] 2019-11-14 06:43
DIM 5.56
Firefox 70.0.1
Windows 10

As far as i could tell, i think a item was causing the error.  I backed up my current settings causing the error then reset everything (cleared browser data, deleted google sync data). 
When i restored my backup, the settings showed up for a quick second then caused the error. I even tried to do a clean backup (just settings and one tag to get JSON structure) and just copied over the JSON data of my items to the clean config, but that caused the same error too.

In the end, I just said fuck it and started brand new. No error since. 
Sorry i don't have any logs or the old backups anymore.

**Comment by delphiactual** [comment] 2019-11-14 12:07
I think possible dupe of #4699

**Comment by bhollis** [comment] 2019-11-15 16:26
Best we can hope for is to find this error in Sentry.

**Comment by delphiactual** [comment] 2019-11-16 18:26
https://sentry.io/organizations/destiny-item-manager/issues/1327149817

**Closed by delphiactual** 2019-11-16 18:26 UTC
Labels: Need More Details
