### ISSUE TITLE
Faction Rally Tokens interfere with the Gather factions items logic.

### ISSUE THREAD

**Issue by QuixoticWolf** [DestinyItemManager/DIM#2669] opened 2018-03-05 20:58 UTC
As the title says, I was unable to gather any of my reputation items because I had 2 NM tokens (non transferable). The workaround seems to move stack by stack of items manually to the vault or discarding the rally tokens.

**Comment by duckmanBR** [comment] 2018-03-06 01:10
Yeah, we had it reported on [reddit](https://www.reddit.com/r/DestinyItemManager/comments/7z36yl/gather_reputation_items_command_not_working) but I couldn't look at that, but I couldn't reproduce with FWC tokens.
I'll try to look at it this week.

**Comment by bhollis** [comment] 2018-03-06 04:02
Hmm, the code specifically filters out non-transferable items. Could it have been a bug in the API?

**Comment by duckmanBR** [comment] 2018-03-06 12:54
yeah, I saw the notransfer part but couldn't debug to check what was happening

**Comment by swable** [comment] 2018-03-07 04:13
After turning in all faction rally tokens this problem persists for me ("Gather Reputation Items"). It also fails if I search "token" and attempt to transfer that filter to my vault. 

Mid-writing this report, I attempted to transfer all reputation items to my player through the same "Gather Reputation Items" button, this worked. When attempting to return the items to the vault through the GRI button, all items except 3 stacks of Gunsmith rewards, and a single simulation seed stack transferred. Total items transferring into inventory was 32, total items transferred out was 28.

Single item transfer works fine.

**Comment by bhollis** [comment] 2018-03-07 05:06
I think there's a different bug where if you have multiple stacks of items, only one stack will get transferred.

**Comment by bhollis** [comment] 2018-03-07 06:21
Wow, I actually found a bunch of bugs around stackables and this loadout. Let me make a PR.

**Closed** 2018-03-18 00:10 UTC
Labels: Bug, Feature: Loadouts, Need More Details
