### ISSUE TITLE
colorblindness options cause the entire interface to disappear

### ISSUE THREAD

**Issue by Selth** [DestinyItemManager/DIM#4494] opened 2019-10-18 18:30 UTC
selecting on firefox any colorblindness option causes the entire interface to disappear, only a grey screen remaining.
![image](https://user-images.githubusercontent.com/4332162/67118812-a46a3100-f1dd-11e9-9a51-b7afa4ba9f53.png)

**Comment by duckmanBR** [comment] 2019-10-18 18:45
Dupe of #4483

**Closed by duckmanBR** 2019-10-18 18:45 UTC
