### ISSUE TITLE
Comparing a vendor item from triage leaves it out of the comparison

### ISSUE THREAD

**Issue by UndarkAido** [DestinyItemManager/DIM#9182] opened 2023-03-04 20:24 UTC
### DIM Version

Version 7.58.1.1002340 (beta), built on 3/4/2023, 1:12:57 PM

### Browser Details

Firefox, 110.0 (64-bit), PWAsForFirefox 2.4.1

### OS Details

Windows 11 (DIM says Windows 10)

### Describe the bug

If you click on a vendor item > triage > compare it isn't listed in the comparison like if you click the normal compare
![image](https://user-images.githubusercontent.com/7421794/222927150-23f1d9e8-734b-4fa0-bf5c-4098c8d5f5a1.png) -> ![image](https://user-images.githubusercontent.com/7421794/222927165-2b46cbc8-3ddf-4052-b3bc-cd5392a8f97d.png)

and

![image](https://user-images.githubusercontent.com/7421794/222927188-be5988b8-627d-4099-b128-85719fdf2ba1.png) -> ![image](https://user-images.githubusercontent.com/7421794/222927198-dea95292-e85f-41ed-b55b-87c86066e6cc.png)

### Logs

[console-export-2023-3-4_14-22-33.txt](https://github.com/DestinyItemManager/DIM/files/10889610/console-export-2023-3-4_14-22-33.txt)

**Comment by bhollis** [comment] 2023-07-29 04:34
I can't reproduce this - is it still happening for you?

**Comment by robojumper** [comment] 2023-07-30 00:51
I think this was fixed with #9611.

**Closed by robojumper** 2023-07-30 00:51 UTC
Labels: Bug, Feature: Vendors, Feature: Compare, Feature: Triage
