### ISSUE TITLE
Perk details do not display

### ISSUE THREAD

**Issue by JCH1970** [DestinyItemManager/DIM#6173] opened 2020-11-15 12:56 UTC
On my iPhone se2020 running IOS 14.1 when I tap on perk icons to display the name details of a perk no longer display.

I have tried on both Safari  and Chrome with the same result.

**Comment by bhollis** [comment] 2020-11-15 16:58
Have you scrolled within the popup at all?

**Comment by JCH1970** [comment] 2020-11-15 20:27
There is nothing to scroll down to below the perk icons.

**Comment by bhollis** [comment] 2020-11-15 21:27
Screenshot? Here's mine:

![image](https://user-images.githubusercontent.com/313208/99197260-41cbc780-2746-11eb-88e5-3e3b66ca2fe8.png)

**Comment by JCH1970** [comment] 2020-11-15 22:14
![8BFDC3ED-EE9A-4155-B49D-B1A6D9012D01](https://user-images.githubusercontent.com/74490401/99198284-93e50b00-278f-11eb-9c07-a5d062698fab.png)
Similar screenshots, except I can’t get the text box to come up as per your screenshot.

**Comment by bhollis** [comment] 2020-11-15 22:32
Yeah, see you scrolled down to see the perks. That means this is a duplicate of #5518

**Closed by bhollis** 2020-11-15 22:32 UTC

**Comment by bhollis** [comment] 2020-11-15 22:33
One thing you can do that'll help is to install DIM to your home screen, you'll get a ton of vertical space back.

**Comment by JCH1970** [comment] 2020-11-15 22:44
I have DIM On my Home Screen, but it opens in Safari. Is there a way to do it differently?

**Comment by bhollis** [comment] 2020-11-16 00:58
It should open as a fullscreen app, if you add it from Safari

**Comment by JCH1970** [comment] 2020-11-16 09:26
That seems to be a connected issue.

I deleted DIM from my Home Screen and reinstalled it (now have an orange icon). Now when I launch from the home screen DIM is full screen and the perk text appears when I hold my finger on the icons.

Many thanks for your help.
