### ISSUE TITLE
Pin Current Loadout in Optimizer List

### ISSUE THREAD

**Issue by Korrasera** [DestinyItemManager/DIM#9755] opened 2023-08-23 07:15 UTC
### Proposed change

Inside the optimizer your current loadout appears in the list of available choices, tagged with an 'Existing Loadout: <loadout name>' entry. When you first open the optimizer it's easily visible because it's the only computed loadout choice. When the pinned equipment is unpinned, the optimizer starts computing additional loadouts and the existing loadout is sorted in that list as any other loadout. This could push it off the screen if the optimizer finds several loadouts that would provide better stats.

This makes it difficult to compare existing loadouts with any newly computed loadouts. The 'compare loadout' button doesn't really do a good job of handling this functionality because it presents the information in a completely different format, and it also compares only the two loadouts, existing and the one chosen for comparison. Here's an example of the existing loadout being pushed down the list far enough that you have to scroll to see it:

![image](https://github.com/DestinyItemManager/DIM/assets/118650/d346c1a6-8574-43a3-9ae3-713ba3184c3b)

Instead, the existing loadout should be pinned to the first page of the computed loadout list so that it can be easily compared with new loadouts the optimizer finds. That way you'll be able to compare stat values, stat distributions, and power levels at a glance. And instead of just using the existing loadout text, it could be wrapped in a box of some kind to indicate that it's the original loadout being compared. 

Personally, I think it would work well if the existing loadout was a floating entry that stayed visible on the computed loadouts page and featured a button that scrolled the list to where it would normally sit, so that it's always visible and can also be put back in the original context.

Here's a very rough mockup:

![1](https://github.com/DestinyItemManager/DIM/assets/118650/7d83170c-dec5-4650-b4eb-84a4ee377430)

### How does this fit into your workflow?

This would improve the functionality of the loadout optimizer when building new loadouts because it would make it much quicker and easier to compare existing loadouts to new options found by the optimizer. Depending on need you might want to update a loadout to get all the stat points available, pick a different stat distribution, or just look to enhance a particular stat block. Adding this functionality to the optimizer would make it much easier to do all of that when updating a loadout.

**Comment by bhollis** [comment] 2023-08-23 07:52
Yep that's part of the plan for redesigning the optimizer UI

**Comment by robojumper** [comment] 2023-08-23 11:33
Linking #9161.

**Comment by bhollis** [comment] 2023-08-23 16:58
Resolving as a duplicate of #9161 but thanks for the clear feature request and mockups!

**Closed by bhollis** 2023-08-23 16:58 UTC
Labels: Enhancement, Feature: Loadout Optimizer
