### ISSUE TITLE
Feature Request: New line break at class change in vault

### ISSUE THREAD

**Issue by jwanja** [DestinyItemManager/DIM#5185] opened 2020-05-13 20:49 UTC
For the armor stored in the vault, can there be an option to insert a new line when the class changes?

Currently lets say I have 5 gloves for each class in my vault. There will be the symbol for the first class then the 5 items for that class, after which the symbol for the next class and the 5 items for the second class, and finally the thrid class symbol and its items.

I feel like the interface could be clearer if it broke each class onto it's own line.

**Comment by bhollis** [comment] 2020-05-14 06:21
Duplicate of #3613, except asking to separate by class instead of by type.

**Closed by bhollis** 2020-05-14 06:21 UTC
