### ISSUE TITLE
Save Data (loadouts and tags) gone (Beta) from 2 weeks

### ISSUE THREAD

**Issue by mistral13** [DestinyItemManager/DIM#3323] opened 2018-11-16 15:23 UTC
I lost all my loadout from the last 2 week. I‘m also missing the 200-300 tags on my items i made in that time.
Cant restore the data form this time periode (google drive)
Anybody got an idea? Could it be that not all backup data is displayed? 

https://i.imgur.com/3fRKc25.png

**Comment by bhollis** [comment] 2018-11-18 04:21
So when you tap on "load content" you don't see any that have tags and loadouts?

**Comment by mistral13** [comment] 2018-11-18 12:48
They have tagged items, but only the 130-150 I had three weeks ago. Last weekend I marked almost all my items and all of them are missing. The stored data between 1.11 and 14.1 are missing.

**Comment by bhollis** [comment] 2018-11-18 21:57
Unfortunately we don't know what's going on here. Do you have any more information? I can guess that you're using Safari - what version? Did you have Google Drive connected when you tagged those items? How much space do you have free on Google Drive?

**Comment by bhollis** [comment] 2018-11-18 23:12
Duplicate of #2713.

**Comment by mistral13** [comment] 2018-11-19 07:13
I used Safari on my iPad with iOS 12. 
from my point of view, I was logged in the whole time. Google Drive almost empty (over 13GB free).
Shortly before the 14.1 an update of the beta was installed (with the green markings), could it have something to do with it?

**Comment by blanchie69** [comment] 2018-11-29 02:57
I haven't created any loadouts, however I did tag a ton of items and none of my tags are available as of today. I tried loading backup data from Google Drive, but none of those backups seem to have any of the tags, and none of the backups are from the last couple of days. 

This is not the first time that this has happened, it seems random when the tags disappear, the previous times were on the regular app, but I'm currently using the beta version.

Google Drive has been connected for several days now and I have more than enough free space. It's frustrating spending the time tagging items and then not only not having the tags appear wherever I'm looking at DIM (between computers or in the android app), but also not knowing how long they'll last, it practically makes them useless. 

Browser: Google Chrome Version 70.0.3538.102
OS: Windows 10

Also, the tags are white text on a white background at the moment in the beta app and you can only tell what they are when you hover over them to see white text on a light grey background.

**Comment by delphiactual** [comment] 2018-11-29 03:02
@blanchie69 That is because this is a google drive problem, not a DIM problem...

**Comment by blanchie69** [comment] 2018-11-29 03:07
The issue was occurring before I signed into Google Drive, I signed into Drive hoping/expecting that it would actually save the tag data. Is DIM not supposed to save the tag data even with local browser storage?

**Comment by delphiactual** [comment] 2018-11-29 03:11
DIM does save to local browser storage, none of the devs have been able to reproduce the disappearing tags/loadouts to even try and begin to formulate a fix.

**Comment by bhollis** [comment] 2018-11-29 16:13
This is a long term bug that we know about but haven’t found a fix for. There’s another issue we should deduplicate this into. DIM is an open source project, and what would help at this point is PRs that fix the bugs or make it easier to figure this out.

**Comment by delphiactual** [comment] 2018-11-29 16:31
#2713

**Closed by delphiactual** 2018-11-29 16:31 UTC
Labels: Bug, Infrastructure: Sync
